RetroAchievements/RAWeb

lib/dynrender.php

Is merging here enough to change on the site? :thinking: 
Well, waiting a more experienced guy check this... ;)

renamed "Neo Geo" to "Neo Geo Pocket" - closes #77

---

lib/utils.php

Reverts RetroAchievements/RAWeb#103
it affected Rich Presence and Forum posts. Will try to find another workaround.

Revert "[DON'T MERGE] seekPOSTorGET returns only ascii chars"

---

public/download.php

IMHO this section doesn't fit very well on this page. People usually come here to download the emulators.
Also, I'm planning to add a "Free ROMs" page on the docs. This way the community can update more dynamically, adding links to the ROMs and to the sets we already have on the site.

getting rid of "Free Genesis ROMs" section

---

lib/dynrender.php

closes #37 
It's just a small change on the code. I tagged you guys as reviewers just to know if you agree with the request in #37 by @kdecks and @JuliaWolska .

remove Welcome! section for signed in users

---

lib/dynrender.php
public/index.php

Maybe some pictures can explain better...
On a big screen:
(don't mind the error messages, please)
On mobile:

Publicizing docs

---

public/js/all.js

Resolves https://github.com/RetroAchievements/RAWeb/issues/115

Correct hyperlink for leaderboard tooltips.

---

public/gameInfo.php

**WARNING: this was blind-coded!!**
No big changes are happening on this PR. I tested the PHP behavior with dummy data and it seems to work fine. But as I'm still unable to reproduce the website environment locally, maybe it worths some testing before merging...
---
This PR is intended to show the Achievement authors on each game page that has achievements, like in the example below:

Show achievement authors on the game's page

---

public/achievementList.php

- refactored some if-else sentences
- added a link to show only achievements in the Core Set.
- added a column to show the Modified Date and a link to sort by this date. Which will be very useful to see what changes are being done in cheevos (since we don't have an audit log).

cheevos list: Core only filter and Modified column

---

lib/database/achievement.php
lib/database/game.php
public/achievementList.php
public/gameList.php
public/userInfo.php

This PR adds a filter in [gameList.php](http://retroachievements.org/gameList.php) making it able to show all games which a dev worked on. The page will look like this:
Same filter thing for [achievementList.php](http://retroachievements.org/achievementList.php?s=17), making it able to see all achivements created by a dev. And it will look like this:

cheevos and game list by dev

---

lib/database/user.php
public/userList.php

Added options to filter the User List by account type, like in the image below:

filter user list by account type

---

lib/database/tickets.php
public/userInfo.php

**WARNING**
This PR needs more tests. I'm not very used to SQL queries and I'm not sure if the one I created here is good enough.
---
Like in this mockup made by @GameDragon2k but with a link to the ticketmanager listing the tickets for the respective dev:

Show number of open tickets on the devs page

---

public/ticketmanager.php

Some tweaks on the breadcrumb and also rearranged the columns when looking details of a single ticket (using the same format as I used on #129 ).

more tweaks on ticketmanager

---

lib/database/tickets.php
public/ticketmanager.php

Added on `ticketmanager.php` a feature to show the "Top N Games Sorted By Most Outstanding Tickets".
Like this:

show "Top N Games Sorted By Most Outstanding Tickets"

---

lib/database/game.php
public/gameInfo.php
public/linkedhashes.php

Pretty much what the title says.
The link on the game's page looks like this:
Not sure if it's the best option. We can change it later if someone has a better approach for design.

showing linked hashes to regular users

---

lib/database/utility.php
public/attemptunlink.php

- added an option to unlink a single hash entry.
- Moved the red Warning to the top
- changed the "leave me a message" link, instead of sending a PM to `Scott` send it to `RAdmin`.
The attemptunlink page will look like this:
closes #2

add an option to unlink a single hash entry

---

lib/database/game.php
public/gameInfo.php

This PR adds a link in the "Dev (click to show)" menu, as in this screenshot (the 2nd link):
When listing unofficial achievements, the "Achievements" heading will look like this:

make developers able to list unofficial achievements

---

public/viewtopic.php

Doing as requested by @kdecks on issue #34.

only admins can manage forum topics - closes #34

---

lib/database/tickets.php
public/achievementInfo.php
public/ticketmanager.php

cheevo's page: show number of open tickets for the respective achievements

---

public/reportissue.php

@GameDragon2k here's what we talked about few days ago...

dropdown list to select a linked hash when opening a ticket via web

---

public/userInfo.php

These variables aren't used in any other part of userInfo's code.

cleanup: removing unused variables/function calls

---

lib/database/game.php
public/gameInfo.php

Related issue: #13 
Related PR: #149

added sort by "Date Won" on the game's page

---

lib/database/game.php
public/gameInfo.php

Reverts RetroAchievements/RAWeb#171
not working as expected...

Revert "added sort by "Date Won" on the game's page"

---

lib/database/achievement.php

Avoiding that April's fool prank...

no bad chars for titles and descriptions

---

lib/database/tickets.php
public/dorequest.php
public/requestupdateachievement.php

This PR makes a comment be added to an achievement's page every time it is changed.

pseudo audit log for achievements

---

lib/database/achievement.php
lib/database/tickets.php
public/requestupdateachievement.php

another approach for the audit log makeshift

---

lib/database/achievement.php
lib/database/tickets.php
public/requestupdateachievement.php

Reverts RetroAchievements/RAWeb#180

Revert "another approach for the audit log makeshift"

---

lib/database/utility.php

Added some validation

---

public/faq.php

I realize we don't use this page anymore, but no point in having any link to them :)

remove link to rom sites

---

lib/database/utility.php
public/achievementInfo.php

Also, handle Values (not Mem nor Delta) in the left operand.
fixes #231 
**WARNING!**: untested code. I'll test it soon.

cleaner view for AddSource/SubSource/AddHits

---

lib/database/tickets.php
public/ticketmanager.php

**DO NOT MERGE**
I didn't test it yet.

dirty hack to list tickets for unofficial cheevos

---

lib/dynrender.php

It's probably fine, but I'll make more tests before merging.

fix "multiple [url] tags in the same line" bug - fixes #264

---

public/download.php

Reword emulator licensing information

---

public/download.php

@Jamiras is it what you had in mind?

add note about upgrading

---

lib/dynrender.php
public/gameInfo.php
public/leaderboardinfo.php

Official topic devs only

---

lib/database/utility.php

show AndNext and Prior in "Mem Explained"

---

lib/database/achievement.php
lib/database/activity.php
lib/database/forum.php
lib/database/friend.php
lib/database/game.php
lib/database/history.php
lib/database/lbs.php
lib/database/message.php
lib/database/news.php
lib/database/rating.php
lib/database/static.php
lib/database/tickets.php
lib/database/user.php
lib/database/utility.php
lib/dynrender.php
public/achievementInfo.php
public/achievementList.php
public/feed.php
public/gameInfo.php
public/leaderboardinfo.php
public/userInfo.php

There's no functional changes here, only coding style changes in some files, trying to addhere to [PSR-1](https://www.php-fig.org/psr/psr-1/) and [PSR-2](https://www.php-fig.org/psr/psr-2/).
Also, replacing tabs with 4 spaces.
**Please do not merge it**, I'm still working on it.

Coding style: trying to addhere to PSR-1/PSR-2

---

lib/dynrender.php
public/index.php
public/js/ping_chat.js

Add rel="noopener" to all links with target="_blank" to prevent phishing attacks.

Add rel="noopener" to links opening in new tab

---

lib/database/forum.php

Updated GameFAQs/Longplay/Wikipedia auto generated game topic hyperlinks to include the system. Updated the longplay URL to search youtube.com rather the longplays.org.
#307

Game Topic Longplay URL Invalid

---

lib/database/user.php

~~Not tested yet...~~
Tested and working as expected.

don't notify banned users - closes #318

---

lib/dynrender.php
public/js/all.js
public/largechat.php

Change flash objects for newer Twitch iframes. Fix for select, which didn't work earlier (videos are blank, as they doesn't exist). Remove button "RA Cinema", as it was linking to the same page (largechat.php).

Fix cinema in largechat.php

---

public/achievementInfo.php

This update would add the ability to promote achievements to official from the web.

Allow achievement promotion through the web.

---

lib/database/game.php

Validate Sega Saturn's console ID on the website.

Update game.php (Saturn)

---

lib/dynrender.php

Adds Sega Saturn to site dropdown

Update dynrender.php (Saturn)

---

lib/dynrender.php

The replacement of twitch links with the embedded twitch player seemed to assume
that the text it operated on only contained the twitch link and nothing else. It
also assumed that if 'twitch.tv' was present in the text, the rest of the text
was a properly formed twitch link.
Fixed using a regex-based solution that can handle multiple twitch links and
does not mess with the rest of the text.
-----
A second problem was that twitch, youtube & imgur links were being embedded even
when they were introduced by the expansion of tags such as [user=x]. This caused
problems if a user had a twitch link in their motto, for example.
Fixed by embedding the links before expanding forum-specific tags, thus acting
only on the links present in the actual forum post.

Fix embedding of twitch videos/collections/clips

---

lib/database/game.php

Changes will make it so Atari Jaguar, WonderSwan, WonderSwan Color, and Pokemon Mini cheevos can be added to the site.

Validates Jaguar, WonderSwan, and Pokemini on site

---

lib/dynrender.php

Adds Pokemon Mini to the dropdown (now that it has at least one set in core)

dynrender.php - dropdown update

---

public/gameInfo.php

Redo of #371 with "px" correctly added to the width and height values.

Maintain aspect ratio for screenshots

---

lib/database/utility.php

also 24-bit mem size.
related:
https://github.com/RetroAchievements/rcheevos/pull/21
https://github.com/RetroAchievements/rcheevos/pull/29

show Measured and AddAddress in "Mem Explained"

---

public/setRequestList.php

Fix set request page traversal when "-- All Systems --" is selected. Ended up removing the s flag when not filtering on a specific console.

Fix set request page traversal again.

---

public/achievementList.php

Capitalized the a and u in "My Unlocked Achievements"

Update achievementList.php - minor capitalization tweak

---

public/ticketmanager.php

Broke this with the ticket filtering implementation. This fixes the issue where previous closed/resolved tickets for any given achievement were not showing on the ticket page.

Fix "Closed tickets for this achievement"

---

database/20200209_222700_Revise_StaticData_NumGames.sql
lib/database/static.php
public/controlpanel.php
public/gameInfo.php

I noticed the tabs were wrong, so I switched them to spaces. I was having difficulty figuring out how to squash the two commits into one. For some reason, it wasn't working for me, but it says there is an option to Squash and Merge when merging the Pull Request.

Fixes #229, #261, #262

---

lib/database/achievement.php
lib/database/codenote.php
lib/database/game.php
lib/database/ticket.php
lib/database/user.php
public/css/styles.css
public/gameList.php
public/individualdevstats.php
public/userInfo.php

The new page can be accessed from the developers user page.
Here is what the new page will generally look like. Information on each stat is defined below.
**Note: Stats are based on official achievements only.**
Chart 1 - The leftmost chart shows the number of games the developer has developer on per console.
Chart 2 - The rightmost chart shows the number of achievements the developer has created per console.
Game stats are broken into three sections: Any Development, Majority Developer, and Sole Developer
- Any Development - Developer has created any number of the achievements.
- Majority Developer - Developer has created at least half of the achievements.
- Sole Developer - Developer has created all of the achievements.
| Game Stats | Description |
| --- | --- |
| Games Developed For | …

New Developer Stats Page

---

lib/util/trigger.php

AddAddress doesn't have details

---

public/login_app.php

Add Permissions and AccountType in login_app response

---

lib/database/user.php

Replace user value from request by user value from database

---

public/.htaccess
public/gameInfo.php

Add flag param in url when it is provided (Unofficial games)

---

lib/database/search.php

Fix link for Ticket as search result

---

lib/database/user.php

Exclude unofficial achievements from point counts

---

lib/database/ticket.php

Fixed a few places where tickets for unofficial achievements were being counted when they should not have been. Ticket Manager, User Profile page, and some stats on the Individual Developer Stats page.

Updates to Ignore Unofficial Tickets

---

lib/database/game.php
public/dorequest.php

and improve game title management
Fix #289

Use GameID from submitgametitle request if available

---

lib/database/achievement.php
public/achievementInfo.php
public/gameInfo.php
public/js/all.js
public/request/user/list-unlocks.php
public/request/user/reset-achievements.php

Offers a way to reset progress for a specific achievement on the achievement's page:
Also a way to reset all achievements for a game on the game's page:
Closes #453

reset progress button on game/achievement page

---

lib/database/release.php

Update release.php - 3DO Interactive Multiplayer

---

lib/database/release.php
src/Emulators.php

See: #496, https://github.com/RetroAchievements/RAInterface/pull/7

Update Console & Emulator IDs to match RAInterface

---

public/request/user/update.php
public/userInfo.php

Lowering required permissions for Patreon badge toggle.
Apply some code calisthenics to `request/user/update.php` while at it.

Admins may toggle Patreon supporter badge

---

lib/render/leaderboard.php
public/globalRanking.php

Two minor issues fixed with this:
- User completed/mastery counts fixed to show correctly rather then showing the counts for the first user on the next page.
- Updated logged users in daily points to link to the history page like all the other users in the table do.

Minor Global Rankings fixes.

---

lib/database/release.php

Accept console ID 23 (Magnavox Odyssey __**TWO**__) as a valid console.
https://github.com/RetroAchievements/rcheevos/pull/90

add console ID 23 (Magnavox Odyssey 2) as valid

---

README.md
public/API/API_GetUserCompletedGames.php
public/APIDemo.php
src/RetroAchievementsWebApiClient.php

A new public facing API to return the results of `getUsersCompletedGamesAndMax()`. This can allow external apps to see the number of games a user has played, the number of games the user has completed and mastered, as well as details on completion percentage for each game.
- Updated the APIDemo page to include the new API call.
- Updated the README to include some details on using XAMPP and updating the included version of PHP to 7.4, as well as creating a dummy database.

GetUserCompletedGames API

---

cronjobs/cron_daily.php
database/20200502_000000_Add_Comment_Foreign_Keys.sql
database/20201114_140000_Add_UserAccount_Deleted.sql
lib/database/leaderboard.php
lib/database/user.php
lib/render/error.php
lib/render/user.php
public/achievementInfo.php
public/controlpanel.php
public/request/auth/delete-account-cancel.php
public/request/auth/delete-account.php

In regards to checking for the Deleted timestamp on users only the check in getAccountDetails has been added. 
Some additional checks in other queries might be appropriate down the line.
This PR is meant to deal with the minimum requirements for account deletion for now.

Allow users to request account deletion via settings page

---

database/20210320_020000_Add_GameHashLibrary_User.sql
lib/database/game.php
lib/database/rom.php
lib/render/user.php
public/latesthasheslinked.php
public/linkedhashes.php

Store user to linked hash

---

lib/bootstrap.php
lib/render/comment.php
public/css/styles.css

Similar to how the userscript by @Xymjak does it.

Mute Server entries' colors in achievements comments

---

lib/database/ticket.php
public/gameInfo.php
public/ticketmanager.php

Adds a core/unofficial filter to ticket manager. Updated link on unofficial game page accordingly.

Add Core/Unofficial Filter to Ticket Manager

---

public/wiki-edit-redirect.php

Allows to redirect docs and guide edit links.

Context aware wiki edit links

---

public/gameInfo.php

reset progress link based on cheevos unlocked (not points) - fixes #525

---

public/userInfo.php

A small cosmetic change to please competitive players.

Site Rank percentage with decimals

---

lib/render/layout.php

Added 'My Sets' and 'My Tickets' links to the 'My Pages' dropdown

---

lib/render/layout.php

Fix navigation markup

---

lib/constants.php
public/css/styles.css

Keep message at the top when scrolling down.
Scrolled:

Sticky messages

---

lib/database/forum.php
lib/render/forum.php

Fixes the ellipses display on forum activity for the home page.

fix: #626 forum activity post length display

---

lib/render/comment.php
public/js/all.js

This will increase the character count for comment fields across all types (achievement comments, user comments, news, activity, leaderboard, and achievement tickets).

fix: #529 increase input length for comments

---

public/achievementInfo.php
public/achievementinspector.php
public/js/all.js

This feature adds a confirmation dialog to promotion and demotion actions for achievements.

feat: #554 add confirmation for achievement promotion/demotion

---

.github/ISSUE_TEMPLATE/config.yml

Branch for open GitHub issue template improvements.

Improve GitHub issue template config

---

public/dorequest.php

clearer login error message

---

lib/database/release.php
lib/database/releases.dist.php
lib/render/layout.php

Validate PSP

---

lib/database/release.php

Assigning console IDs to PC-6000 series, Sega Pico, Mega Duck, and Zeebo..

Add new console IDs

---

lib/render/layout.php

This prevents a HTTP redirect.

Update Facebook link to add www

---

lib/database/game.php

Fixed sorting by 'Last Updated' field for games list

---

lib/render/game.php

add confirmation prompt when creating official forum topic

---

lib/database/leaderboard.php
lib/render/leaderboard.php

show leaderboards with no entries on game page

---

public/dorequest.php
public/leaderboardList.php

Fixes a display issue if the leaderboard fields are not in the expected order. Also updates the new API to put them in the expected order.

fix field order for uploadleaderboard api

---

lib/database/leaderboard.php

expose hidden flag for leaderboards in patch data

---

composer.json
lib/database/achievement.php
lib/database/activity.php
lib/render/leaderboard.php
public/rss.php
public/setRequestList.php
src/ActivityType.php

Fixed a typo on the /rss page.

Fixed typo

---

lib/database/leaderboard.php

Extension of #869. Changes "Hidden" field value from `"0"`/`"1"` to `false`/`true`

set data type to boolean for hidden leaderboard

---

.php-cs-fixer.php
lib/constants.php
public/test/shortcode.php
src/Shortcode/Shortcode.php

- Fix multiple url tags on same line not parsing correctly
- Force https URLs everywhere
- Chore: Sort CS Fixer rules

Prefix URLs with (missing) https protocol

---

lib/database/ticket.php
public/reportissue.php
public/request/ticket/create.php
public/ticketmanager.php
public/views/checksumDescriptionModal.html

change MD5 references to RetroAchievements Hash

---

lib/database/setrequest.php
public/setRequestList.php

Supports #820. The default filter for the Most Requested Sets page will now be "-- Supported Systems --".

add Supported Systems filter to Most Requested Sets page

---

lib/database/activity.php
lib/database/game.php
public/managehashes.php
public/request/game/modify.php
src/ArticleType.php

Adds a comment section to the Manage Hashes page that auto-logs links, unlinks, and updates to hashes. Allows developers to post comments as well.

Add Comments Section to Hash Management Page.

---

lib/database/release.php
lib/database/releases.dist.php
lib/render/layout.php

Also added console to nav bar.

Validate Amstrad CPC on site

---

lib/render/comment.php
public/js/all.js

fix comment appending for non-refreshing pages

---

database/20180212_170235_RA_Template.sql
lib/constants.php
lib/database/activity.php
lib/render/comment.php
public/createmessage.php
public/css/styles.css
public/js/all.js
public/managehashes.php
public/request/comment/create.php

- Reload after submit at all times.
- Textareas now take the full width
- The submit button is accessible via keyboard
Chores:
- Remove unused JS
- Class import

Simplify article comments

---

lib/render/layout.php
resources/docker/nginx/configs/snippets/ra-web-v1.conf

+ serve fresh assets locally at all times.

Adopt versioned assets filenames

---

public/createmessage.php

Allow parsed shortcode content whilst preventing script injection.

Fix inbox output sanitization

---

public/gameInfo.php

Matches `Game Name [Subset - `

separate subsets from similar games

---

lib/render/game.php
public/gameInfo.php

Specifically, `Subgenre` -> `Genre`, and `Hacker` -> `Developer`. Also adds special logic for mapping `Hacks` -> `Publisher` with the "Hack - " prefix.

allow merging aliased hubs

---

lib/util/mail.php
public/controlpanel.php
public/request/user/update-email.php

this forces the user to verify their new email address.
if the user has elevated privileges, they will be warned about losing them:

reset account to unverified when user changes their email address

---

.github/workflows/ci.yml
.gitignore
.hooks/post-merge
.hooks/pre-commit
.hooks/pre-push
package.json
public/gameList.php
public/recentMastery.php
public/ticketmanager.php

- Run eslint in GitHub action as part of CI
- Re-run Rector

Only run code quality tools on changed files

---

lib/render/achievement.php
public/historyexamine.php

Also removes the "(Hardcore!)" flair from the Description column in favor of adding a hardcore border to the badge image. The hardcore flair for additional points remains.

add date picker to user history page

---

public/request/user/update.php

Takes care of #680 by authorizing the users forum posts when giving Jr-Dev or higher permissions

Authorize forum posts when giving Jr-Dev or higher permissions

---

lib/render/layout.php
public/gameList.php
public/viewforum.php
public/viewtopic.php

Replaces the list of pages with a selector (both on the forum list and in an individual topic)
before:
after:

use paginator for forums

---

lib/render/content.php
public/gameInfo.php
public/gameList.php

Game details page:
Game list page:

Add PS2 console message to game info and game list pages

---

lib/database/achievement.php
lib/database/codenote.php
lib/database/leaderboard.php
lib/render/user.php
public/dorequest.php
src/AchievementType.php
src/ArticleType.php
src/AwardType.php

- Remove development tutorial game checks

Add achievement type constants

---

lib/database/achievement.php
lib/database/ticket.php
public/achievementInfo.php
public/achievementinspector.php
public/js/all.js
public/request/achievement/update.php

- Only allow to promote achievements for valid consoles
- Allow achievement updates only via post
- Use AchievementType constants

Refactor achievement inspector

---

public/ticketmanager.php

also lowers the number of tickets shown per page to 50 (from 100)

use paginator for ticket list

---

lib/database/game.php
lib/database/player-achievement.php
lib/database/player-game.php
public/achievementInfo.php
public/dorequest.php

Fix user parameters not being optional for guest requests

---

.env.example
README.md
docker-compose.yml
lib/database/user-auth.php
lib/render/layout.php
lib/render/user.php
lib/util/media.php
public/API/API_GetUserSummary.php
public/createmessage.php
public/gameInfo.php
public/leaderboardinfo.php
public/login_app.php
public/request/auth/login.php
public/request/auth/update-password.php
public/test/media.php
public/validateEmail.php
public/viewtopic.php
src/Shortcode.php

- user might not be logged in when checking for user preferences
- redirect when leaderboard or forum topic were not found
- handle empty user's last activity timestamp
- handle empty login redirect parameter
- allow empty user shortcode embeds

Fix various errors and warnings

---

lib/database/releases.dist.php
lib/render/content.php
lib/render/layout.php
public/download.php
public/index.php
src/Shortcode.php
tests/src/ShortcodeTest.php

Users may decide for themselves if they want to open links in a new tab.

Do not open links in new tabs by default

---

public/claimlist.php
public/manageclaims.php
public/request/game/generate-forum-topic.php

Fixes:
- Sorting by expiration date only working one way.
- Devs unable to create game forum topics.
- Typo on manage claims page.

Claims Hotfix

---

.gitignore
LocalValetDriver.php

Add LocalValetDriver

---

public/request/achievement/update-base.php

I changed one too many things there. The achievement author was showing as change author instead of the acting user.

Fix achievement change author

---

lib/database/user-relationship.php

remnant of the original attempt to make friends require mutual acknowledgment

don't require mutual following to display users in 'compare to others' list

---

lib/database/user-relationship.php
public/friends.php
public/userInfo.php

See #1073 
Adds a "XXX is following you" message to the profile page of users who are following you
Also adds a "Follow User" link to the "Followers" section of the "Following" page for users who you are not already following:
Additionally, the "Followers" and "Blocked" lists are now sorted by name. Previously, they were sorted by last activity (similar to the "Following" list). The "Following" list now also displays the last activity timestamp.

implement feedback for Follower feature

---

lib/render/leaderboard.php

Fix followed user points when user is appended to end of list to fix issue seen below

Follower-points-fix

---

lib/render/set-claim.php

Changes from claim date desc to completion date desc

Fix sorting when clicking more link on New Set/Revision widget

---

lib/render/content.php
lib/render/layout.php

Updates the rollout message on PS2 game entries and adds PS2 to the dropdown.

PS2 update

---

public/API/API_GetUserRankAndScore.php

https://discord.com/channels/310192285306454017/310195854642249728/1020624903537434695

fix points not being returned by API_GetUserRankAndScore

---

public/gameInfo.php

applies the fix from #1117 to the game page as well

fix resetting progress from game page

---

app/Console/Kernel.php
app/Site/Middleware/ForceHttps.php
app/Site/Middleware/RobotsMiddleware.php
cronjobs/cron_1m.php
cronjobs/cron_30m.php
cronjobs/cron_daily.php
cronjobs/cron_hourly.php

Tested via `php artisan schedule:run`.
Fixes players online counts.

Fix scheduled jobs and update environment checks

---

lib/util/trigger.php
public/achievementInfo.php

fixes "Uninitialized string offset 1" exception trying to view achievement 195341
also adds warning text to the achievement display:

prevent exception processing truncated trigger

---

lib/database/player-game.php
public/gamecompare.php

fixes "foreach() argument must be of type array|object, null given" on game compare page when logged in user has no game history

prevent exception visiting game compare page before playing any games

---

lib/util/trigger.php

fixes https://discord.com/channels/310192285306454017/310195377993416714/1023583894114664559

don't report empty group as invalid

---

lib/util/trigger.php

show decimal tooltip for hex values when viewing trigger

---

public/request/user/list-currently-active.php

Microcaching the currently active request doesn't work anymore for multiple reasons. Cache it in redis (production; whatever you choose to use locally) instead.

Cache currently active on front page

---

public/gameList.php

Also removes the console name from the tooltip but I think that's fine in this case?

Remove console name from games list

---

public/leaderboardList.php

update Time(Milliseconds) to Time(Centiseconds)

---

lib/database/player-rank.php

...should follow my own advice...

Prefix user rank cache key

---

public/manageclaims.php
resources/css/table.css

Condensed claims table

---

lib/database/ticket.php

allow user to create new ticket for achievement if previous ticket has been closed or resolved

---

lib/render/content.php
public/request/user/list-currently-active.php

Remove superfluous table headers.
Use Collection and Carbon.

Improve currently active

---

lib/database/achievement.php
public/dorequest.php

Fixes `Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0)` at `lib/database/achievement.php(478)` error

prevent exception trying to return data for non-existent game

---

lib/database/player-game.php

only show recent players from the last six months

---

app/Support/Rules/CtypeAlnum.php
lang/en_US/validation.php
lib/database/ticket.php
lib/database/user-relationship.php
lib/util/string.php
public/createaccount.php
public/request/auth/register.php

Fix register page not remembering old input on validation failure.

Consolidate username validation

---

public/reportissue.php

limit emulator selection to supported emulators for console when creating new tickets

---

lib/database/player-game.php

fix enforcement of minimum number of achievements for badge

---

public/ticketmanager.php

fixes `Trying to access array offset on value of type null at /srv/web/releases/2022-11-18T162835-2.2.0-3537be7/public/ticketmanager.php:41`

fix exception trying to view non-existent ticket

---

lib/database/ticket.php

clear resolution fields when reopening ticket

---

app/Api/Controllers/WebApiController.php
app/Api/Controllers/WebApiV1Controller.php
app/Api/RouteServiceProvider.php
app/Connect/RouteServiceProvider.php
config/app.php

Subdomain routing & major versioning

---

lib/util/trigger.php

https://discord.com/channels/310192285306454017/533411674162593812/1053735829887000618

fix display of value definition containing max_of operator ('$')

---

lib/database/leaderboard.php

https://discord.com/channels/310192285306454017/310195377993416714/1054756930104606761

fix leaderboard not displaying if only entries are for untracked users

---

app/Legacy/RouteServiceProvider.php
app/Platform/Controllers/LeaderboardController.php
public/leaderboardinfo.php

https://discord.com/channels/310192285306454017/310195377993416714/1054759865018495017

hookup leaderboard url alias

---

lib/database/forum.php

The limit returns an appropriate number of items for the current page, then those created by an unverified user are filtered out. If the unverified user creates enough posts, it can actually cause the page to appear blank.
https://discord.com/channels/310192285306454017/453242743292952578/1057440536828588102
Modified the query to exclude the unverified posts before applying the limit

exclude unverified posts from query

---

app/Legacy/Models/PlayerBadge.php
composer.json
composer.lock
lib/database/search.php
package-lock.json
package.json
phpstan.neon
public/ticketmanager.php
public/userInfo.php
rector.php

Return 404 to non-admin/mods when trying to access a banned/spam account's profile page.
Update composer & npm dependencies while at it and ran rector on some newer changes.

Hide banned/spam accounts' user pages

---

lib/render/site-award.php

fixes issue where Game Awards would appear above Site/Event awards if a Game Award was hidden

ignore hidden items when determining award category order

---

app_legacy/Helpers/render/game.php
public/test/cards.php

Validate using `/test/cards.php`

Fix cards rendering when tags have been replaced in game title

---

public/gameInfo.php

apply stylized tags to mature content warning page

---

public/achievementInfo.php
public/codenotes.php
public/gameInfo.php
public/gamecompare.php
public/leaderboardList.php
public/leaderboardinfo.php
public/linkedhashes.php
public/manageclaims.php
public/managehashes.php
public/reportissue.php
public/usergameactivity.php

apply stylized tag to breadcrumbs

---

public/API/API_GetUserCompletedGames.php

Alternate implementation for #1313

restore old response for API_GetUserCompletedGames

---

app_legacy/Platform/AppServiceProvider.php
app_legacy/Platform/Commands/UpdatePlayerPoints.php

As discussed, I left that in there by accident.

Remove incorrectly added UpdateDeveloperContributionYield from schedule

---

app_legacy/Helpers/database/game.php
public/API/API_GetGameExtended.php
public/API/API_GetGameInfoAndUserProgress.php
public/gameInfo.php
public/linkedhashes.php
public/managehashes.php
public/setRequestors.php

avoids a rather expensive secondary query on pages that don't need it

don't fetch player metrics unless needed

---

app_legacy/Community/AppServiceProvider.php
app_legacy/Community/Models/UserActivity.php
app_legacy/Helpers/database/game.php
app_legacy/Helpers/database/player-achievement.php
app_legacy/Helpers/database/player-game.php
app_legacy/Helpers/database/player-rank.php
app_legacy/Helpers/database/user-activity.php
app_legacy/Helpers/database/user.php
database/factories/Legacy/AchievementFactory.php
database/factories/Legacy/UserFactory.php
public/API/API_GetUserPoints.php
public/API/API_GetUserProgress.php
public/API/API_GetUserRecentlyPlayedGames.php
public/API/API_GetUserSummary.php
public/history.php
public/historyexamine.php
public/userInfo.php
tests/Feature/Api/V1/UserPointsTest.php
tests/Feature/Api/V1/UserProgressTest.php
tests/Feature/Api/V1/UserRankAndScoreTest.php
tests/Feature/Api/V1/UserRecentlyPlayedGamesTest.php
tests/Feature/Api/V1/UserSummaryTest.php

API_GetUserPoints
API_GetUserProgress
API_GetUserRank
API_GetUserRecentlyPlayedGames
API_GetUserSummary
I originally started with the last one and the others were mostly covered by it in one way or another.

add tests for UserSummary and related APIs

---

app_legacy/Helpers/database/user-activity.php

https://discord.com/channels/476211979464343552/1026595325038833725/1079438893285380096

include achievement description in activity tooltip

---

public/gameInfo.php

Fixes #1417 and some escaping issues

Fix game metadata update action

---

public/comments.php

https://discord.com/channels/476211979464343552/1026595325038833725/1095107353789075456

fix(comments): enhance page security

---

app_legacy/Platform/Enums/Emulators.php
storage/app/releases.dist.php

add bizhawk and duckstation to downloads page

---

app_legacy/Helpers/database/player-history.php
public/API/API_GetAchievementsEarnedOnDay.php
public/API/API_GetUserRecentAchievements.php
tests/Feature/Api/V1/UserRecentAchievementsTest.php

as a low-overhead alternative to API_GetUserSummary for detecting if a user has recently unlocked any achievements

add API_GetUserRecentAchievements

---

app_legacy/Helpers/database/achievement-creator.php
public/request/game/update-rich-presence.php

This PR addresses a recent Jr Devs permissions issue that was reported here: https://discord.com/channels/476211979464343552/1026595325038833725/1098714596333854720.

fix: remediate regression in checkIfSoleDeveloper()

---

app_legacy/Helpers/database/forum.php
app_legacy/Helpers/database/user-activity.php
app_legacy/Helpers/render/comment.php
app_legacy/Helpers/util/mail.php
public/js/all.js

https://discord.com/channels/310192285306454017/1084948245953908776/1084948245953908776
Works for Game, Achievement, User Wall, and Ticket comment notifications.

add links to new comments in notifications

---

app_legacy/Helpers/database/game.php

Reverts RetroAchievements/RAWeb#1550

Revert "feat(gameList): Show the count of leaderboards owned by the dev even for games the dev hasn't done cheevos for"

---

app_legacy/Helpers/database/forum.php
app_legacy/Helpers/database/user-activity.php

Resolves https://discord.com/channels/476211979464343552/1026595325038833725/1106291571223187526.

fix: remediate issue with first time posters

---

public/request/user/recalculate-score.php

https://discord.com/channels/476211979464343552/1026595325038833725/1106420549309186048

fix forced score recalculation targeting logged in user

---

app/Site/Models/User.php

Fixes exception:
```
Undefined array key "websitePrefs" {"userId":8710,"exception":"[object] (ErrorException(code: 0): Undefined array
key \"websitePrefs\" at /srv/web-preview/releases/2023-06-18T184319-2.15.0-1461b9ac/public/gameInfo.php:86)
```

fix mature content warning

---

public/js/all.js

Resolves https://discord.com/channels/310192285306454017/1126899478167830538.

fix(search): remediate keyboard navigation issues

---

app/Helpers/database/forum.php
resources/views/community/components/forum/post-author-box.blade.php
resources/views/community/components/forum/post.blade.php

https://discord.com/channels/476211979464343552/1026595325038833725/1126985746293735524

fix(forum): visual tweaks

---

app/Exceptions/Handler.php
app/Helpers/database/message.php
app/Helpers/database/user-auth.php
public/dorequest.php
public/login_app.php
tests/Feature/Connect/LoginTest.php
tests/Feature/Connect/PingTest.php

also adds `Code` and `Status` to error responses and Status is reflected in HTTP Response Code per discussion https://discord.com/channels/476211979464343552/757767535293890682/1132370669938671758

return HTTP 401 and code field on dorequest authentication failures

---

public/maintenance.html

Better informs the users of what is going on when the website is down.

feat: Pretty 503 response

---

app/Helpers/database/leaderboard.php

There are several leaderboard queries, including one that executes on game pages, that are non-sargable and not able to use indexes properly.
**Benchmarks**
These samples were collected on game ID 1446 with the local MySQL cache disabled.
|         | Before | After |
|---------|--------|-------|
| 1       | 499ms  | 383ms |
| 2       | 335ms  | 280ms |
| 3       | 444ms  | 260ms |
| 4       | 334ms  | 323ms |
| 5       | 339ms  | 270ms |
| 6       | 488ms  | 265ms |
| 7       | 310ms  | 334ms |
| 8       | 303ms  | 262ms |
| 9       | 292ms  | 260ms |
| Average | 371ms  | 293ms |
Speedup Factor: ~1.26x

perf: remediate non-sargable leaderboard queries

---

public/dorequest.php

Resolves https://discord.com/channels/476211979464343552/1026595325038833725/1139686683026145361.
`t` is being used for the token, which is what's throwing the error.

fix: remediate achievement upload issue

---

app/Community/Components/UserCard.php

Resolves https://github.com/RetroAchievements/RAWeb/issues/1791.

fix(UserCard): remediate softcore rank label typo

---

app/Community/Models/ForumTopic.php
app/Platform/Models/Achievement.php
app/Site/Models/User.php
database/seeders/DatabaseSeeder.php
database/seeders/ForumTopicSeeder.php
database/seeders/StaticTableSeeder.php

`StaticData`'s `last_game_hardcore_mastered_user_id` and `last_game_hardcore_beaten_user_id` are not nullable.

fix(seeders): improve database seeders

---

public/forumposthistory.php

Increases truncation from 90 characters to 120.

show more preview text in wider forum history page

---

app/Site/FortifyServiceProvider.php
database/seeders/UsersTableSeeder.php

Keep upgrading passwords during login.

fix(auth): apply minimum permissions to login

---

public/gameList.php

https://discord.com/channels/310192285306454017/1149601206726045758/1149601206726045758
Also forces pagination when attempting to filter by console

remember sort when changing pages on Want to Play

---

app/Site/FortifyServiceProvider.php

Fixes `Attempt to read property \"SaltedPass\" on null` errror

fix null reference error attempting to log in unknown user

---

app/Helpers/database/player-achievement.php

fixes a query error trying to view unofficial achievements with the AGGREGATE_QUERIES feature (#1814) enabled.

fix error viewing unofficial achievements

---

app/Helpers/database/ticket.php
app/Site/Components/NotificationIcon.php
resources/views/components/notification/icon.blade.php

Do not show the red dot for "ticket pending feedback" notifications.

feat(notifications): mark pending ticket feedback notifications as read

---

public/userInfo.php

Not sure what happened here, maybe an accident while resolving a merge conflict.

perf(user): remove duplicate site awards fetch

---

public/gameInfo.php

Resolves https://discord.com/channels/310192285306454017/1154893380904566876.

fix(gameInfo): render title tags for mature games

---

database/migrations/2012_10_03_133633_create_base_tables.php
database/migrations/upcoming/2023_05_01_000002_add_foreign_keys.php

In preparation for better seeders and to make sure the migrations are in a clean state moving forward in general.
I ran into at least two issues that i thought were bugs when it was the migrations being out of sync.

chore: migrations cleanup to match production schema more closely

---

app/Helpers/database/user-relationship.php

For my four followed users, cuts the time to build this data from 80ms to <1ms.

allow aggregate query for followed users on game page

---

app/Helpers/database/game.php
app/Helpers/database/player-game.php
app/Helpers/database/user.php
public/API/API_GetGameInfoAndUserProgress.php
public/API/API_GetUserProgress.php
public/API/API_GetUserRecentlyPlayedGames.php
public/API/API_GetUserSummary.php
public/achievementinspector.php
public/gameInfo.php
public/gamecompare.php
tests/Feature/Api/V1/UserProgressTest.php
tests/Feature/Api/V1/UserRecentlyPlayedGamesTest.php
tests/Feature/Api/V1/UserSummaryTest.php
tests/Feature/Connect/BootstrapsConnect.php

also passes around the User model instead of fetching it multiple times.

use aggregate data for user progress

---

app/Helpers/database/player-achievement.php
app/Platform/Actions/ResetPlayerProgress.php
app/Platform/Actions/UpdateDeveloperContributionYield.php
app/Platform/Commands/UpdateDeveloperContributionYield.php
app/Platform/EventServiceProvider.php
app/Platform/Models/PlayerBadge.php
tests/Feature/Connect/AwardAchievementTest.php
tests/Feature/Connect/UploadAchievementTest.php
tests/Feature/Platform/Action/UpdateDeveloperContributionYieldTest.php
tests/Feature/Platform/Concerns/TestsPlayerAchievements.php

re-enables the contribution calculation logic

use aggregate data to calculate contribution points

---

app/Community/Enums/AwardType.php
app/Helpers/database/site-award.php
app/Helpers/database/user.php
app/Helpers/render/site-award.php

Fixes tiered awards reading duplicates for SiteAwards.

feat: add site award progress type helper

---

app/Helpers/database/player-history.php

fixes vertical lines showing up in recent progress graph

group recent progress by date not datetime

---

app/Helpers/database/player-game.php

fixes https://discord.com/channels/310192285306454017/1170371063511785514

use subquery to determine most recent per-player session

---

public/individualdevstats.php

SoftcoreCount no longer implicitly counts Hardcore unlocks too.
https://discord.com/channels/310192285306454017/1170490915425628301/1170860155517284444

fix display of own achievements earned

---

app/Community/Components/UserRecentlyPlayed.php

only update date when updating kind

fix mastery time calculation when player has mastery and beaten timestamps

---

app/Platform/Controllers/DeveloperSetsController.php

for example: http://localhost:64000/user/s0uth/developer/sets

fix exception if game has leaderboards but no achievements

---

app/Community/Components/UserRecentlyPlayed.php

Adds point totals to recently played on user profiles.

fix(user): show points in recently played

---

app/Helpers/shortcode.php
public/userInfo.php

Abort if non numeric or greater than 100.
https://discord.com/channels/476211979464343552/1026595325038833725/1174924736795512853

fix(user): add validation to the 'g' query param

---

resources/views/components/menu/main.blade.php

Moves Neo Geo CD and Neo Geo Pocket to a new SNK category in the nav bar.

Add SNK category to nav bar console list

---

app/Helpers/database/ticket.php

Makes the URL in a ticket email be clickable.

linkify ticket URL in email

---

app/Api/RouteServiceProvider.php
app/Connect/RouteServiceProvider.php
app/Site/RouteServiceProvider.php

This is done on the webserver and cloudflare level.

chore: remove in-application rate limiting comments

---

app/Filament/Resources/AchievementResource.php
app/Filament/Resources/SystemResource.php
app/Filament/Resources/UserResource.php
app/Platform/Models/System.php
app/Site/Models/User.php

Add IDs to detail views for all resources while at it.

feat(filament): reduce emphasis on user IDs

---

app/Helpers/render/game.php
public/gameList.php
resources/views/platform/components/game/breadcrumbs.blade.php

`/gameList.php?s=6&c=100&f=1` should not redirect to `/system/100/games`, yet.

fix(games): do not redirect hubs to new games index

---

app/Filament/Resources/AchievementResource.php
app/Filament/Resources/SystemResource.php
app/Platform/Models/Achievement.php
app/Platform/Models/System.php

affects achievements & systems.
see https://github.com/RetroAchievements/RAWeb/pull/2190#issuecomment-1920169431

feat(filament): remove IDs from record title attributes

---

composer.json

see https://getcomposer.org/doc/articles/scripts.md#executing-php-scripts

chore(composer-scripts): use correct php version

---

resources/views/pages-legacy/linkedhashes.blade.php

Resolves https://discord.com/channels/476211979464343552/1026595325038833725/1206241812046544997.

fix(game): removed hash 'linked by' label on supported game files page

---

resources/views/pages/contact.blade.php

https://discord.com/channels/476211979464343552/1026595325038833725/1206688090387906560

chore(contact): remove RAdmin messaging criteria

---

app/Community/Components/UserProfileMeta.php

http://localhost:64000/user/bryce87

prevent divide by zero calculating retro ratio

---

app/Helpers/util/trigger.php

https://discord.com/channels/310192285306454017/310195377993416714/1221620620115181598

support for Float BE in achievement definition display

---

resources/views/pages-legacy/editpost.blade.php

Resolves numerous character encoding issues on the editpost page. Also migrates the page from using helper functions to using Eloquent ORM.
**Before**
**After**

fix(editpost): remediate character encoding issues

---

app/Helpers/database/game.php

The current conditional never evaluates truthy.

fix(getParentGameFromGameTitle): check game title string correctly

---

resources/views/components/game/link-buttons/index.blade.php

Resolves https://github.com/RetroAchievements/RAWeb/issues/2349.

fix(game): remediate missing 'Create Forum Topic' button

---

resources/views/pages-legacy/searchresults.blade.php

https://discord.com/channels/310192285306454017/1229079496376975401/1229079496376975401

also show related game for achievement search results

---

app/Platform/Services/TriggerDecoderService.php
resources/views/components/trigger/viewer.blade.php
tests/Feature/Platform/Services/TriggerDecoderServiceTest.php

https://discord.com/channels/310192285306454017/1233087006167531660/1233087006167531660

fix missing notes for addresses padded to 8 digits

---

app/Helpers/render/user.php
app/Models/Ticket.php
resources/views/components/comment/item.blade.php
resources/views/pages/ticket/[ticket].blade.php

For soft-deleted user (http://localhost:64000/ticket/12345) and null foreign key (http://localhost:64000/ticket/12531)

(tickets) don't show recent history region for deleted user

---

app/Support/Redirector/LegacyRedirector.php

Fixes " Undefined array key 0 " error trying to access ticketmanager.php with no parameters.

fix error redirecting ticketmanager with no parameters

---

app/Models/Leaderboard.php
resources/views/components/game/leaderboards-listing/leaderboards-list-item.blade.php

http://localhost:64000/leaderboardinfo.php?i=3547
**Before**
**After**

fix(leaderboard-listing): exclude untracked users

---

config/missing-page-redirector.php
docs/CODE_OF_CONDUCT.md
resources/views/components/content/getting-started.blade.php
resources/views/components/content/top-links.blade.php
resources/views/components/game/devbox-claim-management.blade.php
resources/views/components/menu/footer.blade.php
resources/views/components/menu/main.blade.php
resources/views/pages-legacy/gameInfo.blade.php
resources/views/pages/achievement/[achievement]/report-issue.blade.php
resources/views/pages/achievement/[achievement]/tickets/create.blade.php
resources/views/pages/contact.blade.php
resources/views/pages/game/[game]/hashes/index.blade.php
resources/views/pages/terms.blade.php
tests/Unit/ShortcodeTest.php

Changes all docs paths so they'll work without relying on the nginx server-side redirects.

fix: update all docs urls to use their new paths

---

resources/views/pages/messages/create.blade.php

https://discord.com/channels/476211979464343552/1026595325038833725/1251180806005850206

fix: add hidden fields to templated messages

---

resources/views/pages/user/[user]/developer/sets.blade.php
resources/views/pages/user/[user]/tickets/index.blade.php

https://discord.com/channels/476211979464343552/1152683553348407409/1251169462132932698

allow viewing sets for deleted developer account

---

app/Helpers/database/forum.php

Resolves: https://discord.com/channels/476211979464343552/1026595325038833725/1251247318917841046
This sanitization is no longer necessary now that the entire UI is handled by Blade and Livewire. There are no other legacy callers.

fix(forum): remove unnecessary sanitization from forum editing

---

app/Helpers/database/user-permission.php

https://discord.com/channels/476211979464343552/1002689485005406249/1253590594685767742
Updated 400+ comments in prod to point to the correct user (as best as possible). Had to manually apply to chunks of IDs because the single query using a join was impacting the website stability.
```
MariaDB [retroachievements]> select c.ID from Comment c left join UserAccounts u on c.ArticleID=u.ID where c.ArticleType=9 and c.Submitted > '2024-05-08' and c.Payload like '%forum posts' and u.forum_verified_at < '2024-05-08';
...
441 rows in set (0.653 sec)
MariaDB [retroachievements]> UPDATE Comment c JOIN UserAccounts u SET c.ArticleID=u.ID WHERE c.Submitted >= u.forum_verified_at AND c.Submitted <= (u.forum_verified_at + INTERVAL 60 SECOND) AND c.ID in …
```

associate forum post authorization comment to correct user

---

resources/views/pages/contact.blade.php

Resolves https://discord.com/channels/476211979464343552/1026595325038833725/1253814120885518456.

fix(contact): remove grammatical mistakes line from qateam

---

app/Community/Components/UserProfileMeta.php

Resolves https://discord.com/channels/310192285306454017/453242743292952578/1260907165024125010

fix(user): update query for user total games beaten

---

app/Platform/Services/FollowedUserLeaderboardService.php

https://discord.com/channels/310192285306454017/453242743292952578/1260912847416987669

fix(FollowedUserLeaderboardService): increase limit

---

app/Connect/Concerns/DevelopmentRequests.php
app/Helpers/database/forum.php
app/Helpers/database/game.php
app/Helpers/database/hash.php
app/Helpers/database/player-achievement.php
app/Helpers/database/set-claim.php
app/Http/Requests/ProfileSettingsRequest.php
app/Platform/Services/CompareUnlocksPageService.php
app/Support/Sync/SyncTrait.php
database/migrations/upcoming/2018_10_01_000001_create_badges_table.php
public/API/API_GetAchievementOfTheWeek.php
public/API/API_GetAchievementUnlocks.php
public/API/API_GetActiveClaims.php
public/API/API_GetClaims.php
public/API/API_GetUserClaims.php
public/API/API_GetUserSummary.php
resources/views/pages-legacy/globalRanking.blade.php
resources/views/pages-legacy/individualdevstats.blade.php
resources/views/pages/achievement/[achievement]/tickets/create.blade.php
tests/Feature/Connect/AchievementWonDataTest.php
tests/Feature/Connect/LoginTest.php
tests/Feature/Connect/StartSessionTest.php
tests/Feature/Connect/UploadAchievementTest.php
tests/Feature/Platform/Action/ResetPlayerProgressTest.php

Fixes Typos/Grammar/etc. found in the code

Typographical Fixes

---

app/Community/Listeners/NotifyMessageThreadParticipants.php
config/services.php

Gets #incorrect-types and #issue-reports working in order to help QATeam.

feat(message): set up more team account forum webhooks

---

app/Community/Listeners/NotifyMessageThreadParticipants.php
config/services.php
resources/views/pages/achievement/[achievement]/report-issue.blade.php

Already set up the env vars on stage & prod. I'm going to deploy this to stage to be sure it works.

feat: set up automated writing team inbox / webhook

---

public/API/API_GetGame.php
tests/Feature/Api/V1/GameTest.php

Will update other endpoint(s) in a separate PR.

feat(api): use released_at and released_at_granularity on API_GetGame

---

database/migrations/community/2024_09_08_000000_update_emulators_table.php
database/seeders/EmulatorsTableSeeder.php
database/seeders/ReleaseTablesSeeder.php
storage/app/releases.dist.php

[emulators.sql.txt](https://github.com/user-attachments/files/16924176/emulators.sql.txt)

extract migration steps from #2684

---

app/Helpers/database/forum.php
app/Helpers/util/mail.php

Forum post email:
Game wall comment email:

include post content in forum post/comment email notifications

---

resources/js/features/game-list/components/WantToPlayGamesDataTable/DataTableSearchInput/DataTableSearchInput.tsx

On page refresh, the debounce is erroneously kicking off a search on mount, which results in the page index automatically being reset back to 0 even if a page number query param is specified in the URL.

fix(DataTableSearchInput): don't override pagination on refresh

---

resources/views/pages/achievement/[achievement]/tickets/create.blade.php

https://discord.com/channels/310192285306454017/1290659568564830218/1290659568564830218

fix(ticket): use ->name

---

resources/js/pages/game/[game]/hashes.tsx

Cherry-picked from https://github.com/RetroAchievements/RAWeb/pull/2762.

fix(game): use correct title tag on hashes page

---

app/Community/Actions/CreateGameClaimAction.php
tests/Feature/Community/Controllers/AchievementSetClaimControllerTest.php

https://discord.com/channels/310192285306454017/1301788137932066856/1301788137932066856

extend claim from expiration, not current date

---

resources/js/features/settings/components/+root/SettingsRoot.tsx

Due to performance issues that will be resolved in https://github.com/RetroAchievements/RAWeb/pull/2807. Will be reverted shortly after the release.

chore(settings): temporarily hide LocaleSectionCard

---

database/migrations/community/2024_11_15_000000_create_emulator_user_agents_table.php

of #2862
SQL to run is in #2862.

extract migration step so data can be populated before deployment

---

lang/ru_RU.json

Translated new keys and touched up 2 keys (changed the wording slightly and fixed capitalization)

chore: New key translations and minor fixes for ru_RU

---

app/Helpers/database/user-activity.php
app/Helpers/util/mail.php

https://retroachievements.org/log-viewer?file=97e6e724-laravel-2024-12-05.log&query=log-index%3A237

fix(comment): remediate server error with email address field

---

docs/TRANSLATIONS.md

Now that user-submitted PRs are no longer necessary to update RAWeb's translations, this doc needs to be updated to reflect how a user can join the Crowdin project and contribute.

docs: update TRANSLATIONS.md to reflect new process on Crowdin

---

public/dorequest.php

Resolves https://retroachievements.org/log-viewer?file=585c4893-laravel-2024-12-26.log&query=log-index%3A282.

fix(connect): set a fallback user agent on patch

---

public/API/API_GetAchievementOfTheWeek.php
tests/Feature/Api/V1/AchievementOfTheWeekTest.php

https://discord.com/channels/310192285306454017/1017568867574362283/1326149165264142336

ensure newest winners are first in AotW API response

---

app/Helpers/database/user-activity.php

Resolves:
> Call to a member function format() on null

fix(getRecentlyPlayedGames): remediate server error on format()

---

resources/views/components/game/claim-info.blade.php

Resolves an issue where moderators can no longer open https://retroachievements.org/game/228.
**Root Cause:**
```php
$achievementSetClaims->load(['user', 'game', 'game.playerSessions', 'game.achievements', 'game.memoryNotes']);
```
This is loading all of the game's player sessions, achievements, and memory notes in a single query. We only need to load data in targeted queries for each claimant.

fix(game): reduce claim info moderator memory usage

---

app/Helpers/render/game.php
resources/views/pages-legacy/gameInfo.blade.php

https://discord.com/channels/310192285306454017/310195377993416714/1326998657811353611

add sort links to event page

---

app/Filament/Resources/EmulatorResource.php
app/Filament/Resources/EventAchievementResource.php
app/Filament/Resources/EventResource.php

Resolves various query errors that occur while using global search which are associated with the new event resources.

fix(manage): remediate events global search query error

---

app/Policies/GamePolicy.php

Resolves:
> does not have permission to edit ImageIcon.
https://retroachievements.org/log-viewer?file=880da11b-laravel-2025-01-11.log&query=log-index%3A43

fix(GamePolicy): add game media to updateFields

---

app/Platform/Services/UserAgentService.php
tests/Feature/Platform/Services/UserAgentServiceTest.php

Fixes `Uninitialized string offset -1 at /home/forge/retroachievements.org/releases/2025-01-10T122158-6.25.1-1591de2b/app/Platform/Services/UserAgentService.php:71)`

fix exception processing User-Agent with multiple spaces in OS

---

app/Helpers/database/site-award.php

https://discord.com/channels/310192285306454017/1190827552491716608/1332016438654799984

count event badges towards set requests

---

app/Filament/Resources/EventResource/Pages/Create.php
app/Filament/Resources/EventResource/Pages/Edit.php

https://discord.com/channels/310192285306454017/1017568867574362283/1332018350477545617

keep game icon in sync with event icon

---

app/Filament/Actions/ProcessUploadedImageAction.php
app/Filament/Enums/ImageUploadType.php
app/Filament/Resources/AchievementResource.php
app/Filament/Resources/AchievementResource/Pages/Edit.php
app/Filament/Resources/EventAchievementResource.php

stacked on #3106 
https://discord.com/channels/310192285306454017/1017568867574362283/1331990960581902396

Allow direct editing of non-sourced event achievement

---

app/Community/Listeners/WriteUserActivity.php
tests/Feature/Platform/Action/CreateAchievementOfTheWeekTest.php

https://discord.com/channels/476211979464343552/1026595325038833725/1332064672584831069

don't update LastLogin when awarding event achievements

---

app/Platform/Services/GameSuggestions/Strategies/RevisedGameStrategy.php
app/Platform/Services/GameSuggestions/Strategies/SharedAuthorStrategy.php
app/Platform/Services/GameSuggestions/Strategies/WantToPlayStrategy.php

Resolves https://discord.com/channels/310192285306454017/1332117347816837261.

fix(SharedAuthorStrategy): filter out event games

---

app/Platform/Actions/RevalidateAchievementSetBadgeEligibilityAction.php
tests/Feature/Platform/Action/ResetPlayerProgressActionTest.php

https://discord.com/channels/310192285306454017/1332124778114584738/1332127019554570352

fix awarding/revoking legacy event badges

---

pnpm-lock.yaml

chore(deps): bump cross-spawn to 7.0.5

---

resources/js/common/components/SystemChip/SystemChip.tsx

fix(SystemChip): prevent word wrap

---

resources/views/pages/ticket/[ticket].blade.php

Resolves https://discord.com/channels/476211979464343552/1026595325038833725/1338290714471170120.

fix(ticket): handle custom display names properly

---

resources/views/pages-legacy/setRequestList.blade.php

Resolves https://discord.com/channels/310192285306454017/1339192283639054337.

fix(setRequestList): override `$username`  with ->display_name

---

app/Policies/GameSetPolicy.php

https://discord.com/channels/476211979464343552/1026595325038833725/1339715815376945274

chore: temporarily disable creation of new hubs

---

app/Community/Concerns/ActsAsCommunityMember.php
app/Helpers/database/user-relationship.php
app/Policies/AchievementCommentPolicy.php
app/Policies/CommentPolicy.php
app/Policies/GameCommentPolicy.php
app/Policies/UserCommentPolicy.php
resources/views/components/user/profile/social-interactivity.blade.php

https://discord.com/channels/476211979464343552/1002689485005406249/1340694992783544372

feat(comments): add anti-harassment measures

---

app/Filament/Resources/GameResource/Pages/Hubs.php

Resolves https://github.com/RetroAchievements/RAWeb/issues/3225.

fix(manage): remediate server error on hub id sort

---

resources/views/pages-legacy/gameInfo.blade.php

Resolves https://discord.com/channels/310192285306454017/888607146290343976/1340640724412141660.

fix(game): sort similar games and hubs alphabetically

---

resources/views/pages-legacy/achievementInfo.blade.php

Resolves https://discord.com/channels/310192285306454017/533411674162593812/1341904825369231403.

fix(achievementInfo): remediate $isAuthor comparison comparison for custom displaynames

---

app/Policies/MessagePolicy.php

https://discord.com/channels/476211979464343552/1002689485005406249/1339681765622681793

chore(MessagePolicy): remove JrDevs from the pierce preference list

---

app/Community/Components/UserProfileMeta.php

Resolves https://github.com/RetroAchievements/RAWeb/issues/3243.

fix(user): don't leak stable username on requested sets href

---

resources/views/pages-legacy/historyexamine.blade.php

`$userPage` is `$user->display_name`, which can cause this img src to point to the wrong path.

fix(history): point to correct user avatar file

---

app/Community/Data/MessageData.php
app/Models/Message.php

https://retroachievements.org/log-viewer?file=62fa1cce-laravel-2025-02-27.log&query=log-index%3A297

fix(messages): don't server error when reading deleted user DMs

---

resources/js/features/events/components/AchievementSet/EventAchievementSection/useEventAchievementSectionAnimation.test.ts
resources/js/features/events/components/AchievementSet/EventAchievementSection/useEventAchievementSectionAnimation.ts

Follows up on the comment here https://github.com/RetroAchievements/RAWeb/pull/3235#discussion_r1971588240:
> I'll probably take some time in a future PR to tune this animation further. I'm still not 100% pleased with it, but it's at least passable in its current state.
This PR mostly focuses on mitigating a "pop" effect which occurs in the open animation. It's probably impossible to resolve 100%, but it can be greatly concealed. The close animation has also been slightly adjusted, but not to remediate any issues.
The open "pop" occurs right at the end of the animation, where on `master`, the final bit of content seemingly teleports onto the page. There's a single frame of animation where the easing curve abruptly ends and ~10px of content instantly appears. It's most noticeable if you …

fix(EventAchievementSection): remediate 'pop' effect in collapse animation

---

app/Platform/Services/GameTopAchieversService.php

Resolves https://discord.com/channels/310192285306454017/1312920636577808384/1350432294216663050.

fix(GameTopAchieversService): point the expire fn to the new cache key

---

app/Helpers/database/player-game.php

https://discord.com/channels/310192285306454017/453242743292952578/1354951345219571965

fix(getUserProgress): return all game achievements

---

app/Helpers/database/player-history.php

Resolves https://discord.com/channels/310192285306454017/1357683032256942200.

fix(history): exclude event achievement points

---

resources/css/theme.css

Resolves:
https://discord.com/channels/310192285306454017/1362480754160042294
https://discord.com/channels/310192285306454017/1362479633874030762

fix: remediate System dark text color issues

---

resources/js/common/utils/shortcodes/postProcessShortcodesInBody.test.ts
resources/js/common/utils/shortcodes/postProcessShortcodesInBody.ts

Resolves https://discord.com/channels/310192285306454017/1364927640695214173.

fix(postProcessShortcodesInBody): remediate issues with wrapped url tags

---

app/Community/Actions/FetchDynamicShortcodeContentAction.php

Resolves https://discord.com/channels/310192285306454017/1365255564405510235.

fix(forums): show deleted usernames with a strikethrough

---

app/Community/Actions/BuildShowForumTopicPagePropsAction.php
app/Community/Controllers/ForumTopicController.php
resources/js/common/hooks/useHydrateShortcodeDynamicEntities.test.ts
resources/js/common/hooks/useHydrateShortcodeDynamicEntities.ts
resources/js/ssr.tsx

Resolves https://discord.com/channels/310192285306454017/1017568867574362283/1365169564484112394.

fix(forums): show event shortcode values correctly

---

resources/js/features/forums/components/ForumPostCard/ForumPostCardMeta/ForumPostCardTimestamps.test.tsx
resources/js/features/forums/components/ForumPostCard/ForumPostCardMeta/ForumPostCardTimestamps.tsx

Resolves https://discord.com/channels/310192285306454017/1365159812886696017.

fix(forums): show correct post edited dates

---

app/Http/Controllers/DownloadsController.php

https://discord.com/channels/310192285306454017/1367826087429673104

fix(DownloadsController): prioritize Android over Linux

---

app/Community/Actions/UpdateUnreadMessageCountAction.php
app/Community/Controllers/UserSettingsController.php
app/Connect/Concerns/AuthRequests.php
app/Filament/Resources/UserResource/Pages/Roles.php
app/Helpers/database/user-auth.php
app/Helpers/database/user-email-verify.php
app/Helpers/database/user-permission.php
app/Listeners/UpdateUserTimezone.php
app/Platform/Actions/RequestAccountDeletionAction.php
app/Platform/Actions/ResetPlayerProgressAction.php
app/Platform/Actions/ResumePlayerSessionAction.php
app/Platform/Actions/UpdateDeveloperContributionYieldAction.php
app/Platform/Actions/UpdatePlayerMetricsAction.php
public/request/user/update-preferences.php

I tried to hit everywhere that isn't related to permissions and display names.

perf: ->saveQuietly() almost everywhere

---

app/Http/Controllers/Api/SearchApiController.php

Resolves https://discord.com/channels/476211979464343552/1159595979746582602/1375449387953557544.

fix(SearchApiController): use values()

---

app/Helpers/render/game.php
app/Models/Game.php

https://discord.com/channels/476211979464343552/1026595325038833725/1377985814763405414

fallback to substring matching for Subset with no explicit mapping

---

app/Platform/Actions/UpdateGameMetricsAction.php
tests/Feature/Connect/UploadAchievementTest.php

fixes https://discord.com/channels/310192285306454017/533411674162593812/1378746763963273256

always sync achievement set, even if core achievements don't change

---

app/Models/PlayerGame.php

Fixes "mastered by same players" suggestions appearing for games without a set.
https://discord.com/channels/310192285306454017/1378442861300682943/1378442861300682943

require achievements for allAchievementsUnlocked scope

---

app/Http/Controllers/Api/SearchApiController.php

This PR makes some minor adjustments to group relevance scores on multi-scoped ("All") searches.
Queries with multiple words now slant more heavily towards hubs and games. They also reduce the relevancy of the user results. Achievements and events are intentionally not touched by this change.
I suspect, though cannot prove, most users of global search are searching for games and hubs. I will add analytics in a subsequent PR so we can begin processing and understanding this user behavior data.
Without these changes, on my local, queries for "pokemon red" rank users as more relevant than games.
**Before**
**After**

fix(SearchApiController): make some minor group relevance tweaks

---

package.json
pnpm-lock.yaml

Resolves a handful of CVEs. No functional changes.

chore: update several node dependencies

---

app/Helpers/database/ticket.php
app/Helpers/database/user.php
public/request/comment/create.php
public/request/ticket/update.php

fixes https://discord.com/channels/310192285306454017/1366925742314623006/1366925742314623006

fix ticket notification indicator not clearing for users with alternate display_names

---

.github/workflows/ci.yml
app/Helpers/database/leaderboard.php

https://discord.com/channels/310192285306454017/1383550440813101087/1384171929551900772
Set the `score` field _before_ calling `->restore()` to avoid a race condition with model observers.

fix(leaderboard): remediate race condition on restored records

---

app/Helpers/database/achievement.php

Resolves https://github.com/RetroAchievements/RAWeb/issues/3676.

fix(achievementList): respect soft deletes

---

resources/js/app.tsx

https://discord.com/channels/310192285306454017/752271759138357249/1397936934642520125

fix: remove vite preload error refresh

---

app/Http/Controllers/RedirectController.php
resources/views/pages/redirect.blade.php
tests/Feature/Http/Controllers/RedirectControllerTest.php

https://discord.com/channels/476211979464343552/1026595325038833725/1402757054627713044

fix(redirect): security updates

---

resources/js/common/components/ActivePlayerFeed/ActivePlayerFeed.test.tsx
resources/js/common/components/ActivePlayerFeed/ActivePlayerFeed.tsx

https://discord.com/channels/310192285306454017/310195377993416714/1407104478884401255

fix(ActivePlayerFeed): pluralize correctly

---

app/Platform/Actions/BuildGameShowPagePropsAction.php

https://github.com/RetroAchievements/RAWeb/pull/3824#issuecomment-3235462034

fix(BuildGameShowPagePropsAction): set user game list state correctly

---

.github/workflows/crowdin-download.yml
.github/workflows/crowdin-upload.yml

Resolves https://github.com/RetroAchievements/RAWeb/actions/runs/17882915123/job/50852882092.

ci(crowdin): use pnpm 10

---

app/Platform/Actions/BuildGameShowPagePropsAction.php

https://discord.com/channels/@me/1065706550318084117/1420402621943906345

fix(BuildGameShowPagePropsAction): send down fields for subseries hubs

---

app/Platform/Actions/BuildGameShowPagePropsAction.php
resources/js/features/games/components/GameSidebarFullWidthButtons/GameSidebarFullWidthButtons.test.tsx
resources/js/features/games/components/GameSidebarFullWidthButtons/GameSidebarFullWidthButtons.tsx

https://discord.com/channels/310192285306454017/1420527245797101598

fix(game): use backingGame for the guide URL
