RetroAchievements/RAWeb

public/faq.php
On the question about creating achievements.
Also, I wonder if we should make that link on "Home" menu go to our FAQ on the docs site. :thinking: 
https://retroachievements.github.io/docs/FAQ/
=> faq.php: direct the reader to the docs site

lib/utils.php
This is just a suggestion on how to deal with non-ascii chars, to avoid the problems like the one we had on this night (vandalism?).
In this PR I make `seekPOST`, `seekGET`, and `seekPOSTorGET` return only valid ascii chars. When they find a non-ascii char they'll return a `.` (dot).
Example: `pokémon` becomes `pok.mon`.
I'm highlighting the **DON'T MERGE** on the title because I'm not sure if all clients of these functions will work as expected with this behavior.
=> [DON'T MERGE] seekPOSTorGET returns only ascii chars

public/achievementList.php
Added achievement's author to the achievementList table (as requested by @kdecks in #71).
Also omitting some info when on mobile. Namely:
- Achievement's Points (it's redundant because the title shows it between parentheses)
- Author
- DateModified
Here's how it'll look like on a Desktop (don't mind the missing userPics, they don't exist on my local server):
And here's how it'll look like on a mobile:
=> show author and omit some info when on mobile

lib/database/tickets.php, public/ticketmanager.php
changing from:
to (I just repeated the reporter user in the dev's user for this mockup):
=> show cheevo's Author in the tickemanager's main page and columns rearrangement

lib/database/user.php, public/developerstats.php
Showing:
- number of open tickets
- number of achievements on the Core set
- number of achievements won by others
- number of points allocated to achievements
Also adding an option to sort by those criteria (always in descending order).
It'll look like in the example below (don't mind the missing userpics and the outdated numbers):
=> Improvements for Developer Stats page

lib/database/achievement.php
This PR makes Unofficial Achievements not being actually awarded in the server's database.
Currently when someone earn an Unofficial achievement, it remains awarded for the user when the achievement is promoted to the Core. This is not a good approach because while in Unofficial the achievement is a work in progress
Example of why it isn't good: if a challenging cheevo, worthing many points, are in development and an user got it while the code wasn't very accurate (triggering at a wrong time), when the cheevo is promoted to the Core, that user still have the cheevo as awarded. And it is clearly unfair.
If you guys agree with this PR we could make the Unofficial Achievements page (#139, [example for Sonic](http://retroachievements.org/gameInfo.php?ID=1&f=5)) available to regular users too. …
=> do not award Unofficial cheevos

lib/database/game.php, public/gameInfo.php
This closes #13, but does not implement the sorting by the date the user won the cheevo.
It would need more tweaks on the SQL-query, and I don't feel confident enough to handle it for now.
=> fix sorting filters on the game's pages - closes #13

public/gameInfo.php
This PR adds a "More Info" box in the right container, available for any logged in user.
It looks like this screenshot (don't mind the missing boxart, also the link to Unofficial was removed by @GameDragon2k's request):
Also in this PR I've made the link for unofficial achievements (available only for devs) work like a tab (as suggested by @GameDragon2k). As you can see in the 2 screenshots below:
=> adds a "More Info" box with useful links to regular users

lib/database/tickets.php, lib/database/user.php, public/ticketmanager.php
Implementing improvements mentioned in #160.
Option available for devs, admins and the reporter. Also, automatically add a comment when a ticket is reopened and who reopened it.
Actually this was the original request made by @JuliaWolska in #160. In this PR I'm allowing tickets to be closed (and not exactly being marked as "Resolved") and offering some options for the reason of closing.
Again, any change on the ticket status, automatically add a comment saying what was done and who did it.
Developer view of an open ticket (in the comments you can notice some comments automatically added when I changed the ticket status):
**EDIT:** changed radio buttons to a dropdown list. [See the comment below](https://github.com/RetroAchievements/RAWeb/pull/167#issuecomment-395936233)
Reporter view of …
=> ticketmananager improvements - closes #160

lib/database/achievement.php, lib/database/activity.php, public/requestupdateachievement.php
The problem in the previous attempts were caused by [this wrong function call here](https://github.com/RetroAchievements/RAWeb/compare/audit_log?expand=1#diff-295c69655390b9ab4408ceea39d90e70L502).
=> yet another audit-log attempt

lib/database/game.php, public/gameInfo.php
a MySQLi query object cannot be `FALSE` unless the request was not sanitized correctly. `$dbResult` represents not a result, but a query object.
As a result, `$gameData` in `gameInfo.php` was always set to a default zero-valued result set.
This solves that issue, avoids filling game data with default values, and aborts game information page loading for invalid IDs (e.g. /Game/0).
=> Fix game ID error handling on the game information page

lib/database/utility.php
**First of all**: huge thanks to @stt for showing me that it's possible to parse MemAddr with Regular Expressions :nerd_face:
This PR changes the behavior of `GetAchievementPatchReadableHTML()`, making it produce this output:
rather than the current buggy one:
=> parse MemAddr with RegEx and show a fancy table

lib/dynrender.php
Closes #271.
https://github.com/RetroAchievements/RAWeb/issues/272 is also needed to match the naming scheme of `SG-1000/Othello Multivision`.
=> Add PC-88 to Site Pages

lib/database/game.php, lib/dynrender.php, public/dorequest.php, public/download.php, src/Emulators.php
Got some boring time ~~while at work~~ and decided to do these things in advance.
- added a RAQUASI88 entry to `src/Emulators.php`
- added a RAQUASI88 entry to `latestclient` in `public/dorequest.php`
- added the PC-8800 console ID as valid in `isValidConsoleID()` (`lib/database/game.php`)
- added an entry in the downloads page
~~Waiting the RAQUASI88 binary to finish the next steps:~~
Steps already taken (09/January/2019) outside this PR
- created a `LatestRAQUASI88Version.html`: http://retroachievements.org/LatestRAQUASI88Version.html
- uploaded the `RAQUASI88.zip` binary: retroachievements.org/bin/RAQUASI88.zip
=> [WiP] add support for RAQUASI88 (NEC PC-8000/8800 emulator) - closes #254

public/gameInfo.php
I made an html edit test and then took a poll on preferences for this change:
Here's the supportive straw poll: (https://discordapp.com/channels/310192285306454017/511718348178849792/541536891326038016) 32 votes in favor, 4 to stick to original, 3 to only increase the game icon).
This is my attempt to modify the game page by increasing the game Icon size, increasing the indent after icon, and adding the game info under the title to make use of the empty space.
The intent is for the game pages to look like this: https://i.imgur.com/J1G46hY.png
I do not know if there is a conflict or if it is considered sloppy having a class inside a class, and I'm editing the raw code without testing, so I might be messing this up.
=> Game page: Increase icon size and move game info up

lib/database/game.php, lib/dynrender.php, public/dorequest.php, public/download.php, src/Emulators.php
- added a RAppleWin entry to `src/Emulators.php`
- added a RAppleWin entry to `latestclient` in `public/dorequest.php`
- added the RAppleWin console ID (`38`) as valid in `isValidConsoleID()` (`lib/database/game.php`)
- added an entry in the downloads page
- added "Apple II" to the list in `lib/dynrenderer.php`
On the server side I did:
- created a `LatestRAppleWinVersion.html`: https://retroachievements.org/LatestRAppleWinVersion.html
- uploaded the `RAppleWin.zip` binary: https://retroachievements.org/bin/RAppleWin.zip
=> WIP: add support for RAppleWin (Apple II emulator)

lib/database/utility.php, public/dorequest.php, public/requestsubmitcodenote.php
When trying to submit a new code note, do **NOT** allow the note to be updated/submitted if:
user is not a developer
**AND**
user is not the author of original note
**AND**
code note is not empty
In other words:
regular users can only submit/edit Code Notes when they are the original Author or the Note is empty.
=> prevent Code Notes vandalism - closes #309

lib/database/game.php, lib/dynrender.php
Changes validate Sega CD and Sega 32X as well as adds them to the "Site Pages" drop down.
=> Add Sega CD and 32X to site

public/achievementList.php
Makes the core achievement list the default view and adds the option to view unofficial achievements only, rather than "all achievements" which would also include cheevos that were hidden/deleted.
=> Sorting update to achievementList.php

lib/dynrender.php
- Moves the "Easy Achievements" link from "My Pages" back to "Site Pages" above "Hardest Achievements" - how did it get there anyway? 
- Moved all links in "Messages" to "My Pages" and turned "Messages" into "Games" - which in turn is moved between "Download" and "My Pages"
- Moved all game lists to new "Games" section
- Changed "NES" to "NES/Famicom"
- Changed "Super Nintendo" to "SNES/Super Famicom"
- Sorted game list by consoles, arcade, computers, and handhelds. 
- Moved "Popular Games" to the bottom of "Games" and renamed to "Most Played"
- Moved "Supported Games" to the bottom of "Games" and renamed to "View All"
- Removes "Official To-Do-List" from dropdown - it's a forum post that hasn't been maintained in over a year and made obsolete with github issues.
=> Updates to site dropdown/toolbar

lib/database/game.php, lib/dynrender.php, public/latesthasheslinked.php
This would add a new page to track when hashes have been linked. The page can be found in the Developer dropdown.
The page displays each hash, the game it's linked to, and the date it was linked in reverse chronological order.
I added in a search feature as well. It lets the user search for a specific hash. My plan is to eventually update the main site search with hash support, but for now a seperate search on this page will work fine. 
Since a timestamp was only recently added the the gamehashlibrary database table the majority of the hashes will have the same date linked. The default entries per page is 50 and can be updated in the latesthasheslinked.php code. This page will not show hashes that have been unlinked since those are completely removed from the database.
=> New Page to Track Linked Hashes

lib/database/game.php, public/achievementinspector.php, public/awardedList.php, public/controlpanel.php, public/createaccount.php, public/css/style54.css, public/editpost.php, public/friends.php, public/gameSearch.php, public/inbox.php, public/latesthasheslinked.php, public/leaderboardList.php, public/resetPassword.php, public/searchresults.php, public/submitnews.php, public/ticketmanager.php, public/userList.php, public/viewtopic.php
- In several pages, there was no rightcontatiner div, or an empty div, so I converted the leftcontainer div to a fullcontainer div so there was not a large blank area on the right side of the page.
Before:
After:
- In the messages page, the rightcontainer div is moved out of the leftcontainer div and the footer is fixed.
- In the friends list page, the friends leaderboard is added to the rightcontainer div.
- In the settings page, the footer is fixed.
- In the achievement inspector page, the fields are organized in a table and sorted alphabetically.
=> Fixed various page layouts

lib/dynrender.php, public/css/style54.css
**Multiline support has been added to the basic formatting tags.**
**New tags were added:**
- Underline tag - [u] - Text within the tags will be underlined
- Code tag - [code] - Text within the code tags is monospaced and is enclosed by a small border.
- Spoiler tag - [spoiler] - The user can click on the spoiler text to display everything with the spoiler tags.
- All other tags are allowed within the spoiler tags as well.
=> New BBCode tags and updates

public/awardedList.php
I missed a closing curly bracket on the awardlist page in my last PR which is causing a syntax error.
=> Fix Awardlist Page

public/css/style54.css
My last PR broke word wrapping on achievement logic. The PR will fix it.
=> Fixed broken word wrapping on the achievement logic display.

lib/database/user.php
It was recently found that when player had completed a game and mastered a game of the same name on a different system, the complete game award did not show up on the users page.
The fix for this was to change 'Title' to 'AwardData' when squashing any same game awards into one.
=> Properly show complete & mastered site awards for same title games

lib/dynrender.php
Adds Atari Jaguar, WonderSwan, and Nintendo DS to the "Games" list in the navigation bar. They'll be hidden until there's at least one set in core. 
Hid Sega 32X since there's not a core set yet. 
Moved Pokemon Mini under Game Boy Advance/Nintendo DS.
Changed all "Gameboy" handhelds to "Game Boy" to be consistent with the rest of the site.
=> Update to dynrender.php - Games List

database/20191218_000000_Add_SetRequest.sql, lib/database/game.php, lib/database/user.php, lib/dynrender.php, public/API/API_GetSetRequests.php, public/API/API_SetSetRequest.php, public/css/style54.css, public/gameInfo.php, public/setRequestList.php, public/setRequestors.php
This gives the user the ability to request sets to be made for games that do not have any core achievements yet. It comes with various ways to view most requested sets, my requested sets, and who requested a set for a game. The request feature works similar to the game rating feature where the user just need to click the text to request or withdraw a request and the new information is displayed instantly without needing to reload the page.
`database/20191218_000000_Add_SetRequest.sql` will need to be run to create a new setrequest tabe in the database to store the user set request information.
Here is a video demo I made a few days ago https://streamable.com/seiuw. There have since been a few typos fixed and some minor updates made, but it gives the general idea of the feature.
The total …
=> Implement Set Request Feature

lib/database/setrequest.php, public/setRequestList.php
Some set request queries were returning games that already have sets which prevented the "Next 50" link from showing up in some cases.
=> Fix Set Request Queries

lib/database/leaderboard.php, public/leaderboardList.php, public/request/leaderboard/create.php
Adds leaderboard duplication ability to the Leaderboard List page. Allows user to specify a leaderboard ID and number of times to duplicate it for the currently selected game. Duplicated leaderboards will increment in display order. The input areas are restricted to numerical values greater than 0.
This is useful for games that have several nearly identical leaderboards. It will really speed up leaderboard creation in those cases.
Also updated adding a single leaderboard to increment the display order.
This would resolve issue #386.
=> Add Leaderboard Duplication

lib/database/setrequest.php, public/setRequestList.php
Add a console filter drop down allowing users to view requested sets for desired consoles. The drop down also lists how many games per console that have set requests for them
This PR would resolve #392.
=> Add console filtering to most requested sets

lib/database/achievement.php, public/ticketmanager.php
This update will show how many times an achievement has been awarded since any given ticket was created against it. It should assist in determining if older tickets are valid or not.
softcore **(Hardcore)**
=> Display awards since ticket creation

lib/database/ticket.php, public/ticketmanager.php
This feature adds several new ways of filter tickets on the Ticket Manager page. Each filter can be individually toggled which allows for a good amount of custom filtering. Total open tickets and total filtered tickets will always display in the headers on the page.
Default Filter:
Custom Filter:
The filters are also compatible with the existing user and game filters as well as tickets for achievements in unofficial.
The filters are broken into the following categories:
**Ticket State** - The state of the ticket
* Open
* Closed
* Resolved
**Report Type** - Why is this ticket being written
* Triggered at wrong time
* Doesn't Trigger
**MD5** - Does the ticket include a MD5
* Contains MD5 - (e.g. `MD5: e9b45d6455e0753b8e0e825a36458253`)
* MD5 Unknown - (e.g. `MD5: Unknown` or `MD5:` is not …
=> Advanced Ticket Filtering

lib/database/ticket.php
The updated logic will correctly filter the <1% of tickets that were slipping by.
Tickets with a ReportType other than 1 will show in the `Doesn't Trigger` filter, this catches the few that were a 0 somehow.
Tickets where the user entered a valid MD5 but did not select it from the list will now show in only `Contains MD5` filter.
Also removed some unnecessary logic that would never be executed.
=> Ticket Filtering Logic Updates

lib/database/achievement.php, lib/database/activity.php, lib/database/game.php, public/achievementinspector.php, public/gameInfo.php, public/request/achievement/update.php
This update allows users with >= developer permission to mass promote/demote individually selectable achievements from a games achievement inspector page. The achievement inspector page has also been updated to show unofficial achievements.
The link to a games achievement inspector will specify unofficial or core.
Unofficial achievements will now show up in the Unofficial Achievement Inspector
On a games Achievement Inspector page there will now be checkboxes for each achievement. The user can check the desired achievements and choose to promote or demote them. The user can also click the `All` or `None` links in the top row of the table to check all or none of the checkboxes. After clicking the Promote/Demote Selected link the page will refresh. The user can also switch between core and …
=> Promote/Demote Selected Achievements

lib/database/user.php, public/history.php, public/js/all.js, public/reorderSiteAwards.php, public/request/user/update-site-award.php, public/userInfo.php
This update will allow users to hide site awards if they set the Display Order value to -1. Hidden site awards will still be visible on the Reorder Site Awards page so users can make them visible again.
This would resolve #380.
=> Allow Users to Hide Site Awards

public/history.php
Update history page so sorting by date/Num Achievement/Score Earned on another users history page stays on their page rather than bringing you back to your page.
Also added a filter by user text area at the top of the page so users can easily switch to other users history pages without  having to modify the URL.
This would resolve Issue #433.
=> Minor History Page Update

lib/database/user.php
Affects both the rank and the top percentage.
Slightly reworked the query so that ties are rounded up instead of down
and there's no need to join UserAccounts with itself.
=> disregard untracked users when calculating rank for user profiles

lib/database/achievement.php, lib/database/codenote.php, lib/database/ticket.php, lib/database/user.php, public/css/styles.css, public/individualdevstats.php
Updates the the dev stats page to fix a few issues and add some few features.
- Couple typos fixed on page and in code.
- Achievement tooltip now shows game rather than console.
- Games with a less than 1 retro ratio will no longer show as easiest game (Unless it the only game).
- Stats no longer include "games" or "achievements" from Hubs or Events.
- Untracked user stats are no longer counted.
- Added average achievement memory length.
- Added shortest and longest achievement by memory length.
- Added table for last 100 achievements obtained.
- Replaced game with most code notes with a table of all games with code notes created by the dev.
- Added total/closed/resolved ticket karma ratio (+/-).
=> Dev Stats Update

lib/database/achievement.php, lib/database/game.php, public/gameInfo.php
Ignore untracked users in:
* achievement stats shown in game and achievement pages
* achievement distribution graph in game page
Fixes #301. The total unique players of the set is used, not the amount
of earners of the most earned achievement in the set. Both for the game
and achievement pages.
Also fixes the infamous won-by-0-of-0 bug.
=> disregard untracked users in achievement-related stats

lib/database/achievement.php, lib/database/game.php, public/gameInfo.php
Ignore untracked users in:
* achievement stats shown in game and achievement pages
* achievement distribution graph in game page
Fixes #301. The total unique players of the set is used, not the amount of earners of the most earned achievement in the set. Both for the game and achievement pages.
Also fixes the infamous won-by-0-of-0 bug.
------------
Fixed the issue in which achievements only earned by untracked users did not show up in the game page.
=> disregard untracked users in achievement-related stats v2

lib/render/achievement.php
Problem was noticed in http://retroachievements.org/game/16191, because the second to last achievement's title contains the word _hidden_ after a single quote, which is an actual html attribute and ends up hiding the badge's image tag.
=> escape html characters in alt & title attributes of badge image tags

lib/database/forum.php, public/css/styles.css, public/forum.php, public/js/all.js, public/viewforum.php, public/viewtopic.php
Added copy comment link image to each forum comment. This allows for easily sharing links to a specific comment on the forums or in discord.
Clicking the chain link icon in the top right of any comment will copy the link to that comment to your clipboard.
Navigating to the copied link will take you to the page with the comment and outline it so it is distinguishable form the rest.
Hovering over the icon will turn it white and as the mouse is pressed it will turn back to the original icon, indicating that the URL has been copied.
Here is the new link image.
The image needs to be placed in `getenv('ASSET_URL') . "/Images/Link.png'`
It should be the same location as the Submit.png icon. ![image](https://user-images.githubusercontent.com/16140035/79671013-fa239400-8194-11ea-8e2a-f14bad94d2d5.p …
=> Forum Comment Link

lib/database/codenote.php, public/individualdevstats.php
Updates the code notes table on the dev stats page to ignore notes for invalid games.
Also ignores code notes of size 0, so deleted code notes will no longer be counted.
Also fixed the "Achivement" typo in the Recently Obtained Achievements table.
=> Dev Stats Code Notes Table Update

lib/database/activity.php, public/request/comment/delete.php
Hi,
I'm not sure it is a security issue but I'm able to remove easily any comment on the site by forging the appropriate HTTP request.
I think it is not a good practice and that's why I propose a fix.
=> Only an admin or the owner should be able to remove a comment

lib/database/activity.php
Hi,
GameID is missing from the request, then always null (0 once cast to int).
=> Fix GameID is always 0

lib/database/leaderboard.php
Update leaderboard to calculate and display the number of hours for times.
The above table will now be displayed like the following table.
=> Update Leaderboard Times to Display the Number of Hours

lib/database/setrequest.php, lib/database/user.php, public/userInfo.php
**Calculation** - 
Previous:
Get requests at 5000 points, 10,000 points, 15,000 points, 20,000 points, and then every 10,000 points after that until 180,000 points (caps at 20).
New:
Adds an extra request at 2500 points, an extra request for every year of the users account age and every 20,000 points after 180,000.
**Link** -
Adds a link to a users set requests on their profile page under their site rank. Also displays their current used and current max requests.
=> Update to Set Request calculation and adds a link on profile

public/request/ticket/create.php
Update to show entered core when choosing the RALibRetro Emulator when creating tickets.
This would resolve issue #490.
=> Show entered cores when creating tickets with RALibRetro chosen

public/ticketmanager.php
Adds a new "Closed - Unable to reproduce" option to the ticket action dropdown.
=> New "Closed - Unable to reproduce" Ticket Action

lib/database/achievement.php, lib/database/activity.php, lib/database/user.php
Assure a valid username is being used before proceeding with "give-award".
To achieve this goal I've changed the behavior of `correctUserCase()` in the case where it fails to find the given username (now it returns `null`, instead of the given username). Also renamed the function to `validateUsername` to describe it better.
In this PR I'm also changing the two clients of that function, making them abort when no valid username is given.
=> change correctUserCase() -> validateUsername()

lib/database/game.php, lib/render/leaderboard.php, public/API/API_GetGameRankAndScore.php, public/css/rac_green.css, public/css/rac_red.css, public/css/rac_white.css, public/css/styles.css, public/gameInfo.php
This updates the High Scores section on game pages to turn it into a tabbed section, one tab have the existing high scorers of the set and a new tab showing the latest masters of the set. Most games will show the same 10 users forever unless there is a revision to the set. When that happens some users will try to snipe the top spots so their names will always show up. The new tab would show more recognition to the users who were not one of the first 10 users to master the set. The Latest Masters tab will automatically be selected if 10 or more users have mastered the set, otherwise the High Scores tab will be automatically selected. I've also outlined the logged in user if they are in the list.
Here is how it would look for a game with 10+ masters and a game with less than 10 masters.
=> Add Latest Masters Tab to Game High Score Section

lib/database/game.php, public/gameInfo.php
Currently the achievement distribution chart counts unofficial achievements along with the core achievements. Because of this, sets with unofficial achievements that have been earned by several users will cause the achievement distribution chart to plot incorrect data. This updates fixes this issue and counts only core achievements when viewing the main game page, and only counts only unofficial achievements when viewing the unofficial achievements.
[Tony Hawk's Pro Skater 2 (PlayStation)](https://retroachievements.org/game/11282) is an example of the chart being incorrect because it has one achievement in unofficial that has been earned by 50+ users. Currently there are over 20 masters but the current chart shows only 2 people have 56 achievements.
=> Achievement Distribution Fix

lib/database/game.php, lib/render/game.php, public/gameInfo.php
Reduce visual clutter on game hub pages by removing all elements that
only make sense for fully featured games.
Features to edit the "game" have been adjusted accordingly.
Games are ordered by achievements availability, title.
Before:
After:
=> Display game alternatives on game hubs only

lib/render/achievement.php, lib/render/game.php
It's a fix for functions creating URLs for games and achievements. URLs starting with uppercase lead to 302 redirection, which does uneccessary hassle for browser and server.
=> fix rendering links to games and achievements

public/API/API_GetUserRankAndScore.php, public/API/API_GetUserSummary.php
In the current APIs API_GetUserSummary and API_GetUserRankAndScore, user "Rank" is available, but the total ranked users information is never available, so it's impossible to count the users rank given the total ranked user and calculate the "top percent" value, as it exists in the /public/userInfo.php page that displays -> " 43018 / 83792 ranked users (Top 52%) ".
=> Add TotalRanked to API_GetUserSummary and API_GetUserRankAndScore

lib/render/layout.php, public/setRequestList.php
Removed the game count from each individual console in the console filter dropdown on the Most Requested Sets page. Added the page link back to the "Games" toolbar.
I'm fairly certain that this is causing the extreme load times on this page. I can't do a fully accurate test as my local DB only has ~3K set requests, but the page loads up instantly verses taking ~5 seconds after making this change. Worth checking to see if the new page load speed is acceptable with a production sized DB as many users have asked where this page link went.
=> Most Requested Sets Fixes

lib/database/user.php, lib/render/user.php
Takes care of #555 by changing Untracked user info card ranking to "Untracked" as seen below
=> Fix untracked users showing rank in user tooltip

lib/util/trigger.php
- Fixed Add Source, Sub Source, and Add Address flags displaying all 0's due to `=0` being removed from the logic string.
- Added in Reset Next If, Sub Hits, Trigger, and the BCD size type
- Renamed `Special?` to `Flag` to match the achievement editor.
`A:0xH00b3a3_46134=b0xX000234_D:d0xH00b406=0_B:p0xH00b4b5_Q:b0xH00b546=0_O:0xH00b57a=d0xH000000_T:46289=0_Z:b0xH00b4f9=p0xH000000_I:0xH00b578_d0xH00b4cb=b0xH004321`
=> Mem Explained Updates for RAIntegration 0.79

lib/render/leaderboard.php
Fixed bad URL in the Friends Ranking section when clicking on your daily point count.
=> Friends Ranking URL Fix

lib/database/game.php
Fixes issue where similar games would not be added to the database if one of the IDs entered in the field is already linked. The `Updated` time for existing entries in the database will be updated to the current time.
=> Similar Games Duplicate ID Fix

cronjobs/cron_1m.php
If I'm understanding this correctly it looks like a cron job runs every minute and does the Recalculate Score on 3 users each run.
https://github.com/RetroAchievements/RAWeb/blob/111a426503f62e8dc5f78ccbe1b182cd7432906d/cronjobs/cron_1m.php#L44-L50
The selection of users could easily check for only users that have points to speed up the process
https://github.com/RetroAchievements/RAWeb/blob/111a426503f62e8dc5f78ccbe1b182cd7432906d/cronjobs/cron_1m.php#L20-L23
Going by current total users on the site: 158811
It checks 3 (per run) * 1 run per minute * 60 runs per hour * 24 hours in a day = 4320 users per day.
So it currently should take around 37 days to fully go through all users but based on data from an older dump it seems like roughly 40% of the users on the site have 0 points so that …
=> Cut auto recalc time roughly in half by excluding users with 0 points

public/leaderboardinfo.php
Allow users to share the same rank when having a tied score/value for a leaderboard. The first user to obtain the best score/value will continue to be the one that is shown as the leader of the leaderboard but this will allow for multiple No.1 rankings.
=> Leaderboard ranking ties

public/leaderboardinfo.php
Missed a case where best score is 0 would set first place rank to 0, updated nextRank to initialize at 1 instead to fix.
=> Leaderboard ranking tie

cronjobs/cron_1m.php, lib/bootstrap.php, lib/database/user.php, lib/render/user.php, public/userInfo.php
Adjusts the Site Ranked users to exclude users with less than 500 points. This will make the Top X% more accurate as a large number of users have less than 500 points (~ 70%). Users with less than 500 points will instead see a message saying they need at least 500 points in order to be ranked (image below has initial proposed 100 point threshold but shows the idea).
=> Adjust ranking requirement to 500 points

lib/util/bbcode.php
Twitch requires the `parent` (domain name) query parameter for embeds. Without it it results in the following error message after parsing the Twitch URL:
=> Fix Twitch embeds

lib/render/game.php, public/css/styles.css, public/gameInfo.php, public/leaderboardinfo.php
This commit introduces visual changes in "More info" section of a game page.
That's how the change looks like:
Except this section, it also changes link to the official forum topic, in the same manner, under achievements list and on leaderboard page.
The reason behind this change is that actual "More info" section is not really readable, especially that it contains a lot of redundant words (like repeated full game name). After changes those links are cleaner, but also easier to tap on mobile screens. I prepared new look of links for every possible action, even those not used at the moment.
For created forum topics I removed the game name from the anchor, as it's rather obvious, that it's about this game, but if topic is not created, I left this info, so devs could be more sure what this …
=> Redesign "more info" links

lib/database/rom.php, public/linkedhashes.php
The User being returned in every `getHashListByGameID()` call is causing this:
reported by @StingX2 on discord
=> getHashListByGameID(): only get User if explicitly requested

public/leaderboardList.php
Cap the amount of leaderboards a user can duplicate in a single attempt at 25. Prevents cases where 100s or 1000s of duplcate leaderboards might get created by accident.
=> Duplicate Leaderboard Cap

lib/database/forum.php, public/viewforum.php
This commit will add pagination on topics list on forum.
It's done the same way how other paginations here works: it limits query by parameter "o" in the URL (and "c", which is the count on one page and it is set by default as 25). In fact, most of the work was prepared already, but the query lacked LIMIT command and there was no COUNT query to get number of all topics in a category.
I did most of things by analogy to posts pagination, only except pagination links – just saved generated links in variable and displayed in two places (DRY rule).
This pull request addresses the issue #506 – solves the problem with performance, caused by rendering long list of topics. I'm not sure, if second issue mentioned there is solved by now.
=> Add pagination on topics list on forum

lib/bootstrap.php, public/achievementList.php, public/css/styles.css, public/developerstats.php, public/download.php, public/forum.php, public/forumposthistory.php, public/gameList.php, public/setRequestList.php, public/userList.php, public/viewtopic.php
Despite earlier improvements on responsiveness of RA, there are still pages which have elements wider than the screen size. Mostly that are pages with tables, as tabular data is difficult to present on narrow screens (there is too much info in horizontal space). Changes from this Pull Request are introducing "table wrapper" – tables on mobile will be scrollable horizontaly within it, without expanding page's layout with its size.
Also, there is also a change in forum topic table layout, transforming table cells in row as one column on mobile devices. It will help to save space, because left column with username and avatar had a little of content, but was taking space of whole row's height (and, dependent on username length, it was letting less space for the post content).
There is also a …
=> Fix responsiveness for some pages

public/individualdevstats.php
This is just a small patch to #598 – as @meleu noticed, pie charts on individualdevstats.php had legend cut off on mobile screen size.
This change is only adding variables to draw charts in different sizes depending on screen width. It does only once, when charts are rendered, so it won't adapt if window size will be changed after loading the page (but I guess it's not an issue, as smaller charts concerns only really narrow screens).
After changes:
=> Render smaller charts on mobile (individualdevstats.php)

lib/database/leaderboard.php, public/leaderboardinfo.php
Allows for navigation through all leaderboard entries for a given leaderboard which should solve some of the issue in #493
Slight update to the way ranks are calculated so that they will stay accurate when navigating to entries past the first 50. Also previously the users own displayed rank when not in the top 50 included Untracked users in the total even though they aren't displayed which has been fixed.
Navigation added
Properly keeps rank across pages (Second page showing entries 51+ tied for 38th)
=> Leaderboard navigation

lib/constants.php
Latest changes in JS files are not received for users because of it's cached version. Bumping version to force downloading updated script.
Sorry for forgetting that...
=> Bump version to 1.73.1

public/inbox.php
Just a follow-up to recent changes, as there were still some uses of function exists() from watermark.js in inline JS on inbox.php (which causes an error and messages cannot be set as read/unread).
=> Replace exists() function in inbox.php

lib/database/leaderboard.php
The getLeaderboardsForGame() function only returns the number of leaderboards with entries. I've updated it to return the number of leaderboards regardless of the number of entries for them. This fixes an issue where the "Manage Leaderboards" and "Create First Leaderboard" links may show incorrectly if the created leaderboards do not have any entries.
=> Leaderboard Count Fix for Leaderboards Without Any Entries

lib/database/leaderboard.php, phpstan.neon, public/dorequest.php
Update lbinfo and GetLeaderboardData to return nearby user entries when checking from emulator overlay by adding user index as well as add total entries to the returned object to allow for future scrolling/navigation. Takes care of the request in #625
=> Update lbinfo call and GetLeaderboardData to allow showing around user entry in overlay

lib/util/bbcode.php
This will fix the embedded video links so they retain the querystring parameters, such as start/end timecodes.
=> fix: #425 keep querystring parameters in youtube embed links

lib/database/user.php
This will exclude the unofficial achievements from the total count in the Reset Game Progress dropdown.
=> fix: #293 exclude unofficial achievements in progress dropdown

lib/database/activity.php
This fix updates the Active Players list to put them in Site Rank order instead of the default ordering by UserID (i.e. order the user was created).
=> fix: #516 revise order of active players

public/achievementInfo.php
The sanitization function uses a null value for the second parameter, so it won't convert quotes to HTML entities. Since this string function is used throughout the site, a simple solution is to only convert the entities that are being used within attribute values.
=> fix: #373 escape achievement description for attributes

lib/database/leaderboard.php
Updated GetLeaderboardData() query to have a subselect statement to get the number of entries for the leaderboard. Previously the query would return null for all values if the leaderboard had no entries in it.
This prevented jr. devs from being able to edit their own leaderboards if there were no entries.
This also caused the leaderboard page to show unknown values if there were no entries.
=> Fix for Leaderboards with No Entries

lib/render/comment.php, public/achievementInfo.php, public/leaderboardinfo.php, public/request/comment/delete.php, public/ticketmanager.php, public/userInfo.php
Fixes delete button being available for delete users' comments when not logged in.
Reason: positively compared `null` to `null` here: https://github.com/RetroAchievements/RAWeb/pull/679/files#diff-19a5e613d5b30767be3889ef2bfb1634f7b8affab4670d8492e2de28f481665aR102
=> Fix comments permissions

lib/render/layout.php, lib/render/news.php, public/css/styles.css, public/reportissue.php, public/request/ticket/create.php, public/views/checksumDescriptionModal.html, public/views/issueDescriptionModal.html, public/views/versionDescriptionModal.html
Certain fields now have clickable links that will bring up a modal that gives important information for that given field. I have also added an Emulator Version field to help make tickets more useful, especially in light of recent updates making save states store hit counts.
I also added in an "Easter egg" of sorts that will prevent a user from submitting the ticket if the description has nothing but something along the lines of, "Doesn't work," prompting them to put in something more substantial, if the description is shorter than 25 characters. This won't prevent someone from making a long-ass description that says absolutely nothing, but I figure it will help educate people inclined to lazily state the obvious to be more thoughtful.
Intended to close #524.
=> Links to supplementary ticket info are now provided after certain fields

lib/database/activity.php
When starting a new game, the user's "Last seen in" doesn't update until the first Rich Presence message is sent.
This PR sets the Rich Presence to "Playing [Game Name]" when a new session is started. It will be updated normally when the first Rich Presence message is sent.
In addition to immediately updating the "Last seen in", this addresses an issue reported by the DuckStation devs where they don't send Rich Presence messages for games that don't have Rich Presence: https://discord.com/channels/310192285306454017/310195854642249728/884134268605980695 
> The last game I played is Gran Turismo, but "Last seen" shows the last game I played that had rich presence
The "Playing [Game Name]" will remain as the last activity until replaced by something else.
=> immediately update rich presence when starting a new session

public/gamecompare.php
fixes #204
also no longer counts hardcore achievements as two unlocks
=> fix incorrect key for hardcore check in gamecompare page

lib/database/activity.php, lib/database/forum.php, lib/util/mail.php, public/request/forum-topic-comment/create.php, src/ArticleType.php
implements #649 
Changes the middle of an email message to include the title of the related record.
Before:
```
New Game Wall Comment from User123
Hello Jamiras!
A game wall discussion you've commented in on RetroAchievements has received
a new comment from User123. Click [here] to see what they have written!
Thanks! And hope to see you on the forums!
-- Your friends at RetroAchievements.org
```
After:
```
New Game Wall Comment from User123
Hello Jamiras!
User123 has commented on the game wall for Super Mario Bros. (NES). Click [here] to see what they have written!
Thanks! And hope to see you on the forums!
-- Your friends at RetroAchievements.org
```
Some other examples:
```
Jamiras has commented on the achievement wall for Master Plumber III (Super Mario Bros.).
```
```
Jamiras has …
```
=> more descriptive email messages

lib/database/leaderboard.php
Before:
```
...
"Leaderboards":[{"ID":3774,
"Mem":"STA:0xH00005c=4_0xH000043=5::CAN:0xH00005c=11::SUB:0xH00005c=12::VAL:0xH000095*10000_0xH000096*1000_0xH000097*100_0xH000098*10_0xH000099",
"Format":"SCORE",
"Title":"Waldo Challenge",
"Description":"Highest score completing the Waldo Super Challenge"}]}
```
After:
```
...
"Leaderboards":[{"ID":3774,
"Mem":"STA:0xH00005c=4_0xH000043=5::CAN:0xH00005c=11::SUB:0xH00005c=12::VAL:0xH000095*10000_0xH000096*1000_0xH000097*100_0xH000098*10_0xH000099",
"Format":"SCORE",
"LowerIsBetter":false,
"Title":"Waldo Challenge",
"Description":"Highest score completing the Waldo Super Challenge"}]}
```
=> include LowerIsBetter in leaderboard patchdata

public/gameList.php
Also removes an empty cell that doesn't correspond to any column.
This fixes leaderboard and ticket totals displaying under the incorrect columns.
=> Add an empty cell under the Last Updated column

lib/database/user.php, public/dorequest.php, public/login_app.php
Fixes #109 and #238 for the `dorequest?r=login` API.
The 0.79 DLL switched from using custom URLs to using rapi, which also caused it to switch from using the `login_app` endpoint to the `dorequest?r=login` API for logins. Because the two endpoints are out-of-sync, this resulted in #109 reappearing (see https://discord.com/channels/310192285306454017/310195854642249728/894042414132625438).
Retroarch has always used the `dorequest?r=login` API for logins, so it has never benefitted from the case-correcting, but I believe all that is affected there is the welcome message.
This ensures the two endpoints behave the same, though I don't believe anything is using the `login_app` endpoint any more.
Example test responses:
```
$ curl "localhost/dorequest.php?r=login&u=jamiras&p=Jamiras" && echo …
```
=> make dorequest?r=login behave like login_app

lib/database/forum.php, public/viewtopic.php
Instead of filtering on forum topics where the last post is unauthorized, this modifies the query to count the number of authorized posts in a forum topic and ignores anything without any authorized posts.
The list will still show the unauthorized user as the user for the last post, but upon opening the topic, the unauthorized posts will remain hidden.
The unauthorized links page still shows the full post count:
The unauthorized post also does not appear in the Forum Activity list on the main page, or the Forum Post History. No change was necessary for that behavior.
=> don't hide forum topics if last post is from an unverified user

lib/database/achievement.php, lib/database/activity.php, lib/database/friend.php, lib/database/leaderboard.php, lib/render/error.php, public/request/message/send.php, public/userInfo.php
Removes the "Send Private Message" link from a user's page when that user has blocked the logged in user. Also removes the ability to post comments on that user's page.
Additionally, removes blocked users from the "compare with friends" lists on the game page and a couple of API calls.
Fixes #813. Closes #691
=> Prevent blocked users from sending private messages

public/gameInfo.php
The "Official Forum Topic" link always appears after the achievements. It only appears in the sidebar when logged in. This just makes it visible in the sidebar when not logged in.
It does have the unintended side effect of showing an empty "More Info" sidebar section if not logged in and the game does not have an official forum topic.
=> allow official forum topic sidebar link when not logged in

lib/constants.php, lib/database/game.php, lib/render/game.php, public/gameInfo.php
Adds a "Recent Players" section at the bottom of the game page (just above the comments). It's populated with the 10 most recent "Last Seen In" entries matching the game. If there are no recent "Last Seen In" entries, the section is not shown.
Implements #730, but only shows the 10 most recent and does not automatically refresh.
Does 10 seem like a reasonable number? It could be unbounded, but in my dump from 2018 there's nearly 1400 entries for Super Mario World.
Would the header be better as "Recent Players" (as pictured), "Recent Activity", "Recent Player Activity", "Recently Seen Players", or something else?
=> show recent players on game page

lib/database/game.php, public/API/API_GetGameRankAndScore.php, public/gameInfo.php
The query used to determine the latest masters of a set and highest scorers for a set is very intensive when a set has a lot of users as it has to calculate every user's score for the set and the datetime of the last achievement earned by the user from the set.
The current implementation runs the query twice, once for High Scores, and once for Latest Masters. This PR runs it once to determine both.
In my dev env, this eliminated 25% of the time spent generating the game page for Super Mario Bros. (6.6s down from 8.8s), which has 5186 unique users for which those values had to be calculated.
I'm not sure if this will translate directly to the live site. The live Super Mario Bros. set has over 17k users, and Super Mario World has over 27k users. Both of these pages took me more than 15 …
=> eliminate second call to expensive query

lib/util/bbcode.php, public/css/styles.css, public/test/bbcode.php
Allows to add URLs as links for services that are embeddable (YouTube,
Twitch, Imgur). Fix link tooltip background color and clean up bbcode
util while at it.
Fixes #818
Verify via `/test/bbcode.php` in browser:
=> Fix bbcode URL parsing for embeddable services

lib/render/user.php, public/reorderSiteAwards.php
This updates the site awards images to be read from the RA server rather than amazon. Also moves them to the `/Images` folder rather than the `/Badge` folder. Images in the `/Badge` folder can be used as achievement badges, which is the driving force for this update.
Will resolve #832 after the proper images are moved the the correct directories and the amazon badges updated back to their originals.
=> Site Award Image Hosting Update

lib/render/achievement.php, lib/render/game.php, lib/util/string.php
#874 made it so apostrophes could appear in tooltips, but broke the "fancy" tooltips in the process.
current:
intended:
=> fix display of 'fancy' tooltips

lib/render/codenote.php, public/codenotes.php, public/gameInfo.php
Adds a "Code Notes" link to the "More Info" section of the game page. It is visible for users with Registered or higher permissions.
The link under "Dev (click to show)" is still present for people's muscle memory. Previously, it was the only way to access the page. The page also did not display notes for anyone with permissions below Junior Developer.
I've also added a disclaimer to the Code Notes page indicating that our addresses may not map directly to hardware addresses, as the desire behind making these pages more accessible was for sharing the information with the preservation and modding communities.
The disclaimer does not show up on other pages that list the Code Notes (like the leaderboard editor).
=> allow code notes to be accessed by registered users

public/linkedhashes.php
Adds a disclaimer that RetroAchievements hashes are not whole file, and links to the doc page describing the per-system hashes.
Also adds a link to the official forum topic (if available) which might help identify the individual hashes.
=> add disclaimer to linked hashes page

lib/database/history.php
A user pointed out the total points are higher in the graph than what the user actually has, turns out it counts unofficial achievements in this total so adding a check to only count core achievements (which was already there just commented out).
=> Fix history graph total points to only count core achievements

lib/database/game.php, public/API/API_GetAchievementDistribution.php, public/gameInfo.php
Hi! I am the author of https://github.com/achievements-app/retroachievements-js and https://github.com/achievements-app/psn-api. I'm in the process of building a dashboard for my own portfolio site that is connected to all the gaming platforms I play on, and I've hit a snag during the development process.
Currently there is no good way for a RetroAchievements API user to calculate what the mastery % of a game is without manually scraping the site.
This PR:
* Adds an endpoint to retrieve the achievement distribution data from a given game ID.
On the current V1 site, this is represented via this graph:
After this PR is merged, this data can be retrieved via the _/API/API_GetAchievementDistribution.php_ public route.
=> feat(api): add API_GetAchievementDistribution.php

lib/util/string.php, lib/util/trigger.php
Fixes case where lowercase markers somehow get into achievement definition.
Previously the first condition was incorrect:
Also adds support for 0.80 features (i.e. floats and big endian values):
=> rewrite trigger parser to support mixed case markers

lib/constants.php, public/js/all.js
This is a small change in JS code to include "loading" attribute, which will greately decrease transfer, when visiting homepage. Active players widget includes a lot of images, and more players are active in games, the more data user needs to download to see main page (and, I guess, that's first contact with RA for a lot of new users).
Implementing this change will let browsers to not load those images, until user explicitly show the need for them (by scrolling down in active players list).
=> add lazy loading attribute to profile and game images outputted by JS

lib/database/leaderboard.php
When asking for the N leaderboard entries near a user, we do some math to calculate the actual offset to use in the query. It turns out that if N is larger than the number of items in the leaderboard and the user's rank is greater than N/2, then the calculated offset will be negative and no results will be returned.
See https://discord.com/channels/310192285306454017/645777658319208448/928763424039657532
The solution is simply to adjust the value to 0 if it ends up being less than 0.
=> prevent negative offset in lbinfo query

lib/database/activity.php, lib/render/achievement.php, lib/render/game.php, lib/render/leaderboard.php, lib/render/ticket.php, lib/render/user.php, lib/util/string.php
Addendum to #882 
For simple tooltips (i.e. for mastery badges), a different set of escaping rules needs to be applied. #882 caused apostrophes in game titles to appear escaped in the non-fancy tooltip: i.e. `Kirby\'s Dream Land`
This separates the logic for escaping fancy tooltips and basic tooltips and updates each of the pieces of code generating fancy tooltips to use the fancy tooltip escaping function.
=> use different escaping function for Tip()

public/gameInfo.php
Followup to #904 
Prevents showing the mature content warning on hub pages. In particular, the `[Central -Themes]` hub, although it will also prevent it from showing on the `[Theme - Mature]` hub as well.
Since the hub is just a collection of links to games, and the links can be posted in forums without flagging the warning, I believe this to be acceptable.
It's also reinforced by the warning itself: "This **GAME** may contain content not appropriate for all ages"
=> Don't show mature warning for hubs

lib/database/message.php, public/inbox.php
Adds an 'Outbox' link to the user's Inbox:
Clicking on that changes the view to messages sent by the user (instead of messages received by the user). In this mode, the ability to mark messages as read or unread, and the ability to create and delete messages are removed. Only the recipient of a message can mark it as read or delete it.
Because of the way the database is currently structured, if the recipient deletes the message, it also disappears from the sender's outbox. Additionally, there's no automatic correlation between messages and their responses.
Also fixes an issue where marking a previously read message as unread would not update the visual state of the message.
=> add ability to view sent messages if they haven't been deleted by the recipient

lib/render/game.php, public/gameInfo.php
Extracts Hubs from the Related list and turns them into metadata which will be displayed below the game screenshots.
If a Hub name starts with Meta, that's discarded. The remaining Hub name is split on the last hyphen, creating a label and value. Multiple items sharing a label are grouped together, otherwise labels are ordered as they would have been in the Related list.
The metadata items appearing above the screenshots are still populated from the game details (editable in the Dev section), but matching Hub items will be merged. If the label/values are not exact, they will be appended instead of merged:
=> separate hubs from similar games

lib/database/user.php, lib/render/comment.php, public/request/user/update.php, public/userInfo.php, src/ArticleType.php
Adds a new comment block within the admin tools on a user's page, allowing administrators to note things about the user, such as why they were untracked or banned. It also leverages the virtual audit functionality for tracking changes to settings managed by administrators.
=> add admin comment block to user page

lib/database/forum.php, lib/database/search.php, lib/render/forum.php, public/createtopic.php, public/forum.php, public/forumposthistory.php, public/index.php, public/rss-forum.xml.php, public/searchresults.php, public/viewforum.php
This removes information on topic information that the user does not have permission to access from Forum Activity, Forum Post History, Search results, and RSS feed.
It does not remove the Last Post info from this section below (my latest comment is in a locked Chat topic):
The Last Post (`LatestCommentID`) for each individual forum is stored in the `Forum` table, the query below uses that ID specifically when rendering this section. I'm not sure the best way to fix this without completely rewriting that query. It's an edge case given how infrequent a locked topic has the latest post of a given forum. This section also does not show what the topic or comment actual was. I can work on rewriting the query if that is preferred.
https://github.com/RetroAchievements/RAWeb/blob/c969d683c304d810f …
=> Remove Locked Topic Information

lib/database/leaderboard.php
The logic to prevent adding an "edit" comment when first uploading a new leaderboard was also not adding an "edit" comment when modifying a leaderboard whose author has been NULLed out for whatever reason.
=> fix edits not being logged for leaderboards with an unknown author

lib/util/trigger.php
Ensures operator and operand are not shown for all comparisons on conditions with scalable flags (AddSource, SubSource, AddAddress). Previously, it only handled "=0".
See https://discord.com/channels/310192285306454017/310195377993416714/953351104660373594
=> ignore all non-scaling operands for scalable flags

lib/database/game.php
Allows hashes to be linked during a rollout to simplify the development process.
Also changes the error message from `Cannot submit game title, ConsoleID is 0! What console is this for?` to `Cannot submit game title for unknown ConsoleID`, which seems to be leftover from this change: https://github.com/RetroAchievements/RAWeb/pull/468/files#diff-7c33f209aea8df531e4a87be81c561b821304c7ec6fa829cf70cb0fdd8fc33a7R1053
And changes the error message for non-devs from `The ROM you are trying to load is not in the database. Check official forum thread for details about versions of the game which are supported.` to `You must be a developer to perform this action! Please drop a message in the forums to apply.` to match the error they receive when they try to publish an achievement.
=> allow admins to link hashes to unsupported consoles

lib/database/game.php, public/gameInfo.php
Fixes an issue reported by Kinglink.
https://discord.com/channels/310192285306454017/453242743292952578/957568137761550388
Within `getGameMetadata`, the `NumDistinctPlayersCasual` and `NumDistinctPlayersHardcore` values were being derived as the maximum value for any given achievement within the set. The `gameInfo.php` page made a separate call to `getTotalUniquePlayers` to get the actual value.
I've modified `getGameMetadata` to make a separate query to fetch the correct values so they can be used in other places (like `API_GetGameExtended.php`), and removed the separate call to `getTotalUniquePlayers` in `gameInfo.php`.
I've also modified `getAchievementDistribution` to accept an optional parameter that is the number of achievements to prevent an extra call to `getGameMetadata` just to …
=> use secondary query to calculate unique players in getGameMetadata

lib/render/user.php, public/reorderSiteAwards.php
If any section would be empty it's not displayed. 
The only caveat is if all three sections would be empty, an empty Game Awards section is displayed.
The reorder site awards page is similarly split up:
=> split Site Awards into Game/Event/Site Awards

.gitignore, public/API/API_GetAchievementOfTheWeek.php, public/API/API_GetAchievementUnlocks.php, public/API/API_GetFeed.php, public/API/API_GetGameList.php, public/API/API_GetGameRankAndScore.php, public/API/API_GetTicketData.php, tests/http/api-connect.http, tests/http/api-web.http, tests/http/http-client.env.json
... to quickly test for PHP 8 compatibility.
I think those are for JetBrains IDEs only, at least I could not find any reference as to whether those can be run by another HTTP client. Added curl notations for reference.
Includes all of Web API but only a few Connect API requests as the latter was acceptance tested with an actual client (latest RALibretro).
=> Add HTTP tests for Web & Connect APIs

.hooks/post-merge, README.md, lib/render/game.php, public/awardedList.php, public/forumposthistory.php, public/history.php, public/historyexamine.php, public/leaderboardList.php, public/userInfo.php, resources/docker/php/Dockerfile
Run PHP 7.4 code without any errors or warning in PHP 8.
Will be followed up with full PHP 8 upgrade (using rector, see https://github.com/RetroAchievements/RAWeb/pull/911) as soon as server has been configured accordingly (php-fpm pool, socket).
=> PHP 8 compatibility

lib/database/achievement.php
Newly created achievements have a retro ratio of 0. As such, they appear "easier" than all other achievements. There are currently around 5300 achievements with a retro ratio of 0. This filters those out so actual easy achievements appear in the "Easy Achievements" page. Unfortunately, there are around 7000 achievements with a retro ratio of 1, so identifying the "easiest" achievements is still far from perfect.
A secondary sort was also added to subclassify items within the same retro ratio by their point value. i.e. a 1 point achievement with a retro ratio of 2 is harder than a 2 point achievement with a retro ratio of 2.
=> ignore achievements with no retro ratio when determining easiest achievements

lib/render/user.php
Avoids greedily downloading images for the 90% of the games in the Completion List that are not visible unless the user scrolls
=> lazy load images for completion list

public/achievementInfo.php, public/gameInfo.php, public/js/all.js, public/largechat.php, public/leaderboardList.php, public/leaderboardinfo.php, public/userInfo.php, public/viewtopic.php
Instead of relying on onready javascript to hide them by name.
Prevents collapsible sections from being rendered/visible/open while the page is loading. For most pages, this just causes the section to flash as briefly visible, but for larger pages (games with lots of achievements, user pages), the collapsible sections remain open for a second or more while the rest of the page loads.
=> start with collapsible sections collapsed

lib/render/user.php, public/reorderSiteAwards.php
Leverages the Display Order property of the first item in each group to determine which order to display the groups on a user's profile page.
i.e. If your first Game Award Display Order is lower than your first Event Award display order, the Game Award section will be displayed first. If the first Event Award Display Order is lower, it will be displayed first. Only the first item in each group matters for intergroup interactions. Items within a group will be ordered by their display order within the group.
The reorder page still has a fixed order of: Game Awards, Event Awards, and Site Awards.
This also moves any Event Awards in the "[Central - Developer Events]" or "[Dev Events - *]" hubs into the Site Awards group.
=> allow award groups to be ordered

lib/database/game.php, public/gameList.php
The All Games list and any list where "games without achievements" are present will still be paginated.
A page selector replaces the "first/prev/next/last" links.
Also fixes the All Games list to not group items by console as the grouping was removed when the pagination was added.
=> remove pagination for per-console games with achievements lists

public/test/shortcode.php, src/Shortcode/Shortcode.php
**Before**
**After**
_Discord Markdown_
_JetBrains Markdown_
=> Fix shortcode parsed auto-link URLs including trailing sentence-punctuation characters

public/request/auth/update-password.php, public/resetPassword.php
Fixes #845 by redirecting to the `resetPassword.php` with the same `$user` and `$passResetToken` parameters along with an error message to indicate it failed.
Also displays a message when changed successfully and changed the redirect to `resetPassword.php` for now since the auto-login portion of the code doesn't seem to be working properly anyways.
Old behavior was redirecting to the homepage on success and failure with this message
=> Display error on failed password resets from reset url

lib/database/rating.php, public/css/styles.css, public/gameInfo.php, public/request/game/rating.php
Adds a tooltip to the game rating widget showing a distribution of the user-submitted ratings, and highlighting the user's rating.
When the user changes their rating, the user's rating portion of the tooltip is updated, but the distribution is not.
The rating will be hidden until there are at least five ratings submitted:
When a game has no ratings:
=> add tooltip to game rating

lib/util/upload.php, public/controlpanel.php, public/doupload.php, public/request/user/update-avatar.php
Fixes an issue when uploading a file where the extension (implied mime type) didn't match the contents. When uploading game badges, it would return a 500 Internal Error error. On the user profile, it would silently fail (it was probably still 500ing in the ajax request).
=> return failure messages when provided with an invalid file

lib/render/leaderboard.php, public/request/user/update-subscription.php, src/SubscriptionSubjectType.php
This fixes the issue where the `(subscribe)` link was not changing to `(unsubcribe)` after subscribing.
#911 changed several `switch` statements to `match` expressions. It turns out that `switch` will coerce the data type, but `match` will not. This led to a situation where a variable that was sanitized for SQL got converted to a string and was no longer being matched by the `match` clauses.
I went through and audited all of the `match` clauses added in #911 and made sure the variable type was well known at the point where the `match` is evaluated. It turns out there was only a couple questionable cases, which I have addressed in this PR.
=> ensure variable type is specified for match clauses

lib/database/game.php, public/API/API_GetGameList.php
Previous response:
```
{
"Title":"Ninja Golf",
"ID":"13352",
"ConsoleID":"51",
"ImageIcon":"\/Images\/019885.png",
"ConsoleName":"Atari 7800"
}
```
New response:
```
{
"Title":"Ninja Golf",
"ID":"13352",
"ConsoleID":"51",
"ConsoleName":"Atari 7800",
"ImageIcon":"\/Images\/019885.png",
"NumAchievements":31,
"NumLeaderboards":0,
"Points":485,
"Hashes":["bb551483d114dcc5bae7aaa892ee856a","220121f771fc4b98cef97dc040e8d378"]
}
```
Note that the `"Hashes"` subdata is only available if `h=1` is passed to the API. `f=1` will limit the response to games with achievements (existing behavior).
The new fields are returns as integers where appropriate. I did not "fix" the previous fields that should have been returned as integers as that's a potentially breaking change.
=> add NumAchievements,NumLeaderboards,Points, and Hashes to API_GetGameList

lib/database/achievement.php, lib/database/game.php
Checking the RR calculation I noticed it was not calculating total users correctly and was instead using the total earners of the achievement with the most earns. You can see an example below
Current
1/2 and 2/2
Fixed
1/10 and 2/10
The other fix is removing softcore users from the calculation, it now counts the total hardcore users that earned the achievements as well as uses the total unique hardcore players for the total to check against. Example below with 34 hardcore users and 37 total
Current
26/37
Fixed
1/34
=> Fix RR total players used for calc and remove softcore users from total

lib/database/achievement.php, public/gameInfo.php, public/ticketmanager.php
Fix related achievements referencing tickets from other games as seen below
As well as game page displaying 0 open tickets when there are some
Also tweaking RR calculation to include games with 0 earns
=> Ticket-Manager | RR hotfix

src/TicketFilters.php
Fixes an issue introduced by #970 where other tickets for this achievement would not show up when viewing a ticket.
=> exclude ResolvedByNonAuthor from All filter

lib/database/achievement.php, lib/database/game.php
Noticed that the displayed won by total users was also counting unique users from unofficial which in cases of re-authoring can cause weird affects like seen in https://retroachievements.org/game/7015 which has 6 total users from the new achievements.
This shouldn't make much difference for most games but the few that get re-authored completely and do not do any transferring of earns are currently showing overinflated user totals as well as inflated RR. Has a very minor impact on some popular games with unofficial achievements from the samples I've checked.
=> Fix total players displayed and used in RR calc from using Unofficial

lib/database/activity.php, lib/database/game.php, lib/database/ticket.php, lib/database/user.php, lib/render/layout.php, public/request/comment/create.php, public/ticketmanager.php, public/userInfo.php, src/TicketFilters.php, src/TicketState.php
Adds a new state to tickets: **Request** (I'm open to a better name if anyone has any good suggestions).
A developer can use this state to put the ticket back in the hands of the reporter to collect additional information.
For example, I receive a ticket for an achievement and I get a bright red notification in my user summary area:
Upon viewing the ticket, I can contact the user asking for more information, but that happens through direct messages, which aren't captured in the ticket itself.
Instead, I put a comment in the ticket, hoping the user sees it. 
At this point, there's not much more I can do with the ticket until the user responds (if they ever respond). The problem is the user may not have seen the email indicating the ticket was updated, so they won't know to respond.
If the …
=> add Request ticket state

public/gameInfo.php, public/request/game/update.php
Updates the Remove Similar Games dropdown to be multiselect and resizable. Allowing for easy removal of multiple entries at once.
=> Allow Multiple Similar Games To Be Removed at Once

public/individualdevstats.php
Fixes cases of developer stat page breaking at the hardest achievement which prevents it from displaying the rest of the info when the developers first achievement (in core) is a 0 pointer.
=> Fix broken dev page when first achievement is 0 pointer

lib/database/achievement.php
`$title` and `$description` are sanitized by `sanitize_sql_inputs()` which adds in escape characters before things like `'` and `"` which was triggering the wording updated portion of edit messages. Created a raw copy of these variables before sanitization to use for the comparison.
=> Fix sanitized title/descriptions from falsely showing differences

public/API/API_GetGameList.php
https://discord.com/channels/310192285306454017/645777658319208448/979739377007726613
Note: this value is actually `max(Achievements.DateModified)` and doesn't truly reflect the last modification to the Game record itself. However, it is consistent with the date shown on the games list as it's using the same query to build the data set.
Value will be null if the game has no achievements.
```
{"Title":"Donkey Kong","ID":"13354","ConsoleID":"51","ConsoleName":"Atari 7800","ImageIcon":"\/Images\/024839.png",
"NumAchievements":23,"NumLeaderboards":3,"Points":348,"DateModified":"2020-04-16 15:25:27"}
```
```
{"Title":"Impossible Mission","ID":"14264","ConsoleID":"51","ConsoleName":"Atari 7800","ImageIcon":"\/Images\/000001.png",
"NumAchievements":0,"NumLeaderboards":0,"Points":0,"DateModified": …
```
=> return DateModified in API_GetGameList query

lib/database/player-achievement.php
Fixes https://github.com/libretro/RetroArch/issues/14041
When the server receives a request to unlock an achievement the player has already unlocked, it responds with an error. The client is looking for a specific substring to indicate that the error isn't actually something that needs to be reported, and despite having a comment suggesting that the string should not be changed, it was. This modifies the string to reflect the intent of the change without breaking the client substring matching.
=> restore messaging to prevent client error

lib/render/game.php
For example, on a game associated to the `[Hacks - EarthBound]` hub:
| Publisher Value | Before | After |
| ----- | ----- | ----- |
| | **EarthBound** | **Hack - EarthBound** |
| Hack - EarthBound | **Hack - EarthBound** | **Hack - EarthBound** |
| Hacks - EarthBound | Hacks - EarthBound, **Hack - EarthBound** | **Hack - EarthBound** |
| EarthBound | **EarthBound** | EarthBound, **Hack - EarthBound** |
(bold items represent links to the hub)
https://discord.com/channels/310192285306454017/888607146290343976/985167615217500200
=> improve merging of Hacks hubs into Publisher field

lib/database/forum.php, lib/render/error.php, public/forum.php, public/viewforum.php
The page it directs to requires admin permission. Clicking the link as a non-admin redirects back to the forum list, where it was supposed to display an "Unknown forum" error. I've also corrected that.
https://discord.com/channels/310192285306454017/493200466222776342/991419417579761704
=> don't show authorisation message for non-admins

.env.example, database/20180212_170235_RA_Template.sql, docker-compose.yml
```
extra_hosts:
- host.docker.internal:host-gateway
```
lines above added to docker-compose.yml, because **host.docker.internal** not supporting in Docker for Linux out of box (this connection from container to local machine needs for **xDebug**)
https://medium.com/@TimvanBaarsen/how-to-connect-to-the-docker-host-from-inside-a-docker-container-112b4c71bc66
=> Small fixes for set up project

public/controlpanel.php, public/request/user/reset-achievements.php
Revert request responses to be strings, not header redirects.
This area still has some logic issues - I don't want to take care of those in this PR though as i rewrote a lot of that in the v2 branch already.
=> Fix progress reset response

public/request/achievement/update-image.php, public/userInfo.php
Uploading badges through the site was sending emails for changes even if you were the author (thanks for reporting TeddyWestside)
Fixes Recent Progress to show softcore and hardcore progress similar to the history view graph update (thanks for reporting p8lg6xtb and Jamiras)
=> Fix emails for site badge updates and Recent Progress graph for softcore

lib/render/game.php, public/gameInfo.php
Relocating the `sanitize_outputs` in https://github.com/RetroAchievements/RAWeb/commit/76e5ef9066e1de281d0e487bca22e6c3cd529951#diff-66930c10e82ee4f8d7cf1fd91cb8a68f42f751f9e653b776fbca42c44603cf56R625-R630 caused the value to become escaped, and then it doesn't match the hub name, resulting in
Since the previous location of `sanitize_outputs` was before they were being initialized, it doesn't seem like it's necessary. I've removed it, and things appear to be working. The `attribute_escape` is handling the sanitization when it becomes necessary.
=> Fix hub matching for values containing ampersands

database/20220810_000000_Add_UserAccount_SoftcorePoints_Key.sql, lib/database/player-rank.php, lib/database/user.php, lib/render/leaderboard.php, lib/render/user.php, public/globalRanking.php, public/userInfo.php, src/RankType.php
Allows players who primarily (or exclusively) use softcore mode to better track their own progress compared to other users.
_NOTE: Softcore removes all restrictions on the emulators. In addition to save states and rewind, you can use things like game genie codes, edit memory, disable layers to see through fog, view tile buffers to see stuff offscreen, or even have a TAS script play the whole game for you. Having a softcore leaderboard requires user to acknowledge that other players on that leaderboard could be using those features without any repercussions. The admin team has already stated that they will not investigate cheat reports submitted against softcore unlocks. So while it might be nice to see yourself go up a rank every few weeks, the rank itself loses its meaning. …
=> add softcore leaderboard rankings

public/css/styles.css
This is a simple amend for #1070. One of the two counters used to overflow below (at least in Windows) in case there were too many digits to display:
Fixed by decreasing `<h3>`'s size on the right container (which has a rather positive side-effect since those were too big anyway).  Now it should hold up to 6 digits total.
=> Fix game award counters overflow

lib/render/set-claim.php, public/index.php, src/ClaimFilters.php
Changes out the New Achievements component with Finished Set Claims component
Old
New
Reasoning being that a majority of the time New Achievements essentially shows that a single game got a set created. Changing to show newly finished sets/revisions show more useful details and if you want to see specific new achievements you will likely be checking the Achievement List page anyways which shows them all.
Finished Claims "more..." link will take you to the Claim List page filtered on Complete statuses.
=> Finished claims widget

lib/render/game.php, public/gameInfo.php, public/userInfo.php
Game progress no longer reports values over 100% (mastering a game is no longer 200%)
Reported progress is now the maximum of (hardcore progress/softcore progress), and if the game has 100% hardcore completion, it's reported as Mastered:
If the user has both hardcore and softcore unlocks, the bar gains a tooltip indicating the hardcore progress. The reported progress will be for the softcore progress.
The change affects the recently played games on the user's profile page, and the bar shown on individual game pages (showing tooltip):
=> update max game progress to 100%

lib/render/leaderboard.php
Fixes the retro points calculation for daily/weekly views which was including softcore unlocks effectively doubling the total in some cases.
=> Fix daily/weekly retro points calculation

public/historyexamine.php
Changes made to support the hardcore/softcore split broke the player history page such that it would sometimes show achievements earned in hardcore as softcore. This is due to the way the data is stored in the database as two separate unlocks (one for the hardcode version and one for the softcore version). When both are generated at the same time, they have the same timestamp and the query that retrieves them may not return them in a deterministic order. If the softcore unlock was returned after the hardcore unlock, the unlock would appear as softcore in the list.
The code prior to the change populated the list with softcore unlocks first, then looped through the list a second time overwriting the softcore unlocks with the hardcore unlock data. This PR keeps the simplified single-pass …
=> fix hardcore indicator on player history page

public/friends.php
`array_search` returns `0` when it matches the first element in the array, or `false` if no elements were found. The boolean check `!array_search()` returns true for both. I've updated the logic to explicitly look for `false`.
=> fix first mutual follower showing follow link

public/gameInfo.php
Also separates earnings by hardcore/softcore and reduces the intensity and frequency of the grid lines.
Several examples (before and after):
A typical game:
A game with a lot of achievements:
A game with just a few achievements:
A meme game:
A recently released game:
=> change Achievement Distribution graph to bar chart

public/achievementInfo.php
=> fix resetting progress from achievement page

lib/render/game.php
https://discord.com/channels/310192285306454017/962817919698501702/1020473949571788851
=> fix Mastered being displayed when 99.5+% of achievements earned, but not 100%

lib/database/user-activity.php, lib/render/user.php, public/js/activePlayersBootstrap.js, public/js/all.js, public/request/user/list-currently-online.php, resources/css/card.css
before:
after:
NOTE: I've chosen to go with a simpler tooltip for the user (to match the game tooltip) as the API that refreshes the active widget doesn't provide all of the information available in the normal user tooltip:
=> update active players tooltips to match new style

lib/database/achievement.php, resources/helpers/helpers.php
Eliminates the need for the client to construct the URL, and allows us to change the URL without breaking the clients. 
The recent move to the new framework had some issues around migrating resources from `i.retroachievements.org` to `media.retroachievements.org` and others related to accessing them directly through `retroachievements.org`.
=> also return full URLs for game images and achievement badges

public/individualdevstats.php
Prevents "Attempt to read property "ID" on null" exception accessing dev stats for a deleted user.
An alternate solution would be to modify `getCodeNoteCounts` to allow retrieving data for deleted accounts.
```
$user = User::withTrashed()->firstWhere('User', $username);
```
But the only link being generated to the individualdevstats page is from the user page, which returns 404 for deleted users, so I've mimicked that behavior for the dev stats page.
=> return 404 for dev stats of deleted user

lib/database/user.php
Fixes "Trying to access array offset on value of type null" exception (returned as a 500 error) when unlocking an achievement associated to an author that doesn't have an entry in the UserAccounts table.
=> prevent 500 response when attributed developer was hard deleted

lib/database/user-activity.php
fixes "foreach() argument must be of type array|object, null given" in API_GetUserRecentlyPlayedGames when the queried user's only play history is for invalid game IDs. 
For example, `JB`s only played game (`Activity.data WHERE activitytype=3`) was game 0.
=> don't return null records for invalid game IDs

public/wiki-edit-redirect.php
Fixes `Undefined array key "HTTP_REFERER"`
=> Handle missing referers in wiki edit redirects

app/Legacy/Models/Achievement.php, app/Support/Shortcode/Shortcode.php, lib/database/player-rank.php, lib/database/user.php, lib/render/achievement.php, lib/render/game.php, lib/render/leaderboard.php, lib/render/ticket.php, lib/render/user.php, lib/util/string.php, public/gameInfo.php, public/js/all.js, public/request/card.php, public/test/cards.php, public/test/tooltip.php, public/vendor/wz_tooltip.js, resources/css/card.css, resources/css/tooltip.css, src/Ticket.php
Includes multiple layers of caching.
Moves rendering of cards (user, achievement, game, ticket) to a dedicated function that can be invoked asynchronously in a new card render request endpoint.
- Load tooltip cards lazily; best way to improve performance is to not load nor render data that is not needed immediately
- Cache (local/javascript) card responses per page visit
- Cache (server/redis) user rank data
User rank cache is not invalidated but can be. Reflecting the correct rank in the card is not important enough to find all valid invalidation opportunities yet. It would be if cache TTL was way above 15 minutes.
=> Lazily load tooltip cards

public/historyexamine.php
fixes `date(): Argument #2 ($timestamp) must be of type ?int, string given` error when accessing the historyexamine page with a non-numeric timestamp
=> prevent exception accessing history with an invalid date

public/individualdevstats.php
If the developer has less than 100 unlocks and the first unlock was softcore, the check to see if a hardcore unlock exists to be merged with the softcore unlock would generate an array bounds exception.
=> fix exception viewing dev stats for new developer where first unlock was softcore

lib/render/user.php
Prevents showing joystick on:
* unclaimed games in the most requested games list 
* leaderboards with no entries on games pages
* resolver for unresolved tickets
=> don't show joystick for 'null' user

public/managehashes.php
Updates comment to match new format.
Current code puts the date in the left most column
This update will put the date in the same column as the comment with the same formatting. So reloading the page shows no differences.
=> Update update/unlink hash comments to match current format

lib/database/ticket.php
eliminates two expensive queries when viewing achievement info pages:
* `getUserActivityRange` scans the Activity table for the user's first and last login timestamps
* `getRecentlyPlayedGames` scans the Activity table for the user's last new session timestamp
=> cache ability to create tickets

lib/database/user-activity.php
eliminates another expensive query against the Activity table by caching the list of recently played games for the user's profile page. expired whenever a new session is started.
=> cache recently played games

lib/database/achievement.php, lib/database/player-achievement.php, lib/database/player-game.php, lib/database/user-activity.php, public/API/API_GetGameRankAndScore.php, public/gameInfo.php, public/request/achievement/update-flag.php
eliminates an expensive query on the game page. only cached if there are at least 10 masteries (full list), minimizing the expiration logic to: new mastery, achievement promoted/demoted, and reset achievement.
NOTE: the current user is no longer shown in the mastery list if they are untracked. I believe this is consistent with the messaging around being untracked:
> An untracked account **doesn't appear in the global ranking**, its activities do not appear in the feed, it's **no longer listed among all other earners of each achievement** (on the achievement page) and their entries on specific leaderboards will not be publicly visible.
=> cache top achievers per game

public/reportissue.php
Fixes `getExistingTicketID(): Argument #1 ($user) must be of type App\Legacy\Models\User, null given` error
=> prevent exception trying to create a ticket when not logged in

app/Support/Shortcode/Shortcode.php
For example, if a forum linked to `[game=111]` and later in the same forum page, there was a link to `[ach=111]`, the second link would be incorrect.
The internal storage for resolved linked was storing both in a bucket for "game:111". The achievement link should have gone into an "achievement:111" bucket.
=> fix display issue when embedding game and achievement with same ID in same page

lib/database/set-request.php, public/setRequestList.php
As mentioned in https://retroachievements.org/viewtopic.php?t=18451.
I've taken the opportunity to move the "Set Exists" moniker into the Claimed By column, whereas it was previously appended to the game.
Before:
After:
Also modifies the `getUserRequestList` function to return how many achievements each requested set has to avoid doing that query twice for each item: once for determining how many requests the user has consumed, and once for determining if the item should be visible on the page.
=> restore Set Exists marker on All User Set Requests page

lib/database/search.php, public/request/search.php, public/searchresults.php, src/SearchType.php
Implements #1064
Adds a type selector to the search results page:
When searching by specific types, items are sorted:
* Achievements, Games, and Users alphabetically
* Forum posts and comments by most recent
NOTE: The subquery sorts appear to be ignored when the subqueries are unioned together for the Everything search. This is consistent with the existing behavior.
I've also made the following changes:
* Replace "Previous 50"/"Next 50" with Paginator widget
* If forum post or comment is less than 64 characters long, don't wrap it in ellipsis
* Don't perform query if search term is a single character
* Don't match "audit" comments (comments associated to Server user)
* Don't match deleted users or comments on their walls
* Use same search queries for autocomplete and search results page …
=> Add type filter to search page

lib/database/player-game.php, lib/database/site-award.php, lib/database/user-activity.php
When unlocking a hardcore achievement, the code would only check to see if the hardcore badge should be awarded. If the user had some non-hardcore unlocks, and the last achievement for the set was unlocked in hardcore mode, it would not award the completion badge.
Also eliminated some queries fetching unused achievement/game data when creating Activity records for unlocking achievements and completing/mastering games.
=> fix completion badge not being awarded if last unlock was hardcore

lib/database/achievement.php, lib/database/set-claim.php, public/achievementInfo.php, public/achievementinspector.php, public/gameInfo.php, public/request/achievement/update-base.php, public/request/achievement/update-display-order.php, public/request/achievement/update-image.php, public/request/game/update-image.php, public/request/game/update-meta.php, public/request/game/update-rich-presence.php
This gives Junior Developers a few more permissions if they have an active primary new set claim, allowing them to do the following:
- Update game page information (Developer, Publisher, Genre, & First Released)
- Update game page images (Icon, Title, In-Game, Boxart)
- Update Rich Presence script
- Update achievement ordering
This also allows Junior Developers to update their achievement titles, descriptions, points, & badges via site or emulator without requiring the achievement to be demoted first.
=> Expand Junior Developer Permissions

lib/util/trigger.php, public/leaderboardinfo.php
implements #1215 
Adds collapsible sections for start/cancel/submit/value triggers to the leaderboard page (not the manage leaderboards page). Includes support for translating legacy value definitions to Measured strings.
=> add explain blocks for leaderboards

public/rss-forum.xml.php, public/rss-newachievements.xml.php, public/rss-news.xml.php
This Pull Request introduces three changes to RSS feeds:
* fix date in News RSS Channel – it had wrong variable, so every item in the feed was showing the same date (actual one)
* strip HTML tags from title and description for News RSS Channel – with encoded content it was difficult to read it
* add "guid" for all available RSS feeds – there was no "guid", so items were distinguished by other means in RSS readers. Now with unique "guid" for each item, it will be easier for readers be sure, which items were read.
In case of the last point, this form of "guid" is my proposition. News doesn't have their permalinks, so it has to be some kind of other string here. I was thinking about going with URI tags (according to [RFC 4151](https://www.rfc-editor.org/rfc/rfc4151.html)), which are …
=> Fix RSS feeds date, strip HTML tags, add guid

public/ticketmanager.php
Allows quick access to the list of hashes for the game in case the user can't see the tooltip (mobile), or if the user is just curious which other hashes are available.
Tooltip still appears on hover.
=> make hash link redirect to hash page

lib/util/database.php
To help track down errors like `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-8, 15' at line 6`
Alternately, we could just throw the exception in production (see line 74) and let the framework log it normally.
=> include calling function location in silenced sql failure

lib/database/search.php, public/request/search.php, public/searchresults.php, src/SearchType.php
implements #1252 
comments as a searchable subtype has been replaced with all of the relevant comment types (filtered by permission level):
=> split comment search type into subtypes

lib/render/avatar.php, public/js/activePlayersBootstrap.js, public/js/all.js
Requires the cursor to be over a image/link for 200ms before fetching the tooltip.
Should minimize the occurrences of the 429 error when scrolling through a page or just moving the cursor around.
=> only fetch tooltip if hovering

lib/database/leaderboard.php, lib/database/user-activity.php, lib/render/code-note.php, lib/render/comment.php, public/achievementInfo.php, public/achievementinspector.php, public/codenotes.php, public/comments.php, public/gameInfo.php, public/leaderboardList.php, public/leaderboardinfo.php, public/linkedhashes.php, public/manageclaims.php, public/managehashes.php, public/ticketmanager.php, public/userInfo.php
Implements #1056 
If a comment block has more than 20 items, the "Comments:" header will change to "Recent Comments (All XXX)" where the XXX is the total number of comments and the "All XXX" is a link to a paginated view of the comments.
Also added nav bars to code notes, linked hashes, and manage claims pages.
=> add subpage for additional comments

database/seeders/ForumTableSeeder.php
Simple correction. The old text wrongly referred to Portuguese nationality (instead of as a language) and was grammatically incorrect.
Old:
```
'title' => 'Portuguese players!',
'description' => 'The section for all our Portuguese friends for talking and having fun!',
```
New:
```
'title' => 'RA in Portuguese!',
'description' => 'Where all our Lusophone friends can talk and have fun!',
```
=> Improve title/description for Portuguese-speaking forum

lib/render/forum.php, resources/css/typography.css
This PR resolves #1224 issue.
At first, I just added one of the Tailwind's utility class, "break-all", to div containing post content for forum activity preview.
The problem with it, though, is that normal words are also broken this way. I was searching for other way of breaking words, and got a solution, which breaks words only when it's necessary (word is longer than whole line, otherwise just wrap to the next line).
```
overflow-wrap: anywhere;
word-break: normal;
```
Wanted to get this effect with Tailwind's classes (https://tailwindcss.com/docs/word-break), but none of them provide this combo: `break-normal` doesn't breakes long words, `break-words` as well, `break-all` breakes also normal words.
I felt, that aforementioned combo works good, because it wraps words not fit into the …
=> Change way of breaking text in forum post content preview

public/ticketmanager.php
fixes #1266 
caused by #1247. The fix to prevent dereferencing a null array was causing related items to be looked up for the ticket ID, not the achievement ID.
=> fix identification of other tickets for same achievement

public/js/all.js
caused by #1254. The redundant ID field was removed from the response, but the javascript was still expecting it.
=> fix compare-to-user autocomplete

lib/database/ticket.php, public/ticketmanager.php, src/TicketFilters.php
Separates tickets that don't specify an emulator (most likely submitted from the standalones) from those associated to emulators that aren't `RA*` or `RetroArch`.
Previously everything that wasn't `RA*` or `RetroArch` was tossed into the Unknown bucket. Now Unknown only matches those items where an emulator is not specified.
=> add TicketFilters::EmulatorOther

lib/render/layout.php
Fixes error:
> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-8, 15' at line 6 at /srv/web/releases/2022-12-22T225652-2.4.1-ae5bf5e/lib/database/forum.php:199
If the user arbitrarily jumps to an offset by manually modifying the URL (i.e. specifying `o=100`), the offset for the next/previous page is adjusted by the page size. If the offset is in the middle of the page, there can be a Prev link on the first page, and clicking that results in a negative offset, generating the reported error. This ensures the first page won't have a Prev link, but does not prevent the user from entering a negative offset manually.
=> adjust page links to multiple of page size

public/request/user/update-avatar.php
prevents logging of the following errors (while still reporting them to the client):
> Invalid file type {"userId":354831,"exception":"[object] (Exception(code: 0): Invalid file type at /srv/web/releases/2022-12-22T225652-2.4.1-ae5bf5e/lib/util/media.php:36)
>imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error: Not a JPEG file: starts with 0x52 0x49 {"userId":352525,"exception":"[object] (ErrorException(code: 0): imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error: Not a JPEG file: starts with 0x52 0x49 at /srv/web/releases/2022-12-22T225652-2.4.1-ae5bf5e/lib/util/media.php:53)
> imagecreatefrompng(): &quot;/tmp/data-url3Fhk3J&quot; is not a valid PNG file {"userId":354508,"exception":"[object] (ErrorException(code: 0): imagecreatefrompng(): …
=> explicitly return error to prevent logging exception

lib/database/achievement-points.php
fixes #1284 
The query was filtering on `HardcoreMode=1 or HardcoreMode=NULL`. If only softcore unlocks exist, HardcoreMode would be 0 and the row would be filtered out. Changing the `COUNT(*)` to `COUNT(aw.HardcoreMode)` and removing the NULL filter allows it to return a count of 0 for both the NULL case (no unlocks) and the 0 case (only softcore unlocks).
=> ensure achievements with no hardcore earned get their true ratio recalculated

deploy/deploy.sh, lib/render/game.php, lib/render/set-claim.php, public/achievementList.php, public/gameList.php
Introducing the wrapper for game titles makes them break between icon and label when too long:
Move icons to a separate column like in other places:
Includes minor cleanups:
- Docblocks
- Only keep the last release instead of five
=> Fix claim tables on front page & cleanup

lib/render/site-award.php, resources/css/achievement-set.css, resources/css/award-count.css, resources/css/progress.css
- Remove progress icon outline (doesn't work on some apple devices)
- Align award counters via flex instead of float (caused issues on small screens)
- Align awards to the left as "5 per line" doesn't apply on small screens
=> Fix minor frontend issues

app_legacy/Helpers/render/game.php, app_legacy/Helpers/render/site-award.php, app_legacy/Helpers/render/user.php, public/gameInfo.php, resources/css/award-count.css, resources/css/progress.css, tailwind.config.js
Simplify progress CSS & tailwind class usage. Same result.
Revert the `.progress` container; a relative container is not needed when aligning progress bar a completion icon using flex. The global and player variants only set the width which can be replaced by reusable utility classes.
Progress bar labels can be aligned using utility classes, too, where needed.
All of this will be moved to a normalized view component eventually so we do not have to maintain it in three different places.
Fix tailwind content paths config.
=> Fix progress bar completion icon alignment

app_legacy/Helpers/render/game.php, resources/css/achievement-set.css, resources/css/tag.css
A more unified, visually consistent inverted version of labels that does not have too many variants and uses existing color variables.
I know you wanted to make a distinction between types, @EmoonX, but i feel it's still to early to introduce such changes before the tag system is in place. Tags will have to then emulate every behaviour that's added until then. Hence why i wanted those colors to be gone previously; to keep it simple for now and make the transition easier.
=> Simplify labels

app_legacy/Helpers/database/player-achievement.php, app_legacy/Platform/AppServiceProvider.php, app_legacy/Platform/Commands/UpdatePlayerMasteries.php
Supports #658 
When resetting a published (core) achievement, or an entire achievement set, the associated mastery/completion badge will now be revoked.
Additionally, a manual upgrade command has been added that will audit existing mastery badges. This can be run after deployment. If a user has a mastery badge for a game and _no_ achievements unlocked for that game, and the game still has published achievements, then the badge will be revoked. If the game has no published achievements, it is assumed the set has been demoted for repairs. If the user has at least one achievement unlocked for the game, it is assumed that a revision occurred and the badge will not be revoked. If the user wishes to revoke the badge themselves, they may reset any or all achievements for the game.
=> Revoke mastery badge when resetting achievements for a set

app_legacy/Helpers/render/game.php, app_legacy/Helpers/render/site-award.php
Updates the tooltips on the game awards to use the game card.
Before:
After:
This does affect the event awards as they're game entries. It does not affect the contribution or patreon badges.
=> use cards for game award tooltips

public/gameInfo.php
The new progress widget really stands out on game pages with no achievements compared to before.
Current:
Before:
But there's no reason for it to be there. The Set Request widget really should just replace it. So that's what I did.
After:
=> hide game progress if game has no achievements

public/codenotes.php, public/leaderboardList.php, public/linkedhashes.php, public/manageclaims.php, public/managehashes.php
Affects the following game subpages:
* Code Notes
* Manage Leaderboards
* Linked Hashes
* Manage Hashes
* Manage Claims
Helps to differentiate subpages when creating bookmarks and linking in Discord
=> include game name in page titles for game subpages

resources/css/nav.css, resources/css/theme.css, resources/css/tooltip.css
Add some depth to main menu dropdowns and tooltips:
=> Add box shadows to main menu dropdowns and tooltips

app_legacy/Helpers/database/player-game.php, app_legacy/Helpers/database/user-activity.php
Fixes an issue where a player would not be awarded a mastery badge if they had recently unlocked the achievement with the same ID as the game they mastered.
i.e. The mastery badge for game 1234 would not be awarded if the user unlocked achievement 1234 within an hour prior to mastering game 1234.
=> decouple site award from recent activity

app_legacy/Helpers/render/game.php, public/achievementInfo.php, public/codenotes.php, public/gameInfo.php, public/gamecompare.php, public/leaderboardList.php, public/leaderboardinfo.php, public/linkedhashes.php, public/manageclaims.php, public/managehashes.php, public/reportissue.php, public/usergameactivity.php
Since we're in the process of semantically separating tags from the actual game titles, and since there have been concerns about the visual clutter in breadcrumbs (either in the old or new formats), here are some changes I've implemented:
- Category tags won't be displayed (in general) when a game has one. 99.9% of the time its title is already unique for a given console, and the full tagged title usually appears right below in most pages anyway
- In the really rare case of a pair of games sharing the same base title, the category tag for the derived one is shown -- to avoid ambiguity. Unless I'm mistaken about my searches, this one below is currently the sole actual instance in... _5792_ sets
- Subsets get more interesting. I've separated the main title and subset tag into different …
=> Simplify breadcrumbs and separate main/subset links

app_legacy/Helpers/render/achievement.php, public/achievementInfo.php, public/reportissue.php, public/ticketmanager.php, resources/css/legacy.css, resources/css/tag.css, resources/css/typography.css
Self-explanatory. Should be able to be eventually expanded to other kinds of achievement tags.
=> Render `[m]` in achievement titles as a tag

app_legacy/Helpers/database/achievement-points.php, app_legacy/Helpers/database/player-game.php
fixes #1320
Changes made in #1286 moved the Untracked filter into the JOIN clause. This results in the Untracked users still being counted for the number of hardcore unlocks associated to an achievement when doing the true ratio calculation. I've moved it back, and provided an alternate solution to the original problem.
=> Fix recalculation of true ratio not ignoring untracked users

app_legacy/Helpers/database/game.php, app_legacy/Helpers/render/game.php, public/comments.php
Follow-up to #1314, as per @RALordAndrew's report.
- Fix breadcrumb links not working for game titles with special characters (e.g `/`, `'` and `\`). Previously, sanitization was converting titles like `.hack//Infection` to `.hack--Infection`, which caused queries to fail. Solved by modifying `sanitizeTitle` to slash-escape text instead; then, `s_mysql_sanitized_query` is called (which is fine, I hope, since the dangerous parts have already been sanitized).
- Add tag rendering to `comments.php` breadcrumb + header:
---
Furthermore, we have some breaking cases revolving around base game and subset naming; more precisely, when `$title` isn't actually the base game for the subset `$title [Subset - XYZ]`. However, I could find only two instances of it, which are ironically opposite in nature: …
=> Follow-up fixes for breadcrumb tags

README.md
The README is currently incorrect. The required Node.js version is [enforced via the _package.json_ file](https://github.com/RetroAchievements/RAWeb/blob/219266ab104da7c74c236b67125ed6cb4e9340e1/package.json#L33):
```json
"engines": {
"node": "v18.8.0",
"npm": "8.18.0"
}
```
=> docs(README.md): update required node version

app_legacy/Helpers/database/forum.php, app_legacy/Helpers/render/forum.php, public/forumposthistory.php, public/viewforum.php
implements #727 
Only shows the most recent post to a forum topic on the Recent Posts page. If additional posts have been made in the last 24 hours or last 7 days, links will be provided to jump to the first post within the 24-hour or 7-day windows.
This does not change the behavior of the Forum Activity widget because of the additional overhead in performing the query since the widget appears on the main page. If the four most recent posts are all part of the same Topic, they'll still all be shown.
I did, however, slightly modify the layout of the Forum Activity widget. The timestamp is changed from an absolute GMT time to an elapsed time, and the View link has been pulled into the header to allow more space in the body for the message content.
Before:
After:
=> collapse forum history by topic

app_legacy/Site/Models/User.php
Strict model rules apply (https://github.com/RetroAchievements/RAWeb/blob/master/app_legacy/Site/AppServiceProvider.php#L24).
Laravel tries to access `remember_token` on the legacy User model which does not exist.
Setting it to `null` resolves this for now.
=> Fix logout request

public/request/auth/update-password.php
instead of "There appears to be a problem with your account".
=> show "Invalid Credentials" error if current password is incorrect

app_legacy/Helpers/database/player-game.php
Address #1349.
So far, the "Latest Masters" table only checked for 100% points, not accounting for cases where the player missed one or more 0-point achievements (thus not 100% cheevos). This is in disagreement with other instances for showing mastery, e.g the "Completion Progress" table. As a side effect, one could possibly even repeatedly "update" their table spot by earning 0-point cheevos.
Fixed by simply changing the check from _total points_ to _amount of achievements_.
=> Require 0-point achievements for `Latest Masters` table

app_legacy/Site/AppServiceProvider.php, app_legacy/Site/Commands/UpdateUserTimestamps.php, phpstan.neon
Add a command to derive more accurate creation timestamps for user accounts.
```shell
php artisan ra-legacy:site:update-user-timestamps
```
This fixes an issue where some accounts are allowed to request a high amount of sets due to their creation timestamp not existing.
Creation timestamps ("Member Since" on profile pages) used to be derived from the Activity table.
Activity entries were written when a user first logged in, not when the account was actually created. As some of the accounts never had any activity there is no date to go by. 
This command tries to interpolate missing and/or timestamps that are out of order.
=> Adjust user account timstamps

public/expiringclaims.php
There is currently a typo when applying the `do-not-highlight` class to the table heading row on the expiring claims page. This is causing the table heading itself to break.
**BEFORE**
**AFTER**
=> fix(expiring-claims): remediate broken header row

public/friends.php
This PR fixes an issue on /friends.php.
Previously, when clicking the "Message" link, the recipient of the new message opened on the subsequent page would be yourself. Now it is changed to the user you clicked the "Message" link for.
=> fix(following): remediate issue with Message link

resources/css/app.css, resources/css/statistics.css, resources/views/components/home-stats-embed.blade.php, resources/views/content/static-data.blade.php, tailwind.config.js, vite.config.js
This PR redesigns the Statistics section on the home page.
**Why?**
The section provides interesting data, but I have always found it difficult to read. Originally, I was just going to add number separators, but I pushed a bit further to use this as an exercise to get more comfortable with the dev experience available on RAWeb.
Notable changes:
- Rather than a paragraph, content is displayed in a small 4x4 grid view.
- Numbers now have separators (ie: 1,000,000 instead of 1000000).
- The latest registered user now is using a timeago-style relative date, so instead of showing a hard date like "11 Feb 02:31", something more approachable like "5 minutes ago" is displayed.
**BEFORE**
**AFTER**
=> feat(home): redesign Statistics section

resources/css/legacy.css
This PR fixes an issue that I believe was introduced as part of the V2 rollout. There is now a substantial cumulative layout shift on legacy pages that have leftcolumn + rightcolumn layouts. 
I am still not totally clear on why this happens, much to my disappointment. I believe the right column renders in the DOM after the left column, but that is just my guess. Regardless, this should fix the issue while still preserving full-width layouts when they occur.
Note that this does not fix the issue on modern pages. I think only the home page and TOS fall under this umbrella presently. However since [layout shift is a core web vital](https://web.dev/cls/), this feels essential to fix for the sake of SEO.
**BEFORE**
**AFTER**
=> fix: remediate large layout shift on legacy pages

resources/views/components/user/top-card.blade.php
This PR makes minor design and a11y changes to the guest login component displayed on the top right of the site. 
The component now responds better to all screen widths. 
A longstanding a11y bug in the existing component was also fixed: the input fields were confusing to screen readers. Up to now, screen readers have only been able to determine that the password field was, in fact, a password field. The username field was undeterminable, so easily confused for username / email address / etc. To fix this, I have attached invisible semantic labels to both fields.
**BEFORE**
_Mobile_
_Desktop_
**AFTER**
_Mobile_
_Desktop_
=> feat(top-card): redesign guest login

public/globalRanking.php
https://discord.com/channels/310192285306454017/1048299730670735421/1075113426105409646
Introduced by #1328. The rank of the first user on a page is looked up to ensure the shared rank is carried over between pages.
There's no easy way to do that for the following list, but there's less chance of users sharing ranks there, so I've removed the lookup. The 26th user on the following list will have rank 26, even if they should share a rank with whoever's at 25.
=> don't calculate rank for highest followed user

app_legacy/Helpers/render/avatar.php, public/gameInfo.php, public/js/activePlayersBootstrap.js, public/js/all.js
This PR resolves https://github.com/RetroAchievements/RAWeb/issues/1365. There are various issues with tooltips on mobile because taps are interpreted as hover events. I have confirmed these issues occur not only on iOS, but occur on some Android browsers as well.
A new event listener, `ontouchstart`, is attached to DOM elements responsible for opening tooltips. This listener will always fire before `onmouseover`. If it does fire, a flag is set and tooltips will not open on tap.
This solution has the benefit of not breaking mobile devices that are using trackpads (which is increasingly common with iPads).
=> fix: turn off tooltips for touch events

public/viewtopic.php
This PR remediates an issue where a long string, such as a very long URL, does not break properly on forum posts and instead overflows the x-axis of the container.
This can be reproduced by going here and scrolling horizontally:
https://retroachievements.org/viewtopic.php?t=13871&c=154476#154476
The post that is overflowing is by a user named ExTermi.
After this PR, the same post wraps correctly:
=> fix(forum): remediate an issue where long strings dont wrap

public/gameInfo.php
This PR adds a 3rd option to the mature content warning. When clicked, this option disables the notification setting for mature content, then redirects the user to the game page.
This change was motivated by some discussion in the #site-feedback channel.
Also, "No" is now in the first position. If this content warning is continuously displayed we can now assume going forward this is no accident. Therefore it makes sense for "No" to be the primary action.
=> feat(game): add mature content permanent bypass option

app/Site/Controllers/ContentController.php, app/Site/RouteServiceProvider.php, resources/views/components/menu/footer.blade.php, resources/views/contacts.blade.php, resources/views/terms.blade.php
Provides a more detailed interaction with the unique accounts over the proposed dropdown menu in #1352.
Removes the "RetroAchievements" section from the footer, as it just linked to the "All Games", "All Achievements", and "Downloads" pages, which are readily accessible from the main menu.
Replaces the "About" header for the Legal/Privacy Policy links with "RetroAchievements", and adds a "Contact Us" link there.
Clicking on the "Contact Us" link goes to a page with links to contact each of the unique accounts, and reasons why those individual accounts should be contacted.
=> add Contact Us page

app_legacy/Helpers/render/layout.php, public/inbox.php
Fix #1373, plus a few more changes.
- Don't show `Next ... >` if there are no more messages ahead (corner case handling)
- Allow passing custom `c` parameter for messages-per-page amount instead of previously hardcoded 10 (no UI way of utilizing this yet; must be URL-modified)
- Fix server error due to occasional negative offset after clicking `< Previous` (defaults to 0; not an expected error, only happens when toying with URL)
- Shows true number of messages next if below max amount (e.g `Next 5 >` instead of `Next 10 >` when at offset 30 with 45 total, 10 per page)
=> Small fixes/adjustments for Inbox/Outbox pages

app_legacy/Helpers/util/trigger.php
This PR fixes an issue on the achievement page where Memory and Mem/Val cell contents can wrap. This is reproducible currently on /achievement/80118 by opening the Dev menu.
**BEFORE**
**AFTER**
=> fix(achievement): remediate an issue where the memory cell contents wrap

app_legacy/Helpers/database/player-game.php, app_legacy/Helpers/render/content.php
This PR fixes an issue reported in #site-feedback where long strings don't properly break in the table, resulting in a horizontal scrollbar and weird formatting for rich presence if a single one of these strings overflows.
=> fix(home): remediate issue where active players table overflows

app_legacy/Helpers/render/code-note.php
This PR makes a change to the code notes table so the note itself is also in monospace font. For improved readability, the monospace font has been changed to use the Tailwind `font-mono` rather than what the `<code>` tag is using.
**BEFORE**
**AFTER**
=> fix(code-notes): use monospace font for both the mem and note columns

resources/css/legacy.css
This PR remediates an issue on the user page where the completion progress div can overflow on the x-axis.
I believe this is occurring due to some operating systems having a slightly thicker native scrollbar than what the div was developed under. The issue does not occur in macOS, but it does occur if I add just a bit of right padding to the div.
**BEFORE**
**AFTER**
=> fix(user): remediate x-axis overflow on completion progress

public/js/activePlayersBootstrap.js
This PR is an initial stopgap fix for addressing a performance issue in the Active Players list (https://github.com/RetroAchievements/RAWeb/issues/1387). It would be ideal for this component not to use Knockout.js and probably to use infinite & virtual scrolling, however until that migration happens this can address a perf issue impacting the site's homepage.
When the component loads, it fetches all of the active players on RA and loads them into an array. Unfortunately this is done using `Array.prototype.forEach()`, which is quite slow when trying to iteratively add this much content to the DOM.
I have made two refactors here to greatly improve performance:
1. `forEach()` has been replaced with `reduce()`. Generally, I do not like using `reduce()` because I find it difficult to read, …
=> perf(active-players): reduce processing overhead by 70%

app_legacy/Helpers/render/content.php, public/viewtopic.php
This PR addresses word wrap regressions on active players and the forum.
With recent changes in 2.9.0, long strings (such as URLs) are correctly wrapped, however now words are wrapped without regard for if the whole word should be moved to a new line.
This PR corrects this, while also still wrapping extraordinarily long strings correctly.
**BEFORE**
**AFTER**
=> fix: address more word wrap issues

app_legacy/Helpers/util/request.php
Included in #1393  
https://github.com/RetroAchievements/RAWeb/pull/1393/files#diff-276f85cc7d9994b508613eab3ce641376786c6128138dedeb71adf41fcea444fR13
Fixes (among other occurences):
```
getRecentMasteryData(): Argument #1 ($date) must be of type string, null given, called in /public/recentMastery.php
```
when calling `recentMastery.php?d=` with an empty `d` parameter. It should default to the current date: https://github.com/RetroAchievements/RAWeb/blob/master/public/recentMastery.php#L12
=> Fix request input default not being passed when empty and string

resources/views/community/components/event/aotw.blade.php, resources/views/community/components/news/carousel.blade.php
https://laravel.com/docs/blade#displaying-data
This will ultimately allow us get rid of the `requestInputSanitized()` helper as soon as all views have been ported to blade views:
> Blade's {{ }} echo statements are automatically sent through PHP's htmlspecialchars function to prevent XSS attacks.
Ideally all those `echo` statements will be removed in the future, too.
=> Use blade's curly braces for data display to show better practice

public/API/API_GetUserCompletedGames.php, public/API/API_GetUserRecentlyPlayedGames.php, public/API/API_GetUserSummary.php, tests/Feature/Api/V1/UserCompletedGamesTest.php, tests/Feature/Api/V1/UserRecentlyPlayedGamesTest.php, tests/Feature/Api/V1/UserSummaryTest.php
This PR acts as a template for other web api endpoint validation.
It applies Laravel's validation to `API_GetUserSummary` and `API_GetUserRecentlyPlayedGames`, comparable to request files in `public/request/`, without making too many assumptions about how our endpoints are used. Adding basic validation to them however might reduce resource usage caused by invalid requests (cpu, db hits, ...) and logging useless errors.
Calling `/API/API_GetUserSummary.php?y=API_KEY&u=&g=nope&a=-1` results in:
```
{
"message": "The u field is required. (and 2 more errors)",
"errors": {
"u": [
"The u field is required."
],
"g": [
"The g must be an integer."
],
"a": [
"The a must be at least 0."
]
}
}
```
Fixes 
```
getUserPageInfo(): Argument #1 ($user) must be of type string, null given, called in …
```
=> Add validation to web api user summary and recently played games

resources/css/statistics.css
Per discussion prior to the 2.9.0 release, this PR adds some slight border radius to the stat boxes on the home page. The radius given matches the other buttons on the side bar.
=> fix(statistics): round the corners on stats boxes

app_legacy/Helpers/render/achievement.php
This PR makes a very minor change to the "Points" label on achievement tooltips. If Points === 1, the label now displays "1 Point" instead of "1 Points".
=> fix: add basic point pluralization to achievement tooltips

app_legacy/Helpers/database/set-claim.php, app_legacy/Helpers/render/set-claim.php
Claims for games for rollout consoles can be completed from Unofficial, but not played by users yet. This filters completed claims for rollout consoles from the main page. They'll still appear in the page that loads when clicking the "more..." link, and users who have requested the set will still be notified that the claim was completed.
https://discord.com/channels/310192285306454017/1067638638919307414/1081271680833429604
=> exclude sets for rollout consoles from new sets widget on main page

resources/css/statistics.css, resources/views/content/static-data.blade.php, tailwind.config.js
This PR adds the app color theme variables to the Tailwind configuration so we no longer need to use something like:
```html
<div class="hover:border-[color:var(--menu-link-color)]" />
```
Instead, we can now use:
```html
<div class="hover:border-menu-link" />
```
Existing styles for the new statistics UX have been refactored accordingly.
=> refactor: integrate app theming in tailwind

app_legacy/Helpers/render/avatar.php, package-lock.json, package.json, public/gameInfo.php, public/js/activePlayersBootstrap.js, public/js/all.js, resources/js/app.ts, resources/js/types/global.d.ts, resources/js/utils/index.ts, resources/js/utils/tooltip.ts
This PR addresses some discussion that recently came up in #site-feedback regarding recent changes to mobile tooltips, specifically in the case of Android users.
It seems Android and iOS handle "hover" gestures differently, and things were not broken on Android as they are on iOS for tooltips.
```
Hey yall, Jamiras directed me here. Just wanted to voice that I liked / used site tooltips on mobile quite a bit (android chrome). not sure if it can be disabled for one browser and not another, or via user profile settings, but it never seemed to cause any issues on my platform. minor thing but wanted to pass it on, thanks for all the hard work :pray~1:
Same here, I was trying to pull them up the other day while looking at a ticket to see the description of an achievement by tap holding it but …
```
=> fix: enable mobile tooltips on Android only

public/request/game/update-image.php
This PR adds validation to uploading game icons to game pages. An error message is now shown if the user attempts to upload an image that is not exactly 96x96.
https://discord.com/channels/310192285306454017/1082859674002522192
=> feat(game): require game icons to be 96x96 pixels

resources/views/content/top-links.blade.php
This changes the home page's RAPodcast URL to https://youtube.com/@RAPodcast, per https://github.com/RetroAchievements/RAWeb/pull/1372#discussion_r1122510772.
=> feat(home): update RAPodcast url

app_legacy/Helpers/render/layout.php, public/gameInfo.php
Currently, the "Hardest Achievements" URL does not link to a list of achievements. It takes the user to a game list sorted by retro ratio. This could be more accurately labeled as "Hardest Games", but then it wouldn't belong under the "Achievements" menu.
This PR updates the URL to instead go to the site's global achievement list, pre-sorted by highest retro ratio.
https://discord.com/channels/310192285306454017/511718348178849792/1083779531065806929
=> fix(layout): update sitenav Hardest Achievements url

public/gameInfo.php, public/linkedhashes.php
Per https://discord.com/channels/310192285306454017/1082381537619738766/1083784110364958860, this PR changes the game page's "Linked Hashes" to "Supported Game Files".
The Manage > Latest Linked Hashes is intentionally left untouched because the linked hashes copy is certainly more relevant for that page.
There are also some minor stylistic changes to the game link hashes page.
=> feat(game): change copy for linked hashes

resources/views/layouts/components/head.blade.php
iOS Safari is currently detecting several sequences of numbers on the site as being phone numbers. When these values are tapped, the user is prompted to initiate a phone call.
This change mitigates this undesirable behavior.
ref: https://discord.com/channels/310192285306454017/1087759281299914843
=> fix: prevent iOS Safari from detecting numeric sequences as phone numbers

public/dorequest.php, resources/js/dynamic/reorderSiteAwards.ts
This PR fixes an issue where dragging award images on the reorderSiteAwards page can break the table. Now when an image is dragged, it's treated the same as a row drag.
https://user-images.githubusercontent.com/3984985/231588610-e1e0fecb-abeb-4dd0-9ad5-1864ff1a7114.mp4
=> fix(reorderSiteAwards): remediate issue with dragging badge images

app_legacy/Helpers/database/game.php, public/gameList.php
This PR:
* Makes an update to dev-specific _gameList.php_ pages such that, in addition to a set's total loaderboard count being shown, the count of leaderboards worked on by the dev is also shown.
* Adjusts the total cell for leaderboards so it displays the sum of leaderboards specifically worked on by the dev.
**BEFORE**
**AFTER**
=> feat(gameList): show the count of leaderboards owned by the dev

resources/css/nav.css
With the addition of system icons in the main navigation the columns aren't wide enough anymore to prevent line breaks (PC Engine & 3DO entries).
This PR fixes that, should not have implications for smaller screens if i'm not mistaken.
**Before**
**After**
=> Adjust column width in main nav

app_legacy/Helpers/database/player-game.php
Long due follow-up to #1350.
The `Latest Masters` / `High Scores` loop logic checks for the first 10 players returned by an SQL query. Since the query was previously ordered by score but _not_ by # of unlocked achievements, in sets with 0-pointers the loop would occasionally abort too early (i.e before it could find all masters). This PR simply amends things so they work as intended.
=> Fix `Latest Masters` not showing players correctly for sets with 0-pointers

app_legacy/Helpers/render/user.php
This PR addresses feedback left by @Jamiras in https://github.com/RetroAchievements/RAWeb/pull/1477#pullrequestreview-1392714663 for the "Hide completed sets" checkbox.
With this branch's changes, the new checkbox will no longer appear unless the user has at least 1 completed set and 1 non-completed set.
=> fix(user): add conditional rendering for hide completed sets checkbox

resources/js/utils/injectShortcode.test.ts, resources/js/utils/injectShortcode.ts
This PR fixes a longstanding issue with shortcode injection where if a shortcode button is clicked but no text is highlighted, the shortcode is appended to the end of the textarea's input rather than the current cursor position.
I have confirmed this behavior [was not a regression from this function's migration to TypeScript](https://github.com/wescopeland/RAWeb/commit/da3e9c56d775919b97103f78e657ef81adc88d86#diff-931ee85c19ae8eac66d195c307413252e54191fb71c05b9d2e45ec7b66169ad7L111). It seems to have been intentionally built this way, but I believe this is not a great user experience.
**Root Cause**
In the case where `selectedText === ''`, the code simply appends the shortcode to the end of the textarea value, which is incorrect. We need to change this line to properly insert the …
=> fix(forum): inject shortcodes to the correct position

app_legacy/Helpers/render/ticket.php
This pull request addresses a bug in the renderTicketCard function, which caused an incorrect display when the closedBy value of a ticket was not truthy. The issue resulted in an empty "Closed by" name and a close date showing"01 Jan 1970".
ref: https://discord.com/channels/310192285306454017/1098327873686880276/1098327873686880276
=> fix(ticket): dont show closed by meta for tickets in request status

app_legacy/Helpers/render/achievement.php
This PR addresses an issue raised in https://github.com/RetroAchievements/RAWeb/pull/1487 where locked achievement badges shown in tooltips on user profile pages are not in grayscale.
I have come to believe this behavior is a bug, mostly due to badge artwork like what was created for [Myst on 3DO](http://retroachievements.org/game/16839).
This PR restores these images to be grayscale until the achievements are unlocked by the user.
https://user-images.githubusercontent.com/3984985/233530759-9cbc2a91-4ccc-4e4f-99a9-1ce4cd431aac.mp4
=> fix(user): force locked achievement tooltips on user pages to grayscale

storage/app/releases.dist.php
The link to download DuckStation on the Downloads page is currently broken. This PR fixes the broken link.
=> fix(downloads): remediate broken duckstation link

.github/workflows/ci.yml, package.json
Addresses https://github.com/RetroAchievements/RAWeb/pull/1528#issuecomment-1529133767
`npm run test` does a full pass of Vite/TypeScript code.
`npm run test:watch` puts Vitest into watch mode after a full pass.
=> ci: adjust vitest package.json commands

public/gameInfo.php
Per https://discord.com/channels/310192285306454017/1103984823040737280, renames "Collections" on game pages to "Hubs". They referred to as Hubs everywhere else on the site, so this brings the game pages in line for consistency's sake.
=> fix(game): rename Collections to Hubs

app_legacy/Helpers/render/leaderboard.php
**Highlights**
- This PR attempts to fix an issue with the Mastered column on the global ranking [page](https://retroachievements.org/globalRanking.php?s=9&t=1&d=2023-05-07&f=0) when certain filters are used.
- The issue was first described in [#1088](https://github.com/RetroAchievements/RAWeb/issues/1088) as quoted below.
> Mastered (and soon Completed) columns do not report accurate data for the Daily/Weekly filters and will at most display 1
**Considerations**
- Because my RAWeb test server is not fully set up, I'm submitting this untested on my part.  Any feedback/assistance would be greatly appreciated.
- As for the second issue described in [#1088](https://github.com/RetroAchievements/RAWeb/issues/1088) and relating to Friends, I haven't looked into it yet, because I haven't started …
=> fix(globalRanking): Mastered column only displays a value of 1 or 0 when using Daily/Weekly filters

public/globalRanking.php
**Highlights**
- This PR attempts to fix an issue with the Rank column on the global ranking [page](https://retroachievements.org/globalRanking.php?s=5&t=2&d=2023-05-07&f=1&o=25) using the Followed Users filter and when browsing pages past your actual rank.
- The issue was first described in the latter part of [#1088](https://github.com/RetroAchievements/RAWeb/issues/1088) as quoted below.
> Self rank among followed users is not correctly displayed when you move to
**Considerations**
- Because my RAWeb test server is not fully set up, I'm submitting this untested on my part.  Any feedback/assistance would be greatly appreciated.
- The other issue described in the former part of [#1088](https://github.com/RetroAchievements/RAWeb/issues/1088) is addressed by …
=> fix(globalRanking): Rank column shows your rank as being 0 when using the Followed Users filter and browsing pages past your actual rank

public/codenotes.php
Resolves https://github.com/RetroAchievements/RAWeb/issues/1563.
In the original code, the `.replace()` function was looking for a `<br>` element followed by a newline character (`\n`). However, it is possible for the input string to contain `<br>` elements that are not always followed by a newline character. This inconsistency caused the line breaks to not be properly restored when the user cancelled editing a code note.
=> fix(codenotes): remediate issue with cancel restore linebreaks

resources/css/table.css
This PR lightly increases the background color contrast for table rows so they stand out more, as per some feedback. So far the visual difference was really subtle, almost invisible in some displays. The change was small, so the focus doesn't go away from the content.
Before / after:
Likewise, highlight on hover was also increased a little bit.
=> Increase contrast for alternate table rows

resources/js/dynamic/reorderSiteAwards/cancelAutoscroll.ts, resources/js/dynamic/reorderSiteAwards/handleRowDragOver.ts, resources/js/dynamic/reorderSiteAwards/index.ts
This PR resolves a minor issue with the new window edge autoscroll functionality on the reorder site awards page.
**Before**
When a row is dropped while autoscroll is running, autoscroll keeps running and the page keeps scrolling.
**Now**
Autoscroll is immediately stopped on a row drop.
=> fix(reorderSiteAwards): force stop autoscroll on row drop

app_legacy/Community/Models/UserGameListEntry.php, app_legacy/Helpers/database/site-award.php, app_legacy/Helpers/database/user.php, tests/Feature/Community/UserGameListTest.php
Provides one extra set request per Event Award the user has earned. This includes Site Award Developer Events (DevQuest, Devember, Junior Dev, etc) and Event Awards (AotW, Challenge League, Daily DistRActions, etc). This does **not** include the tiered developer achievements and points awards, Patreon or RA Legend badges.
ref: https://discord.com/channels/310192285306454017/1103455623288475748/1103455623288475748
Example with a mix of points and each type of award
Before
After (4 Site awards excluded as stated above so a total of 20 added)
Example where a dev that completes a lot of developer events will see benefit
Before
After (2 Site awards excluded so a total of 18 added)
Reasoning is to help promote both player and developer events by providing some extra small reward to earning …
=> Event Awards Add Set Requests

app_legacy/Helpers/database/forum.php, app_legacy/Helpers/database/user-activity.php
This PR adjusts the function calls for submitting comments and forum topic replies.
If the user submits a duplicate payload on the same article/comment ID, the function now returns an error and the duplicate post is blocked.
This issue can occur when the site doesn't instantly respond to a post submit and the user repeatedly spams the button click. After this change, only the first post will be preserved and all subsequent duplicates are blocked.
=> feat: throw an error on forum/comment double posts

app_legacy/Helpers/database/game.php, public/API/API_GetAchievementOfTheWeek.php, public/API/API_GetAchievementUnlocks.php, public/achievementInfo.php
This PR resolves an issue where subsets are not inheriting their parent game player counts correctly.
**Root Cause**
The algorithmic check was not checking for console ID. Many of the games with issues were PS2 titles with GameCube ports, thus 0 players were detected from the parent.
=> fix(game): add console id check for parent game id

app/Helpers/formatters.php
This PR remediates an exception thrown in dorequest.php with `VALUE`-kind leaderboard submission.
**Root Cause**
```php
$locale ??= session('number_locale');
```
This null coalescing assignment operator has nowhere to safely navigate to if there isn't a `number_locale` value in the session, which will always happen in the case of calls made through rcheevos. Now, it will fall back to "en_US".
=> fix(localized_number): use en_US as a fallback locale

public/gameList.php
Resolves a minor regression introduced in https://github.com/RetroAchievements/RAWeb/pull/1504 where the table footer is missing a td element.
=> fix(gameList): add missing td

storage/app/releases.dist.php
This PR adds three missing systems to Bizhawk on the downloads page:
* Apple II
* Game Gear
* PC Engine CD
All three of these systems have been confirmed as supporting RA, but are currently absent from the list.
=> fix(downloads): add missing bizhawk supported systems

public/achievementInfo.php
Resolves https://discord.com/channels/310192285306454017/1107095778167619584.
**Root Cause**
Game titles on achievementInfo pages are being sanitized before being passed to the parentId checking function. This causing the matching algorithm to break.
=> fix(achievementInfo): resolve an issue where player counts are incorrect

public/createmessage.php
This PR remediates an issue reported here: https://discord.com/channels/310192285306454017/1106029608408723486
**Root Cause**
The HTML structure for createmessage.php is invalid. Right now, the entire form renders outside its `<form>` tag.
=> fix(createmessage): remediate html structure issue

public/admin.php
A user has reported that the Get Achievement Unlocks tool on admin.php is consistently returning 500 errors. The changes in this PR should resolve the issue.
ref: https://discord.com/channels/476211979464343552/1110344645675864074
**Root Cause**
The original code used a for loop to iterate over the `$winners` array based on its count. However, inside the loop, `$winnersCount` was reassigned to the count of the current element in `$winners`. This led to a potential scenario where the loop could iterate beyond the size of `$keys` array, causing an "Undefined array key" error when trying to access an index in `$keys` that didn't exist.
=> fix(admin): remediate 500 error on Get Achievement Unlocks

app/Support/Shortcode/Shortcode.php, tests/Unit/ShortcodeTest.php
This PR remediates an issue where timestamps are ignored by YouTube video embeds, such as on achievement pages.
**Root Cause**
The privacy-enhanced YouTube embed URL at `youtube-nocookie.com` does not support the `&t` query parameter. Instead, `&t` must be converted to `&start` which an integer of seconds representing the timestamp.
For example, `&t=1m30s` must be converted to `&start=90`.
=> fix(shortcode): support timestamps in youtube embeds

app_legacy/Helpers/database/release.php, app_legacy/Helpers/render/layout.php
Atari Jaguar CD validate + adding it to the navbar.
Once merged, this should **NOT** be deployed until Sunday, June 4th at 00:00 GMT.
=> Validate Jaguar CD on site

resources/views/platform/components/game/primary-meta-row-item.blade.php
This PR resolves an issue with hyperlink rendering on game page metadata rows.
**Root Cause**
There is a logic error when handling the keys in the `$metadataValues` array.
When using the `array_search` function to find the key of a value in an array, it returns `false` if it cannot find the value. PHP will automatically cast this `false` value to 0 when it's used as an array key. Therefore, if `$value` is not found in `$metadataValues`, `$key` will be set to `false`, and then used as 0 when setting a value in `$metadataValues`. This would cause the first value in the array to always be replaced with the new value, which leads to the current prod issue.
**Before**
**After**
Current (prod): https://retroachievements.org/game/12635
Expected (v3 preview): …
=> fix(game): remediate metadata anchor tag issue

public/js/all.js
This PR converts search results in the site's searchbox to be actual hyperlinks. With this change, the user is able to right click on them and open results in a new tab.
ref: https://discord.com/channels/310192285306454017/1113094098010771526
https://github.com/RetroAchievements/RAWeb/assets/3984985/3828092c-cd29-41b2-817f-1f2bd4041e07
=> feat(search): allow opening new tabs via right clicking

app_legacy/Helpers/database/search.php
This PR remediates an undesirable behavior where pipes in game names causes those results to be placed too far down the list, often resulting in a dropoff altogether. This can notably be seen in the original release of Pac-Man for the arcade, which currently does not appear as a result in the search component unless searching for its Japanese name.
**Before**
**After**
=> fix(search): ignore pipes in game names

app_legacy/Helpers/database/ticket.php, public/request/achievement/update-flag.php
This PR resolves an issue where if an achievement is demoted as a ticket resolution action, an audit log is not added indicating who demoted the achievement.
ref: https://discord.com/channels/476211979464343552/1026595325038833725/1116877958733365369
https://github.com/RetroAchievements/RAWeb/assets/3984985/d211fe77-1803-464c-b904-2faf35d0da24
=> fix(ticket): add audit log on achievement demotion

public/achievementInfo.php, public/gameInfo.php
This PR fixes an issue on game pages and achievement info pages where if points is equal to zero, a retropoints value of zero is always shown when it should actually be hidden.
Currently:
On game pages, the zero points value is currently hidden but retro points is always shown.
On achievement info pages, both zero-point values are shown.
After this PR:
On game pages, if an achievement is worth zero points, a retro points value of zero does not appear.
On achievement info pages, if both the achievement and its retro points are zero, neither will be displayed.
**BEFORE**
**AFTER**
=> fix: hide zero-value RetroPoints display if Points value is zero

public/js/all.js
Resolves mobile search links issue found in V3.
**Before**
Clicking a searchbox result on <=MD would cause a page refresh with no navigation.
**After**
Clicking a searchbox result on <=MD navigates the user correctly, mirroring the current behavior in prod.
=> fix: remediate mobile searchbox navigation

public/gameInfo.php, resources/views/platform/components/game/devbox-claim-management.blade.php
This PR resolves an issue where game names are not being decoded in the `confirm()` dialogs that appear for the claims controls in the devbox component.
**Root Cause**
_gameInfo.php_ is (correctly) sanitizing game names:
```php
sanitize_outputs(
$gameTitle,
$consoleName,
$richPresenceData,
$user,
);
```
Then, `$gameTitle` is used for non-Blade stuff on the page. My naive guess is the co-mingling of the legacy renderer and the Blade renderer is causing issues like this.
=> fix(claims): decode game titles in confirm dialogs

resources/views/community/components/news/carousel-scroll-buttons.blade.php
This PR remediates an issue with the pagination buttons on the home page news carousel. Their current z-index places them on a layer above the navigation menu.
**Before**
**After**
=> fix(home): remediate zindex issue with carousel buttons [V3]

app/Helpers/render/comment.php, public/js/all.js, resources/views/community/components/forum/post-container.blade.php
This PR fixes an issue with opening deep links in forum threads where the top of the message is cut off by the navbar. To resolve this, I've set the `id` attributed element to an invisible div that is floating 64px away from the linked post.
The issue can be repro'd by opening (in a new tab) a deep linked forum post that is somewhere halfway through the thread, eg: viewtopic.php?t=20260&c=153328#153328
**Before**
**After**
=> fix(viewtopic): add 64px offset for deep links [V3]

resources/css/nav.css
Resolves https://discord.com/channels/476211979464343552/1002693810037477377/1126534792108851250.
I know we had agreed to generally not use `@apply` directives in CSS files, however this is one change where I strongly feel it is appropriate. A benefit of using Tailwind is to mitigate magic numbers for z-indexing, a common cause of bugs and stress.
=> fix(nav.css): raise z-index value

resources/views/community/components/news/carousel-item.blade.php
This resolves an issue with the news carousel where on slow connections if the image does not fill the container, the carousel height appears as too small for a few frames.
=> fix(carousel): add minimum height

public/js/all.js
Resolves https://discord.com/channels/476211979464343552/1026595325038833725/1127755709442961438.
**Root Cause**
In https://github.com/RetroAchievements/RAWeb/pull/1641, code was added to increase the offset to these links to account for the site's sticky navbar. However, I forgot to delete some code from the previous implementation, which is now blowing up and causing the error exhibited at the Discord URL above.
=> fix: remediate js error on comment deep links

app/Support/Shortcode/Shortcode.php, tests/Unit/ShortcodeTest.php
Resolves https://github.com/RetroAchievements/RAWeb/issues/1655.
**Before**
When making a post with the text content:
```
docs.retroachievements.org/Working-with-the-Right-ROM
```
The displayed content would be:
```
docs.https://retroachievements.org/Working-with-the-Right-ROM
```
**After**
The displayed content is now:
```
https://docs.retroachievements.org/Working-with-the-Right-ROM
```
=> fix(forum): resolve parser outputting broken docs links

resources/js/tooltip/utils/renderTooltip.ts
The new Floating UI tooltip implementation has a mild clash with the new user card tooltips due to not accounting for overflow in the card div. Resolved by simply adding `overflow-hidden` to the Floating UI tooltip div.
**Before**
**After**
=> fix(tooltip): add overflow-hidden classname

resources/js/tooltip/attachTooltipToElement.ts
This PR resolves a longstanding issue where tooltips flicker when hovering over other elements within a tipped element's context.
**Root Cause**
Event bubbling is causing multiple onmouseover events to fire, even if the tooltip is already opened.
**Before**
https://github.com/RetroAchievements/RAWeb/assets/3984985/82ddbe36-eb0e-4a9a-85c6-0cd29b895532
**After**
https://github.com/RetroAchievements/RAWeb/assets/3984985/cccab760-c715-40da-bd91-d960d0331474
=> fix(tooltip): prevent tooltip flickering on mouseover

database/seeders/AchievementSetClaimSeeder.php, database/seeders/DatabaseSeeder.php, resources/views/community/components/claims/finished-claims.blade.php
This resolves #1670 by adding the ConsoleId on the edge case if a game shares a name with one on another console then it does not get flagged. I know the others were using the name of user and game, but figured ConsoleId would be a bit more unquie, smaller in size and maybe stop any other possible edge cases.
Also added a Seeder to populate some claims. Set `Status => ClaimStatus::Complete` so it has some data to display on the front page.
=> Resolves #1670 By adding ConsoleId to the ClaimKey check

public/js/all.js
Resolves https://github.com/RetroAchievements/RAWeb/issues/1678, a regression introduced by https://github.com/RetroAchievements/RAWeb/pull/1641.
Additionally, I've migrated the query call from jQuery to vanilla JS.
**Root Cause**
Deleted comments to be hidden are no longer being queried correctly in the DOM.
=> fix: hide comments when deleting them

resources/views/components/tooltip-card.blade.php
Resolves #1691.
**Root Cause**
In anticipation of using larger images in tooltip cards for game and achievement badges, I applied an `image-rendering: pixelated` style to the card container, which makes those badges look quite a bit nicer when scaled up. However, this has the opposite effect for avatar images.
To resolve this, I've added a new prop, `isLowResImage`, to the `<x-tooltip-card />` component. The style is conditionally applied when this prop is set to `true`.
=> fix(tooltip): conditionally apply pixelated rendering style

public/js/activePlayersBootstrap.js
Resolves https://discord.com/channels/310192285306454017/1133533776153170022 and https://discord.com/channels/476211979464343552/1026595325038833725/1133879281135657002.
**Root Cause**
The active players widget images are tooltipped, but also pop native browser tooltips using `title` attributes. These take precedence over JS tooltips, thus causing the reported issues.
**Resolution**
The `title` attributes have been removed. They are redundant given the images already have `alt` attributes and JS tooltips.
=> fix(active-players): remove native browser tooltips

public/request/auth/reset-password.php
There is currently a bug on the reset password page affecting users with usernames less than 4 characters long. These users are unable to reset their passwords.
This PR removes the min length validation from the password reset endpoint, allowing these users to reset their passwords and regain access to their account.
=> fix(resetPassword): allow resetting even with short username

database/seeders/GamesTableSeeder.php
The `MD5` column of game hashes has to be populated by seeders to allow the down migration of `2018_10_02_000004_create_game_meta_tables` to revert the composite primary key.
`composer mfs` is a shorthand for `php artisan migrate:refresh --seed` which runs the down migrations instead of dropping all tables.
`php artisan migrate:fresh --seed` drops all tables and does not run into this issue.
> **Warning**
> Do NOT run these commands if you do not want to lose any data in your local database.
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'GameHashLibrary.PRIMARY' (SQL: alter table `GameHashLibrary` add primary key (`MD5`))
```
=> fix(seeders): `composer mfs` cannot run down migration

resources/views/community/components/claims/finished-claim-table-row.blade.php, resources/views/community/components/claims/finished-claims.blade.php, resources/views/community/components/claims/new-claim-table-row.blade.php, resources/views/community/components/claims/new-claims.blade.php
This PR resolves a potential issue that can arise on the home page as a result of user avatars being rendered in two different table columns.
This is a stopgap solution- these components ideally shouldn't be using table layouts.
**Before**
**After**
=> fix(home): use a single table column for showing claim devs

public/API/API_GetAchievementUnlocks.php, tests/Feature/Api/V1Test.php
fixes
```
Trying to access array offset on value of type null at /srv/web/releases/2023-07-23T133407-3.1.1-29c6335f/public/API/API_GetAchievementUnlocks.php:66)
[stacktrace]
#0 /srv/web/releases/2023-07-23T133407-3.1.1-29c6335f/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /srv/web/releases/2023-07-23T133407-3.1.1-29c6335f/public/API/API_GetAchievementUnlocks.php(66): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
```
=> prevent exception requesting non-existant achievement

public/gameInfo.php
fixes:
```
Undefined array key 1 at /srv/web/releases/2023-07-23T133407-3.1.1-29c6335f/public/gameInfo.php:385)
[stacktrace]
#0 /srv/web/releases/2023-07-23T133407-3.1.1-29c6335f/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /srv/web/releases/2023-07-23T133407-3.1.1-29c6335f/public/gameInfo.php(385): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /srv/web/releases/2023-07-23T133407-3.1.1-29c6335f/public/gameInfo.php(468): calculateBuckets()
```
when visiting `/game/X?f=N` where N is something other than 3 or 5.
=> prevent exception when receiving invalid f parameter

app/Helpers/database/forum.php, app/Helpers/database/search.php
When a forum topic is deleted, the topic is marked as deleted (soft delete), but the posts remain. This prevents the "deleted" posts from appearing in the list of unverified forum posts and search results.
https://discord.com/channels/476211979464343552/1002689485005406249/1134137157636870164
Side note: should the forum topic comments for the deleted topic also be marked as deleted?
=> ignore deleted forum topics when reporting unverified forum posts

app/Helpers/render/layout.php, resources/css/legacy.css, resources/css/search.css, resources/views/components/menu/main.blade.php, resources/views/components/user/top-card.blade.php, resources/views/layouts/components/brand-top.blade.php, resources/views/layouts/components/main.blade.php
Apply `lg:grid grid-cols-[1fr_340px] gap-4` in top brand, nav, and main content areas. 
Prevents layout shift and works with wide layouts (see /demo).
=> fix(layout): prevent layout shift with sidebars

app/Helpers/database/user-activity.php
Fixes
```
"exception":"[object] (Illuminate\\Database\\Eloquent\\JsonEncodingException(code: 0): Error encoding model [App\\Site\\Models\\User] with ID  to JSON: Malformed UTF-8 characters, possibly incorrectly encoded at /srv/web/releases/2023-07-23T133407-3.1.1-29c6335f/vendor/laravel/framework/src/Illuminate/Database/Eloquent/JsonEncodingException.php:18)
[stacktrace]
#0 /srv/web/releases/2023-07-23T133407-3.1.1-29c6335f/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1649): Illuminate\\Database\\Eloquent\\JsonEncodingException::forModel()
#1 /srv/web/releases/2023-07-23T133407-3.1.1-29c6335f/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2354): Illuminate\\Database\\Eloquent\\Model->toJson()
#2 …
```
=> fix cache key generation

app/Helpers/database/game.php, app/Helpers/database/player-achievement.php, public/gameInfo.php
Filtering out the untracked users for metrics calculations appears to have an exponential impact to the query performance. Game pages make four metrics calculations:
1) number of players for the game
2) number of players who have earned each achievement in hardcore or softcore
3) number of achievements earned per player in hardcore (distribution graph)
4) number of achievements earned per player in softcore (distribution graph)
As a result, loading game pages for popular games is slow. The plan was to generate denormalized data in the database to address this, but we need a more immediate solution for now.
This PR modifies the game page logic for games where there are more than 100 players. The number of players for the game is calculated in the same way (excluding untracked users). If …
=> don't filter out untracked users if set has more than 100 players

public/codenotes.php
Resolves https://discord.com/channels/476211979464343552/1026595325038833725/1137756621519454238.
**Root Cause**
The JS in this file is assuming the old wz_tooltip implementation is still in place, and is not correctly compensating for the new Alpine.js-driven implementation.
=> fix(code-notes): remediate js error on save

app/Helpers/database/player-achievement.php
#1712 removes the untracked user filtering for sets with over 100 players but the join on UserAccounts was still there so this removes that as well.
**Benchmarks**
These samples were collected on game ID 1446 with the local MySQL cache disabled. Results are the combine 2 calls for hardcore and softcore
  | Before | After
-- | -- | --
1 | 1105ms | 507ms
2 | 1180ms| 501ms
3 | 1117ms | 505ms
4 | 1135ms | 493ms
5 | 1119ms | 499ms
Average | 1131ms | 501ms
Speedup Factor: ~2.26x
=> perf: remove unnecessary join on UserAccounts

public/gameInfo.php, public/history.php, public/individualdevstats.php, public/userInfo.php, resources/views/community/components/user/online-count-chart.blade.php
This PR adjusts how Google Charts renders on all relevant pages.
Right now, on game pages and user profiles, once the browser receives its first byte but before the page fully paints to the screen, 50% of that time is spent parsing JS. A huge chunk of that JS is Google Charts.
After this PR, Google Charts will no longer be render-blocking. It will load asynchronously in the background, and while loading the chart component will just render empty space.
=> perf: defer loading of google charts

public/js/activePlayersBootstrap.js, resources/views/layouts/components/head.blade.php
There is only one lodash call in the entire app: `_.filter()` in the Active Players widget.
The lodash dependency is roughly 27KB unminified, and the entire app pays this tax due to this one call. On mobile 3G connections, this adds roughly 500ms of load time to an end user's first page view.
This PR migrates the `_.filter()` call to native JS `Array.prototype.filter()` and removes the lodash dependency.
=> perf: eliminate lodash

resources/views/layouts/components/brand-top.blade.php, resources/views/layouts/components/head.blade.php
The LCP on nearly every page of the site is the logo in the navbar. Currently it has no preloading, priority, or importance hinting. These hints move the image further up the waterfall to coerce the browser to fetch the image earlier, resulting in better LCP scores.
=> perf: add priority hints to the LCP

resources/views/platform/components/game/multiline-avatar.blade.php
Resolves https://discord.com/channels/476211979464343552/1026595325038833725/1139310042869407995.
**Root Cause**
The invisible space doesn't have the same styles applied as the real visible element, resulting in a minor enough style difference to cause the whitespace to appear.
=> fix: remediate multiline game avatar whitespace issue

resources/views/platform/components/game/screenshots.blade.php
Resolves https://discord.com/channels/476211979464343552/1002693810037477377/1139333012446785657.
**Root Cause**
On macOS, this native scrollbar is hidden. However, it is visible on Windows (and I assume Linux).
=> fix(game): hide images native scrollbar on SM+

public/achievementInfo.php, public/gameInfo.php
Replaces the `*` on Guide URL and Type fields with an infobox icon. Also makes a few a11y improvements to those labels.
=> fix: use infobox icons to designate when title attrs are available

public/achievementinspector.php
This PR remediates an issue from #1714's new toolbox component on the achievement inspector page. Jr Devs are currently able to see more buttons than they should. This PR hides the buttons that they should not be able to see.
**Before**
**After**
=> fix(achievementInspector): adjust display of some buttons for jr devs

public/achievementInfo.php
This PR updates the OpenGraph meta description of achievement info pages to add more contextual information about the achievement and move the achievement description to be the primary focal point of the content.
**Before**
```
Mega Man (NES) - Beat the game without losing a life
```
**After**
```
Beat the game without losing a life (50 points), won by 513 players - Mega Man for NES
```
=> feat(achievement): update meta description

app/Community/Components/UserCard.php
The site rank row in the user card renders as "Site Rank:: #N", with two colons. This is due to a refactor that occurred in the most recent release to transition those cards over to using more reusable components.
=> fix(UserCard): remediate typo

public/gameInfo.php
Mitigates https://discord.com/channels/476211979464343552/1026595325038833725/1139734338041299065, which was introduced by the optimizations in #1712.
Now if unlock rate % is greater than 100% because Untracked players are being included, the UI will just fall back to showing 100%.
=> fix(game): remediate issue where more than 100% progress is shown [V3.2.1]

app/Helpers/database/site-award.php, app/Helpers/render/site-award.php
Resolves https://discord.com/channels/476211979464343552/1026595325038833725/1139786829290291241.
* Ensures beaten games are being fetched properly by the all-purpose `getUsersSiteAwards()` function.
* Ensures they're filtered out in the `SeparateAwards()` function so they don't increase the count of Site Awards on user profiles.
=> fix(site-awards): filter out beaten games from awards displays [V3.2.1]

resources/views/platform/components/game/screenshots.blade.php
Resolves https://discord.com/channels/476211979464343552/1026595325038833725/1139773947949355070.
**Root Cause**
`flex-none` prohibits downscaling to fit the container correctly on mobile, but this is not desirable on SM and above where the carousel is not used. Added `sm:flex-auto` to "undo" this style on SM+ breakpoints.
=> fix(game): remediate desktop screenshots scaling [V3.2.1]

app/Helpers/render/site-award.php
A few of the popular userscripts for the site depended on "seeing" the mastery dates statically rendered in the user profiles site awards. This no longer occurs because of the dynamic game cards not being initially available in the template.
To retain compatibility with these scripts, `data-gameid` and `data-date` attributes have been added to the wrapper div around each award. The date is presented in the same format it was displayed as in the static cards.
NOTE: I have communicated that the preferred solution is https://retroachievements-api-js.vercel.app/v1/users/get-user-awards.html.
=> chore(user): add data-* attrs to game awards for userscripts [V3.2.1]

app/Helpers/database/achievement.php, public/achievementinspector.php, public/request/achievement/update-type.php, tests/Feature/Platform/BeatenGameTest.php
This PR adds another button to the toolbox for mass removal of types from the achievements in the list.
@Tsearo How do you feel about the button position and label?
=> feat(achievementInspector): allow mass removing achievement types

app/Platform/Enums/AchievementType.php, lang/en_US/achievement-type.php, public/achievementInfo.php, public/achievementinspector.php
This PR renames the values for achievement types to "progression" and "win_condition". It also adds i18n resources for these snake-case values, and now uses these resources everywhere in the UI these labels are mentioned.
NOTE: After deploying, the following SQL needs to be executed:
```sql
UPDATE Achievements a SET a.`type` = NULL WHERE a.`type` = '';
UPDATE Achievements a SET a.`type` = 'progression' WHERE a.`type` = 'Progression';
UPDATE Achievements a SET a.`type` = 'win_condition' WHERE a.`type` = 'Win Condition';
```
=> refactor: use snake-case values for the achievement type enum

tests/Feature/Platform/BeatenGameTest.php
This PR adds a new test case to confirm that the platform recognizes a game is beaten in hardcore mode if:
* The user has unlocked all Progression achievements in hardcore.
* The player has unlocked 1 Win Condition achievement in hardcore.
* The player has unlocked 1 Win Condition achievement in softcore.
This seems like something that would be easy to break, so I wanted to add a test case for this to ensure the stability of this behavior.
=> test: add another case for testBeatenGame()

package-lock.json, package.json, resources/js/alpine/tooltipComponent/tooltipComponent.ts, resources/js/alpine/tooltipComponent/utils/loadDynamicTooltip.test.ts, resources/js/alpine/tooltipComponent/utils/loadDynamicTooltip.ts, resources/js/alpine/tooltipComponent/utils/pinTooltipToCursorPosition.ts, resources/js/alpine/tooltipComponent/utils/trackTooltipMouseMovement.ts
This PR resolves a race condition in the tooltip rendering functionality which is currently causing a flicker when rapidly alternating between dynamic tooltips. It is also causing a positioning miscalculation, which sometimes causes tooltips to render in the wrong place.
**Current Prod Behavior (which this PR fixes)**
https://github.com/RetroAchievements/RAWeb/assets/3984985/6a17aa67-09df-4141-91c2-1d5940bdbf85
=> fix(tooltip): remediate render cycle race condition

resources/views/platform/components/game/screenshots.blade.php
Resolves https://discord.com/channels/476211979464343552/1026595325038833725/1140208098909372457.
The carousel styles are only visible now at the XS breakpoint. SM+ sees exactly the content that was present in release 3.1.
**Before**
**After**
=> fix(game): resolve screenshot height issue [V3.2]

resources/views/components/modal-trigger.blade.php
Resolves this issue:
**Root Cause**
There is an erroneous `z-50` class name attached to the modal trigger component that is unnecessary.
=> fix(modal-trigger): remove z-50 [V3.2]

resources/views/platform/components/game/devbox-claim-management.blade.php
This PR resolves a JS error that can occur due to an interpolation problem in the devbox. This is because the raw PHP boolean value is not being interpolated correctly into the component's inline <script> tag.
=> fix(devbox): remediate js error from blade interpolation

app/Helpers/render/layout.php, app/Helpers/render/player-game-compare.php, public/achievementInfo.php, public/achievementList.php, public/controlpanel.php, public/createmessage.php, public/createtopic.php, public/editpost.php, public/gameInfo.php, public/gamecompare.php, public/globalRanking.php, public/history.php, public/historyexamine.php, public/individualdevstats.php, public/latesthasheslinked.php, public/managehashes.php, public/recentMastery.php, public/searchresults.php, public/ticketmanager.php, public/viewtopic.php, resources/css/button.css, resources/css/search.css, resources/views/components/button/form.blade.php, resources/views/components/modal-trigger.blade.php, resources/views/components/user/top-card.blade.php
One of the first components PRs extracted from the prototype/preview branch.
Normalize button usage:
- No `<input type="submit">`
- No `<button type="submit">` (`submit` is implicit)
- No implicit styling of `<button>` (relevant for upcoming PRs)
- Buttons with JS handlers use `type="button"`
That's the third or fourth time I'm normalizing those buttons now 🤔 
I hope this time it sticks 😅
=> chore: normalize buttons

app/Helpers/database/player-game.php, tests/Feature/Platform/BeatenGameTest.php
Resolves an issue found in #1780 in [this comment](https://github.com/RetroAchievements/RAWeb/pull/1780#pullrequestreview-1585778201):
>Not necessarily related to this specific page but through more testing I also noticed if I have a beat award for a game with a single progression achievement if I change that single achievement type to none (no longer any progression) and recalculate my score I still retain the beat award in the database which I would expect is no longer valid and gets removed. This will likely be more apparent when we have the user profile update.
**Root Cause**
`testBeatenGame()` bails when a set has no progression or win condition achievements. Because of the premature return, the code for revocation wasn't being hit.
Now, when the function falls into this premature …
=> fix(testBeatenGame): revoke awards when types are completely removed

resources/views/community/components/forum/post-container.blade.php
Noticed this issue while testing #1786. It appears the IDs for posts are not being interpolated correctly, resulting in the page not auto-scrolling to the linked forum post.
=> fix(forum): remediate deep links anchors

app/Exceptions/Handler.php, public/request/user/update-motto.php
Reccurrance of:
```
Error encoding model [App\\Site\\Models\\User] with ID  to JSON: Malformed UTF-8 characters, possibly incorrectly encoded 
at /home/forge/retroachievements.org/releases/2023-08-14T082503-3.2.2-83eca4ee/vendor/laravel/framework/src/Illuminate/Database/Eloquent/JsonEncodingException.php:18)
```
Which was originally reported [here](https://discord.com/channels/310192285306454017/1135568221995536554/1135568221995536554).
This sanitizes the motto going into the database so the error shouldn't occur again in the future.
=> prevent inserting truncated UTF-8 into motto field

app/Helpers/database/achievement.php, public/dorequest.php
This PR resolves an issue where achievement edits from RAIntegration are removing an achievement's `type` value.
`null` is a valid `type`, so a different fallback ("not-given") was picked.
These exceptions can be removed if and when RAIntegration natively supports the `type` field.
=> fix(UploadNewAchievement): dont strip `type` value on RAIntegration edits

app/Helpers/database/user.php
fixes
```
(mysqli_sql_exception(code: 1064): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')
GROUP BY sa.AwardData, gd.Title
ORDER BY Title'
```
```
[stacktrace]
#0 /home/forge/retroachievements.org/releases/2023-08-14T082503-3.2.2-83eca4ee/app/Helpers/util/database.php(107): mysqli_query()
#1 /home/forge/retroachievements.org/releases/2023-08-14T082503-3.2.2-83eca4ee/app/Helpers/database/user.php(436): s_mysql_query()
#2 /home/forge/retroachievements.org/releases/2023-08-14T082503-3.2.2-83eca4ee/public/individualdevstats.php(202): getMostAwardedGames()
```
=> fix exception viewing dev stats for developer with no sole/majority credits

resources/views/platform/components/game/devbox-claim-management.blade.php
Resolves https://discord.com/channels/310192285306454017/962817919698501702/1145153656702914580.
The "Within 24 hours of Claim" notice is appearing even after multiple days. This is due to a type coercion bug.
=> fix(devbox): remediate early claim notice appearing after 24 hours [V3.3]

resources/js/alpine/tooltipComponent/tooltipComponent.ts, resources/js/alpine/tooltipComponent/utils/trackTooltipMouseMovement.ts
Remediates an issue where static tooltips (such as those for achievements and tickets) are not following mouse cursor movement and are staying frozen in place.
=> fix(tooltip): track mouse position properly with static tooltips [V3.3]

.env.example, app/Site/AppServiceProvider.php, config/envy.php, config/feature.php, public/admin.php, resources/views/components/feature-flags.blade.php, resources/views/demo.blade.php
This PR adds support for feature flags, as well as adds a new Blade directive: `@hasfeature()`.
Assuming this is approved+merged, I'll begin adding feature flag-driven conditional rendering to the progression PRs so they can be merged but not yet enabled.
=> feat: add support for feature flags

public/achievementinspector.php, public/request/achievement/update-type.php
Manually marking progression sucks so now Jrs can do it in bulk on sets where they are the sole developer
=> feat(inspector): allow Jr Devs to mark progression in bulk

public/gameInfo.php
This dialog is user context specific. There should be no reason for it to be enabled/accessible if the user is not authenticated.
=> fix(game): disable beaten credit dialog unless authenticated

resources/views/community/components/global-statistics/recent-game-progress.blade.php
Side note: It seems `.smalldate` has a forced min-width. We may want to get rid of that at some point, it is combative with flex layouts :-(
=> fix(home): use smalldate on recent awards

resources/views/platform/components/game/multiline-avatar.blade.php
The `<img>` tag in these components is missing `loading="lazy"` and `decoding="async"` attributes, causing all the images to load before they're in the browser viewport.
=> perf: use lazy loading on multiline game avatar images

resources/views/components/menu/management.blade.php
Resolves this issue, where the System column can appear even if no tools are available:
=> fix(navbar): hide System column if no tools available

resources/views/components/menu/account.blade.php
If the user has more softcore points than hardcore points, use softcore points as the first points indicator in the navbar.
=> feat(navbar): put softcore points on top for softcore players

public/gameInfo.php, resources/views/platform/components/game/achievements-list/achievements-list-item.blade.php, resources/views/platform/components/game/achievements-list/root.blade.php, tests/Feature/Platform/Components/AchievementsListTest.php
Restores the ability to see author names while viewing Unofficial.
=> fix(achievement-list-item): show unofficial authors

public/gameInfo.php, public/leaderboardList.php
Sets the start, cancel, submit, and value fields in leaderboardList.php to read-only. Now that RAIntegration supports editing leaderboards, and given that we have no validation of input on the web, it doesn't make sense for these fields to be editable in the web UI anymore.
=> chore: disable web-based leaderboard editing

resources/views/platform/components/modal-content/beaten-game-credit.blade.php
This PR adjusts the rendering of game titles in the beaten game credit dialog so they utilize the `renderGameTitle()` function.
**Before**
**After**
=> fix: use rendered game titles on beaten game credit dialog

public/gameInfo.php, resources/views/platform/components/game/mature-content-gate.blade.php
Refactors the mature content warning to a Blade component as part of the continued refactoring of the game page.
To test: visit any game in the mature content hub, such as ID 2772.
Preserves all existing functionality, with only two subtle differences:
* `fetcher` is used instead of native `fetch`.
* The `<x-game.heading>` component is used, which renders the console name and icon as a subheading.
=> refactor(game): migrate mature content gate to blade

app/Helpers/database/player-game.php
With the feature enabled, returns a field that can't reasonably be referenced from the code:
```
array:13 [▼ // app/Platform/Controllers/PlayerCompletionProgressController.php:131
"ConsoleID" => 27
"ConsoleName" => "Arcade"
"FirstWonDate" => "2021-02-15 16:51:35"
"GameID" => 11944
"IF(pg.achievements_unlocked_hardcore > 0, 1, 0)" => 1  <----
"ImageIcon" => "/Images/035728.png"
"MaxPossible" => 22
"MostRecentWonDate" => null
"NumAwarded" => 13
"NumAwardedHC" => 13
"PctWon" => "0.5909"
"PctWonHC" => "0.5909"
"Title" => "Donkey Kong Junior"
]
```
Without the feature enabled, the field doesn't appear to be returned at all.
```
array:12 [▼ // app/Platform/Controllers/PlayerCompletionProgressController.php:131
"ConsoleName" => "Arcade"
"ConsoleID" => 27
"FirstWonDate" => "2021-02-15 16:51:35" …
```
=> remove unused field from query

app/Helpers/render/game.php, public/gameInfo.php, resources/views/platform/components/game/recent-game-players.blade.php, tests/Feature/Platform/Components/RecentGamePlayersTest.php
This PR migrates the game page's "Recent Players" section to Blade and improves the mobile UX for the component.
**Mobile Before**
**Mobile After**
**Desktop Before**
**Desktop After**
---
UX Notes:
* "Recent Players" is now an H2 tag similar to the "Achievements" heading higher up on the page. I wasn't sure if this was perhaps too loud. If we think it's too loud, let's reduce the size but give the tag a `role` attribute with a "heading" value and an `aria-level` of "2".
=> refactor(game): migrate recent game players to blade and improve mobile ux

public/reorderSiteAwards.php
This PR adds a missing "btn" classname to the Save All Changes button on the reorder site awards page.
**Before**
**After**
=> fix(reorderSiteAwards): add btn class to Save All Changes

app/Community/AppServiceProvider.php, app/Community/Components/DeveloperGameStatsTable.php, app/Helpers/database/user.php, public/individualdevstats.php, resources/views/community/components/developer/game-stats-table-row.blade.php, resources/views/community/components/developer/game-stats-table.blade.php
This PR migrates the three "Games" tables on individualdevstats.php to Blade and adds beaten game awards stats to the tables themselves. A significant amount of duplicated code on individualdevstats.php has been deleted.
**NOTE:** I opted not to put these new stats behind a feature flag because, currently, the feature flag is only guarding against player-facing UI/UX. I don't think there's any harm in eagerly exposing these new stats to devs.
=> feat(individualdevstats): migrate game tables to blade and add beaten stats

app/Platform/Models/PlayerBadge.php, database/migrations/2012_10_03_133633_create_base_tables.php, database/migrations/platform/2023_09_29_000000_update_site_awards_table.php
`SiteAwards` has been the only table in the V3 schema changes that did not receive a primary key. This should prevent running into bugs with Eloquent again due to its handling of missing primary keys.
=> feat: add primary key to SiteAwards table

.prettierrc, resources/views/community/contact.blade.php
This PR adds a new section to our contact page to reflect the new inbox we're building out:
=> feat(contact): add new section

public/achievementinspector.php
Resolves #1887.
**Before**
Jr Dev collab partners could not modify achievement types on the Manage Unofficial Achievements page.
**After**
Jr Dev collab partners can now perform this modification.
=> fix(achievementinspector): show checkmarks for jr dev collabs

app/Helpers/database/user-activity.php, app/Support/Cache/CacheKey.php
should minimize login failures
```
[object] (Illuminate\\Database\\QueryException(code: HY000): SQLSTATE[HY000]: General error:
3024 Query execution was interrupted, maximum statement execution time exceeded (SQL:
SELECT * FROM Activity AS act
WHERE act.ID =
( SELECT MAX(Activity.ID) FROM Activity WHERE Activity.user = :user AND Activity.activityType = 2 ) )
at /home/forge/retroachievements.org/releases/2023-09-25T165924-4.1.0-97eec26c/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760
```
=> avoid querying Activity table for recent logins

app/Helpers/database/player-game.php, app/Platform/Models/Achievement.php, app/Site/Models/User.php, database/migrations/platform/2023_10_09_000000_update_player_tables_index.php, database/migrations/platform/2023_10_09_000001_update_achievements_index.php, tests/Feature/Api/V1/AchievementOfTheWeekTest.php, tests/Feature/Api/V1Test.php
Add indexes for player_achievements, player_games, and Achievements tables to improve game metrics queries.
Migrations have been applied to stage environment.
Refactor `getTotalUniquePlayers` to use `player_achievements`.
Verified that the query optimizer actually uses those indexes using the following queries:
```sql
-- players
EXPLAIN
SELECT
COUNT(DISTINCT pa.user_id)
FROM
player_achievements pa
LEFT JOIN Achievements a ON a.ID = pa.achievement_id
LEFT JOIN UserAccounts u ON u.ID = pa.user_id
WHERE
a.GameID = 228 -- 1, 228, 337
AND a.Flags = 3
AND u.Untracked = 0;
EXPLAIN
SELECT
COUNT(DISTINCT pa.user_id)
FROM
player_achievements pa
LEFT JOIN Achievements a ON a.ID = pa.achievement_id
LEFT JOIN UserAccounts u ON u.ID = pa.user_id
WHERE
a.GameID = 228 -- 1, 228, 337
AND a.Flags = 3
AND …
```
=> feat: improve query performance for game and achievement metrics updates

app/Http/Kernel.php, app/Platform/Actions/UpdateGameMetrics.php, app/Site/Middleware/EncryptCookies.php, app/Site/Middleware/FeatureFlagMiddleware.php, resources/js/app.ts, resources/js/types/global.d.ts, resources/views/components/feature-flags.blade.php
This PR adds a middleware which allows a user to force-enable aggregate queries at the request level by having a cookie `feature_aggregate_queries` set to `true`.
It also adds a label for the feature flag to the `<x-feature-flags />` component, which is visible on the admin panel.
=> feat: allow activating aggregate queries with a cookie

app/Platform/Commands/UnlockPlayerAchievement.php, app/Platform/Commands/UpdatePlayerGameMetrics.php, app/Platform/Commands/UpdatePlayerMetrics.php
Makes it easier to run on the server when focusing on individual `player_games` updates where the `user_id` is more prevalent than usernames.
As mentioned in the command parameter descriptions:
> User ID or username. Usernames containing only numbers are ambiguous and must be referenced by user ID
=> feat: allow for user id or username command parameters

app/Helpers/database/player-game.php
Takes ~250ms to build the high scores list for Super Mario World vs 2.5s with the feature disabled.
250ms is still a reasonably large amount of time, so I recommend we continue to cache the result (line 733 above).
=> use aggregate_queries feature for high scores on game page

app/Helpers/database/player-game.php, tests/Feature/Connect/AwardAchievementTest.php, tests/Feature/Connect/BootstrapsConnect.php
```
'DateEarnedHardcore' => $unlock->unlocked_hardcore_at?->format('Y-m-d H:i:s'),
```
would return a null entry for `DateEarnedHardcore`, whereas the non-aggregate code does not populate the key. This caused the filtering code for the `unlocks` and `startsession` requests to not produce the desired results.
https://github.com/RetroAchievements/RAWeb/blob/c0fa53753c0c1a16ce9418c17af8c72f23af1233/public/dorequest.php#L392-L394
https://github.com/RetroAchievements/RAWeb/blob/c0fa53753c0c1a16ce9418c17af8c72f23af1233/public/dorequest.php#L325-L335
In fact, the `strtotime` call would change the value from `null` to `false` resulting in unparseable timestamps for the client.
```
{"Success":true,"HardcoreUnlocks":[{"ID":361917,"When":false},{"ID":361918,"When":false},{"ID":361919,"When":false}, …
```
=> fix client error retrieving softcore unlocks with aggregate queries on

public/dorequest.php
Fixes `App\Platform\Events\PlayerSessionHeartbeat::__construct(): Argument #2 ($game) must be of type App\Platform\Models\Game, null given`.
I don't think saving the last login date for users when no valid date was provided is worth the overhead. There are a lot of writes to the last login date already.
=> fix(connect): do not record ping requests without a game ID

app/Helpers/database/game.php
Fixes 
> Undefined array key 3 at /home/forge/retroachievements.org/releases/2023-10-21T184740-5.0.1-b4e1dc15/public/gameInfo.php:446)
exception caused by soft-deleting achievements with Flags=0 (https://discord.com/channels/476211979464343552/1026595325038833725/1165025766585671821)
See also: https://discord.com/channels/476211979464343552/1002696640001478769/1165839500572889128
=> fix error viewing unofficial achievements for game with soft-deleted achievements

app/Helpers/database/user.php
This should get rid of one of the majorly slow queries.
=> feat: use pre-aggregated data for unlocks on users list

app/Helpers/database/player-game.php, composer.json, public/gamecompare.php
Fixes exception:
> Attempt to read property \"id\" on null at /home/forge/retroachievements.org/releases/2023-10-23T221621-5.0.1-2265ac73/app/Helpers/database/player-game.php:317
returns 404 instead
=> prevent exception comparing to non-existant user

.env.example, .gitignore, app/Site/AppServiceProvider.php, config/database.php, docker-compose.yml, docker/mysql/Dockerfile, docker/mysql/create-testing-database.sh, docker/mysql/mysql.cnf
Add the following to your `.env` until the mariadb utf8 dump is ready:
```env
DB_CHARSET=latin1
DB_COLLATION=latin1_general_ci
```
Rebuilding docker containers is not advised yet as it will remove the mysql container from compose.
=> feat: switch to mariadb and convert to utf8mb4

app/Helpers/database/set-claim.php, app/Helpers/database/ticket.php, app/Support/Cache/CacheKey.php
Eliminates ~20ms from every page load by not constantly looking to see how many tickets or expiring claims a user has. Value is from local testing. I'm not sure exactly how that will translate to the server.
I'm uncertain why the queries are happening twice per page. I assume it has to do with having two copies of the nav bar in the returned page source (one with `<nav class="z-20 flex flex-col w-full justify-center lg:sticky lg:top-0">`, and one with `<nav class="z-10 flex flex-col w-full justify-center lg:sticky lg:top-0 lg:hidden">`). That might be something to look into separately as each copy of the `<nav>` is ~40KB.
Cached ticket counts are expired once a day, or immediately when tickets are updated.
Claim information is only cached for one hour at a time. If a user has no claims, …
=> Cache ticket count

app/Helpers/database/player-game.php
Fetching rich presence data from UserAccounts takes 2-5 times longer than fetching it from player_sessions. This attempts to fill as much of the Recent Players list as possible from player_sessions. If 10 rows can be generated, then the UserAccounts table doesn't have to even be looked at.
For games with less than 10 players since the v5 release, the result will be slower because two queries will be executed, but they will be taking less traffic, so that's an acceptable tradeoff.
=> populate as much of Recent Players list as possible from aggregate data

app/Helpers/database/player-achievement.php, app/Helpers/database/user.php, app/Platform/Actions/UpdatePlayerGameMetrics.php, lang/en_US/legacy.php, public/admin.php, public/dorequest.php, public/request/user/award-achievement.php, public/ticketmanager.php
Only accessible to moderators.
After being awarded, the ticket page will reflect the fact that it was manually awarded:
Also note that the "hardcore" text has been removed from the unlock history, and the gold border is displayed instead.
=> Add manual unlock buttons to ticket page

app/Helpers/database/user.php, app/Platform/Actions/ResetPlayerProgress.php, public/request/user/list-games.php, public/request/user/list-unlocks.php
=> use aggregate data for reset progress dropdowns

database/migrations/2012_10_03_133633_create_base_tables.php, docker/mysql/mysql.cnf
Minor cosmetic change: before starting imports on the new server I'd like to get those index names cleaned up. With data in the tables it takes unnecessarily long to change them.
The dumps won't include table schema, only data, meaning that the migrations will define how things are named in the new databases. Another cleanup of migrations to better match current prod as closely as possible happened prior.
=> chore: adjust index names

app/Site/Components/NotificationIcon.php
This currently breaks stage and preview environments:
`"PHP message: PHP Fatal error:  Uncaught ErrorException: Undefined array key "Expired" in /.../app/Site/Components/NotificationIcon.php:61`
=> fix: expiring claims in notifications can be non-existent

public/dorequest.php
missed one in https://github.com/RetroAchievements/RAWeb/pull/1948, only checked `postactivity` and `ping` previously.
=> chore: startsession legacy rich presence & last game save

app/Api/Middleware/LogApiUsage.php, app/Helpers/database/ticket.php, app/Helpers/database/user-activity.php, app/Helpers/database/user-auth.php, app/Support/Cache/CacheKey.php, tests/Unit/CacheKeyTest.php
Do not set timestamps to false on user object - this prevents datetime casting for Created and Updated attributes.
Change ticket `isAllowedToSubmitTickets()` check.
=> fix: user created timestamp not cast to Carbon

resources/views/platform/components/game/current-progress/root.blade.php
Sets the "Your Progress" label to screen readers only on the current-progress component.
**Before**
**After**
=> feat(game): remove 'Your Progress' heading

app/Helpers/render/achievement.php, database/migrations/platform/2023_10_29_000000_update_player_games_table.php
This dramatically improves performance on the two queries to fetch the game's achievement distribution on game pages.
**Benchmark query:**
```sql
-- softcore mode, use NOW() to bypass local performance caching
SELECT
NOW(),
pg.achievements_unlocked AS AwardedCount,
COUNT(*) AS NumUniquePlayers
FROM
player_games AS pg
WHERE
pg.game_id = 228
AND pg.achievements_unlocked > 0
GROUP BY
AwardedCount
ORDER BY
AwardedCount DESC
```
**Before**
4.389s
4.697s
4.282s
4.723s
4.867s
Average: _4.591s_
**After**
38ms
23ms
8ms
24ms
19ms
Average: _22.4ms_
The addition of these indices results in a speedup factor of around 535x. This is especially desirable given the query **runs twice on every game page**.
=> perf(game): add composite indexes for game_id and achievements unlocked

app/Helpers/database/user-activity.php
Prevents actual session end time from being overwritten by the last achievement in the session.
Before:
After:
=> don't overwrite session end time unless newer

app/Platform/Controllers/PlayerCompletionProgressController.php, app/Platform/Services/PlayerProgressionService.php
This PR fixes a bug on user profiles and the user completion progress page where, now that aggregate queries are enabled, games with no achievements unlocked are appearing/counting in these areas as "Unfinished".
We should only count a game as Unfinished if the user has earned at least one achievement for the game. Simply booting a game should not qualify.
@luchaos , this issue is highly visible on your profile for these areas of the UI.
**Before**
**After**
=> fix(user): only count games with at least 1 earned achievement as "Unfinished"

app/Helpers/render/user.php
Resolves an issue on user profiles where the "see more..." link to take the user to the unfiltered Completion Progress page may never appear.
@luchaos, this is another issue that is exhibited on your profile 😅
**Before**
**After**
**Root Cause**
The conditional for determining whether or not to render the filter checkbox was driving the entire div that also contained the "see more" link. I've removed the conditional and its helper function entirely- IMO, they're overkill.
=> fix(user): dont hide profile completion progress widget row

resources/views/components/menu/main.blade.php
Currently, the site is eagerly loading all console icons from the navbar, even if the user never opens the "Games" pane in the navbar.
On mobile with 4G conditions, this eager loading results in a ~1s longer overall page load time across the entire site due to hitting the browser's maximum connections limit. Render-blocking resources downstream are being delayed because of the max connections occupancy. The waterfall can be seen here: https://www.webpagetest.org/video/compare.php?tests=231030_BiDc3Y_EH4-r:3-c:0-e:filmstrip
After this PR, the icons will only load when the user opens the menu (or sees them elsewhere on the page).
=> perf(navbar): don't eagerly load console icons

app/Helpers/render/avatar.php
Should improve perceived performance of large user profile pages in some browsers.
Even though image loading is set to lazy, on profile pages that have a lot of badges, all the badges start rendering+decoding synchronously because they appear above the fold. This deadlocks the UI thread.
More info:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/decoding
https://css-tricks.com/newsletter/249-decoding-async-tree-rings-and-flexbox-gap/
=> perf(avatar): force async decoding

app/Helpers/database/leaderboard.php, public/gameInfo.php
Helps particularly on game pages like 1446, which has many legacy hidden leaderboards that are being calculated for, even though the results are never displayed to end users.
**Perf Before**
162ms
158ms
457ms
165ms
158ms
Average: 161ms
**Perf After**
34ms
32ms
17ms
34ms
34ms
Average: 30ms
Note: Several leaderboards on the site are deliberately kept with a -1 DisplayOrder for other practical purposes. We should not purge the -1 leaderboards from the DB.
=> perf(game): dont compute for hidden leaderboards

app/Helpers/render/user.php, database/migrations/platform/2023_10_30_000000_update_player_achievements_table.php
`getAchievementsEarnedBetween()` is responsible for building the chart to show the user's points progress over the last ~2 weeks.
This is currently very slow for users with a lot of progress on the site, even though it is using denormalized data. After running `EXPLAIN` on the query, I identified the main driver behind this slowness is because the query has to scan potentially tens of thousands of rows on the `player_achievements` table due to a missing compound index.
**Benchmark Query**
```sql
SELECT
COALESCE(pa.unlocked_hardcore_at, pa.unlocked_at) AS Date,
SUM( IF(pa.unlocked_hardcore_at IS NOT NULL, ach.Points, 0)) AS HardcorePoints,
SUM(ach.Points) AS SoftcorePoints
FROM
player_achievements pa
INNER JOIN Achievements AS ach ON ach.ID = pa.achievement_id
INNER JOIN GameData AS gd ON …
```
=> perf(user): optimize getAchievementsEarnedBetween()

resources/views/community/components/active-players/active-players.blade.php
Resolves this issue with the last updated label on the active players widget. "0:37pm" should read "12:37pm".
**Root Cause**
Nullish coalescing in JS only checks for null or undefined. I mistakenly believed because 0 is a falsy value the original implementation would work. It doesn't; it requires an explicit check.
=> fix(active-players): show '12' on hour 0

.env.example, app/Helpers/database/game.php, app/Helpers/util/database.php, app/Site/AppServiceProvider.php, config/database.php
`utf8mb4_unicode_ci` is based on Unicode-4.0.0 which is fairly old. Use `uca1400_ai_ci` collation instead. (see https://jira.mariadb.org/browse/MDEV-27009)
The `utf8mb4_unicode_ci` mariadb container default can stay for now, Laravel will use `uca1400_ai_ci` for migrations. Changing the docker container default to `uca1400_ai_ci` resulted in `SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client`.
I'll look into that another time, not relevant for the server move.
Already migrated/imported local databases can stay as is - no need to change the collations just yet, but can be done if desired.
Fix tilde sort while at it.
Left is `utf8mb4_unicode_ci` collation without sort fix, right is with `uca1400_ai_ci` with the fix. Note the sorting of `Ł`:
=> feat: use MariaDB uca1400_ai_ci and fix game title tilde sort

public/viewtopic.php
It's been almost a year, and the error supposedly fixed by #1276 still pops up every now and then. I have to assume users have bad data in their bookmarks or links in forum posts. While the bad urls should no longer be getting generated, this will also address any that are still floating around.
=> ignore negative offset

public/managehashes.php
Fixes "ErrorException(code: 0): Trying to access array offset on value of type null at /home/forge/retroachievements.org/releases/2023-11-04T091534-5.1.0-27696186/public/managehashes.php:22"
=> fix exception accessing manage hashes page for non-existant game

app/Helpers/database/set-request.php
Remediates an issue where tilde characters in game titles are not being ignored in the sort order.
In the images below, look at the position of the unlicensed title, "Tiles of Fate".
**Before**
**After**
=> fix(setRequestList): remediate user request list sort order issue

app/Helpers/database/game.php
Applies the same adjustments to hub sort order as setRequestList and other places by moving prefixed games from the top to the bottom of the list.
=> fix(game): remediate hub sort order

app/Helpers/render/ranking.php, public/friends.php, public/userInfo.php, resources/views/community/components/user/followed-leaderboard-cta.blade.php
This PR:
* Makes some minor adjustments to the ranking query, swapping `LEFT JOIN` to `INNER JOIN` for a very minor performance improvement.
* Moves the followed users ranking component to _friends.php_.
* Adds a link to user profiles where the component used to be so users know where to find it now.
When following 800 users, the query always runs at less than 300ms for me. At more reasonable following counts, it's around 100ms. With it being off the user profile, it should have much less of an impact on the site.
=> feat: re-enable followed users ranking, move it to Followers page

public/gameInfo.php
This PR resolves an uncaught JS error on game pages that do not have sets, which ultimately results in all kinds of front-end weirdness further downstream.
Because game pages that do not have sets do not render Google charts in the sidebar, the JS trying to act upon those charts is crashing. It's better to just not execute this JS at all.
This issue can be seen in prod on https://retroachievements.org/game/20786 if you open the browser devtools and inspect the Console tab. After this PR, that issue should go away.
=> fix(game): only load google charts if necessary

resources/js/alpine/newsCarouselComponent/newsCarouselComponent.test.ts, resources/js/alpine/newsCarouselComponent/newsCarouselComponent.ts
A trivial UX improvement to the home page news carousel. Show the first slide for significantly longer (~20 seconds) before beginning autoscrolling to slide 2.
Whatever is on the first slide is likely the most important item for incoming users to see, so it should receive more prominence in the component.
=> feat(home): delay autoscrolling on the news' first slide

public/dorequest.php, tests/Feature/Connect/PingTest.php
Fixes
```
Unable to JSON encode payload. Error code: 5 at /home/forge/retroachievements.org/releases/2023-11-05T163253-5.1.2-749d077a/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:108)
[stacktrace]
#0 /home/forge/retroachievements.org/releases/2023-11-05T163253-5.1.2-749d077a/vendor/laravel/horizon/src/RedisQueue.php(46): Illuminate\\Queue\\Queue->createPayload()
...
#8 /home/forge/retroachievements.org/releases/2023-11-05T163253-5.1.2-749d077a/public/dorequest.php(238): App\\Platform\\Events\\PlayerSessionHeartbeat::dispatch()
```
=> fix exception when ping contains invalid UTF-8

app/Helpers/database/user.php
Improves load time of "Community > Developer Stats" page from ~21seconds to ~900ms.
=> split massive dev stats query into several subqueries

app/Helpers/database/game.php, public/gameList.php, tests/Feature/Api/V1/GameListTest.php
Provides substantial performance improvements to the All Games page and individual Developer Stats pages.
Provides minor performance improvements to per-console Games lists and Want to Play Games lists when paginated.
Performance for non-paginated lists is basically unchanged.
=> split massive game list query into several subqueries

tests/Feature/Platform/BeatenGameTest.php
Fixes https://github.com/RetroAchievements/RAWeb/actions/runs/6825993731/job/18564962167
Calling `Carbon::setTestNow` without a timestamp actually disables the time mocking functionality, so if the time changes between lines 216 and 220, the test fails.
=> fix spurious unit test

public/admin.php
Eliminates needs for direct database access to move achievements to a subset, and ensures all appropriate aggregate data gets updated.
=> add admin tool to migrate achievements between games

public/achievementinspector.php, resources/views/platform/components/developer/inspector-toolbox.blade.php
This PR migrates the achievement inspector toolbox component (`/achievementinspector.php?g=1`) to Blade. It also hides the "Set Selected to Progression" and "Set Selected to Win Condition" buttons if the game is either a subset or a test kit.
In a subsequent PR, I will also adjust the logic for these cases in _achievementinfo.php_ and our API calls.
=> feat: migrate inspector toolbox to blade, hide type additions to subsets

public/achievementInfo.php
Related to #2014.
This PR prevents the user from adding types to an achievement if it is a subset or a test kit.
To test:
* You should be able to add types to `/achievement/9`.
* You should get an error if you try to add a type to `/achievement/241312`.
* You should always be able to remove a type, regardless of the game title.
=> fix(achievementInfo): prevent adding types to subsets and test kits

app/Helpers/database/achievement.php, app/Platform/Models/Game.php, public/request/achievement/update-base.php, public/request/achievement/update-type.php, tests/Feature/Connect/UploadAchievementTest.php
This PR updates _update-base.php_ and _update-type.php_ such that if the target game is a subset or test kit, the user cannot set any achievements to Progression or Win Condition. Type removal is still allowed.
**How to test this PR**
Since this PR does not contain the front-end changes of #2014 or #2015, simply open a subset and try to give one of its core achievements a type.
=> fix: block adding types to subsets via web api calls

resources/views/platform/components/game/title.blade.php
=> fix: remediate encoding issue with game titles [V5.2]

resources/views/platform/components/developer-feed/recently-obtained-achievements.blade.php
The descriptions are currently missing on the achievement cards in this table.
**Before**
**After**
=> fix: add achievement descriptions to unlocks table in dev feed [V5.2]

app/Community/Components/ActivePlayers.php
Right now, the active players shown on the dev feed pages still uses the user's cookie-driven saved search for the home page active players. This will result in the wrong results being shown.
After this change, the filter is ignored for this variant of the active players component.
=> fix(feed): ignore default active players filter [V5.2]

app/Helpers/render/achievement.php, app/Support/Shortcode/Shortcode.php
**Before**
**After**
There is still a minor issue with the "Homebrew" tag floating to the right in the [code] block.
=> fix(forum): remediate shortcode rendering for games and achievements [V5.2]

public/request/user/list-currently-active.php, resources/views/community/components/active-players/active-players.blade.php
On its 5 minute refresh interval, the feed is loading all players rather than the filtered list for the developer's games. This PR ensures the list remains focused on only those game IDs.
=> fix(feed): dont show all players on player list refresh [V5.2]

public/admin.php
The `unlockAchievement` function has code that prevents unlocking Unofficial achievements. The `UnlockPlayerAchievementJob` has no similar qualms. Both were being called previously to ensure both new and old data structures were updated. The old data structure is no longer used, so there's no need to try to populate it.
=> allow admins to manually unlock demoted achievements

app/Helpers/database/game.php
fixes
```
SQLSTATE[HY093]: Invalid parameter number (SQL: SELECT  gd.ID, gd.Title, gd.ImageIcon, gd.TotalTruePoints,
...
#7 /home/forge/retroachievements.org/releases/2023-11-17T040722-5.2.1-054ded59/public/gameList.php(31): getGamesListByDev()
```
bindings left over from preliminary query were confounding primary query
=> fix error viewing want-to-play list sorted by date

app/Platform/Controllers/BeatenGamesLeaderboardController.php
This PR resolves an issue where the same user can appear on the beaten leaderboard multiple times on the same page. The issue is easily reproducible by visiting the following route:
```
/ranking/beaten-games?page%5Bnumber%5D=1&filter%5Bsystem%5D=2&filter%5Bkind%5D=all
```
**Before**
**After**
**Root Cause**
This issue occurs when a user has two beaten game awards that occurred at exactly the same timestamp.
=> fix(beaten-leaderboard): dont show the same user multiple times

app/Helpers/shortcode.php
Resolves an issue where posting a link in the forum like:
`https://retroachievements.org/user/Jamiras/progress`
causes username normalization to kick in and submit as `[user=Jamiras]/progress`.
Now, URLs with path params are not normalized.
=> fix(forum): dont normalize user links with path params

app/Platform/Controllers/PlayerCompletionProgressController.php, app/Platform/RouteServiceProvider.php, resources/views/platform/completion-progress-page.blade.php, tests/Feature/Platform/PlayerCompletionProgressTest.php
Right now, the Completion Progress page requires authentication to view.
This PR removes the auth gate and adds a meta description to the page for crawlers.
=> feat(user): remove auth gating from completion progress

resources/views/platform/components/beaten-games-leaderboard/pagination-controls.blade.php
This PR remediates an issue where manual pagination on the beaten leaderboard resets a currently active console filter.
**To reproduce**
Navigate to:
```
http://localhost:64000/ranking/beaten-games?page%5Bnumber%5D=1&filter%5Bsystem%5D=7
```
Attempt to visit page 4 via the pagination control at the bottom of the page.
Observe that your system filter is no longer applied.
**Root Cause**
The JS code was stripping the currently applied system filter.
=> fix(beaten-leaderboard): remediate manual pagination with console filter

app/Platform/Controllers/BeatenGamesLeaderboardController.php
Resolves a regression introduced in https://github.com/RetroAchievements/RAWeb/pull/2035 which causes the last game_id to not be correctly picked.
**Before (also reproducible on prod)**
**After**
Duplicate rows (which #2035 resolved) are still correctly omitted after this change.
=> fix(beaten-leaderboard): correctly pick the last beaten game id

public/request/achievement/update-base.php
Resolves https://discord.com/channels/310192285306454017/310195377993416714/1175593754028158986.
**Root Cause**
When editing an achievement belonging to a subset, there isn't a type field anymore. Therefore, we need to add some safety before we navigate into the "type" array key of the `$input` variable.
=> fix: remediate subset achievement update error

app/Platform/Controllers/PlayerCompletionProgressController.php, resources/views/platform/completion-progress-page.blade.php, resources/views/platform/components/completion-progress-page/meta-panel/sort-order.blade.php
This PR adds two new sort orders to the Completion Progress page:
Game Title: A - Z
Game Title: Z - A
All the sort options have also been relabeled to hopefully improve the intuitiveness of the sort select control.
=> feat(completion-progress): add alphabetical sorting

app/Helpers/database/set-request.php, public/request/user-game-list/set-requests.php, public/setRequestList.php, public/userInfo.php
eliminates a ~40ms query from my profile page
=> only fetch claimants for set requests on set requests page

resources/views/platform/components/game-list-item/index.blade.php
Resolves a minor issue on user profiles, specifically with mobile. The animation to expand a game's list of achievements clips the edges of the badges while the animation is running.
**Before**
https://github.com/RetroAchievements/RAWeb/assets/3984985/cad81e7a-d76b-4e58-9761-3f30ab13ddc7
**After**
https://github.com/RetroAchievements/RAWeb/assets/3984985/2100ab32-dec9-4eca-aac1-9f467f80354c
=> fix(user): remediate achievement badge clipping on mobile animation

app/Platform/Commands/MigrateMissableAchievementsToType.php
Updates `$usesLegacyMissableTag` to account for "[m]" starting at the beginning of achievement titles. Has already been executed on prod.
=> fix: update sync conditional in missable migration script

app/Helpers/render/achievement.php
Resolves this issue:
**To Reproduce**
* Find a profile that has a subset in its recent activity.
* Hover over an achievement icon and observe the achievement card.
After this PR, the achievement card text should be rendered correctly, and the JS errors previously seen on the forum should not re-emerge.
=> fix: resolve achievement card game title rendering issue

app/Helpers/database/user-auth.php, app/Helpers/database/user-password-reset.php, app/Site/FortifyServiceProvider.php, public/request/auth/register.php, public/request/auth/reset-password.php, public/request/auth/update-password.php, tests/Feature/Connect/LoginTest.php
Makes sure that resetting passwords locally does not subsequently use the wrong algorithm. Changing the hashing configuration for verification is not required.
Pretty much all of the affected code will be replaced with standard Laravel/Fortify features.
=> fix: always hash passwords with the configured algorithm

app/Helpers/database/player-history.php, public/API/API_GetAchievementOfTheWeek.php, public/API/API_GetAchievementsEarnedBetween.php, public/API/API_GetAchievementsEarnedOnDay.php, public/API/API_GetUserRecentAchievements.php, tests/Feature/Api/V1/UserRecentAchievementsTest.php, tests/Feature/Api/V1Test.php
Resolves https://github.com/RetroAchievements/RAWeb/discussions/2081#discussioncomment-7794278.
Adds "Type" value to achievements returned in:
* API_GetAchievementsEarnedBetween
* API_GetAchievementsEarnedOnDay
* API_GetUserRecentAchievements
* API_GetAchievementOfTheWeek
=> feat(api): add 'Type' to more endpoint responses

app/Community/Controllers/MessageController.php
Fixes '{s}' being left in the subject field when clicking links going to the old create message page.
=> ignore placeholders not replaced by missing-page-redirector

app/Helpers/database/player-achievement.php, public/API/API_GetAchievementOfTheWeek.php, public/API/API_GetAchievementUnlocks.php, public/achievementInfo.php, resources/views/platform/components/game/achievements-list/achievements-list-item.blade.php, tests/Feature/Api/V1/AchievementOfTheWeekTest.php, tests/Feature/Api/V1Test.php
This PR adds type indicators to the achievement info pages, eg:
```
/achievement/9
```
**Before**
**After**
From a technical POV, this is achieved by reusing the achievement list item component from game pages.
To facilitate displaying hardcore unlock progress in the component, a slight modification was made to `getAchievementUnlocksData()`, which has a minor impact on two API endpoints.
=> feat(achievement): show type indicators on the info page

public/history.php
Resolves #2101.
Currently, the Google Chart on _history.php_ is shifted 1 month into the future. For example, at https://retroachievements.org/history.php?u=Jamiras:
**Root Cause**
Months in JavaScript date objects are 0-indexed. We need to compensate for this when constructing the x-axis values.
=> fix(history): remediate chart incorrect x-axis

public/API/API_GetUserSummary.php
Replaces `max` validation on API_GetUserSummary.php to better support backwards compatibility with legacy clients.
Now, if a consumer asks for a large sum of recent games, we force a cap of 100 and do not error the response.
=> feat(api): replace max validation on API_GetUserSummary with a cap

app/Platform/Controllers/GameHashController.php, database/migrations/2023_12_16_000000_update_gamehashlibrary_table.php, resources/views/platform/components/manage-hashes/hash-entity.blade.php
In addition to .zip, users can now use .7z URLs from the RAPatches repo on the new Manage Hashes page (`game/1/hashes/manage`).
=> feat(hashes): allow .7z patch urls

resources/views/components/community/user-card.blade.php
Resolves an issue where if a motto is empty, the space for the motto in the user card still appears:
=> fix(user-card): dont show empty motto

app/Helpers/database/leaderboard.php, app/Helpers/render/leaderboard.php, app/Platform/Enums/ValueFormat.php, public/leaderboardList.php, public/leaderboardinfo.php, resources/views/platform/components/developer-feed/recent-leaderboard-entries.blade.php, tests/Unit/ValueFormatTest.php
Allows the use of new formats defined in https://github.com/RetroAchievements/rcheevos/pull/305 in leaderboards.
Consolidates labels and formatting functions into helpers on enum.
=> add additional leaderboard formats

public/userInfo.php, resources/views/community/components/user/recent-progress.blade.php
Migrates the user profile Recent Progress chart to Blade. Chart colors have been changed to mirror the distribution chart on game pages (gold for hardcore, gray for softcore). Other than that, implementation details are unchanged.
**Before**
**After**
=> refactor(user): migrate Recent Progress chart to blade

public/gameInfo.php
Simple tweak to the game page to remove the Achievements Distribution chart when viewing unofficial achievements.
Right now, the component is a bit disorienting when viewing unofficial. Unlocks are not shown on the achievements list (I believe this is correct), but they are shown on the distribution chart.
=> fix(game): remove distribution chart when viewing unofficial achievements

app/Community/Models/ForumTopicComment.php, app/Helpers/database/forum.php, app/Site/Models/User.php, public/viewtopic.php, resources/views/community/components/forum/post.blade.php
Purely to better prepare for rendering modern roles - rather than augmenting the legacy `mysqli` calls it would make more sense if we used Eloquent ORM relationships here to fetch the user's roles.
=> refactor(viewtopic): migrate fetching comments to Eloquent ORM

public/achievementInfo.php
Fixes a minor issue on _achievementInfo.php_ where the current ticket count is not pluralized.
**Before**
**After**
=> fix(achievementInfo): pluralize ticket count

app/Filament/Resources/AchievementResource.php, app/Platform/Policies/AchievementPolicy.php
As discussed, there's no valid use-case for us to allow force deleting soft-deletable models.
=> feat(filament): remove force delete feature from achievement resource and policy

resources/js/livewire.d.ts
Gets rid of `Unchanged files with check annotations` when reviewing PRs:
I couldn't find a better solution for now.
=> chore(eslint): ignore Livewire any type

app/Helpers/database/game.php
Implements @Jamiras's suggestion from https://github.com/RetroAchievements/RAWeb/pull/2179#discussion_r1468890568:
> [gameslist and officialgameslist] could be hugely improved by just querying the ID/Title instead of doing a full data dump and extracting the Title.
**`gameslist` Before (ms)**
1300ms
1230ms
1190ms
1170ms
1190ms
Average: 1216ms
**`gameslist` After (ms)**
359ms
358ms
352ms
357ms
355ms
Average: 356ms (around a 3.5x speed increase)
=> perf(connect): optimize gameslist and officialgameslist routines

app/Helpers/database/user-email-verify.php, app/Helpers/database/user-permission.php
Allows to use `$user->isForumVerified()`, `$user->hasVerifiedEmail()`, and `$user->isBanned()` in upcoming PRs.
Preparation for `TODO drop ManuallyVerified in favor of forum_verified_at`.
Backfill timestamps - low precision is acceptable in this case:
```sql
UPDATE
UserAccounts
SET
email_verified_at = Created
WHERE
Permissions > 0
AND email_verified_at IS NULL;
UPDATE
UserAccounts
SET
forum_verified_at = Created
WHERE
ManuallyVerified = 1
AND forum_verified_at IS NULL;
UPDATE
UserAccounts
SET
banned_at = Updated
WHERE
Permissions < 0
AND banned_at IS NULL;
```
=> feat(permissions): store new permissions related timestamps

app/Platform/Services/GameListService.php
This PR adds award indicators to everything using `GameListService` that shows user progress.
**Before**
**After**
=> feat: add award indicators to game lists

app/Support/Sync/SyncTrait.php
Fixes `Undefined property: App\Platform\Commands\SyncLeaderboardEntries::$Model`
=> fix: sync model access

app/Platform/RouteServiceProvider.php, config/missing-page-redirector.php, resources/views/components/menu/account.blade.php, resources/views/platform/components/game/link-buttons/index.blade.php
REST routes should stay clean to not cause potential conflicts with `game/{id}`.
Temporarily redirects `/game/suggest` to `/games/suggest` so nobody currently accessing the page should notice. Redirect can be removed in the next release.
=> fix: move suggestions route

public/controlpanel.php, public/createtopic.php, public/editpost.php, public/submitnews.php, public/viewtopic.php, resources/js/utils/loadPostPreview.ts, resources/views/components/input/shortcode-textarea.blade.php
Force `.animate-spin` to only appear when loading spinner SVGs are actually visible.
=> perf: add .animate-spin just-in-time

resources/views/community/components/user/recent-progress.blade.php
Resolves the "time travel" issue currently being exhibited in the Recent Progress chart on user profiles.
**Root Cause**
`$nextMonth` needs to account for JavaScript 0-indexing months in the native `Date` object.
**Before**
**After**
=> fix(recent-progress): remediate dates being out of order

public/request/user/update-email.php
Followup for https://github.com/RetroAchievements/RAWeb/pull/2189#issuecomment-1919708289:
```sql
-- Reset any timestamps that were not unset after email changes (none on production so far since v6 release, just to be sure)
UPDATE
UserAccounts u
SET
u.email_verified_at = NULL
WHERE
u.Permissions < 1
AND u.email_verified_at IS NOT NULL;
-- Pull email_verified_at from server comments, affecting ~345k user entries
UPDATE
UserAccounts u
SET
u.email_verified_at = (
SELECT
MAX(c.Submitted) -- take latest verification comment
FROM
`Comment` c
WHERE
c.ArticleID = u.ID
AND c.ArticleType = 9 # User moderation
AND c.UserID = 14188 # Server user
AND c.Payload = 'Server set account type to Registered'
GROUP BY
c.ArticleID
)
WHERE
u.Permissions > 0
AND u.email_verified_at IS NULL;
-- Update remaining …
```
=> fix(email-verification): unset email_verified_at when changing email address

app/Helpers/database/release.php, resources/views/components/menu/main.blade.php
Adds system 102 to the valid systems list and enables the "Standalone" nav option under the Games menu.
=> feat: enable Standalone system and Final Fantasy XI

public/userInfo.php, resources/views/community/components/user/recent-progress.blade.php
Resolves https://discord.com/channels/310192285306454017/1203067172470005870.
If the user has any points, the "more..." link will always appear and direct to the user's history page.
=> fix(user): always show 'more...' for Recent Progress if user has any points

public/history.php
This PR adjusts the History page line chart colors to be consistent with chart colors used for Recent Progress on the user profile.
**Before**
**After**
=> fix(history): use the correct hardcore and softcore chart colors

resources/views/platform/components/manage-hashes/hash-entity.blade.php, resources/views/platform/components/manage-hashes/hashes-list.blade.php
Fixes a bug on the Manage Hashes page where when the user attempts to unlink a hash, the hash name in the `confirm()` is wrong.
**Root Cause**
The JS function responsible for popping this confirm was being redefined, as it was a `<script>` tag being rendered in a loop.
I've lifted the `<script>` tag up one level in the tree and changed how `hashName` is defined in the JS code.
=> fix(manage-hash): show correct hash name on unlink confirm

app/Platform/Services/GameListService.php
Resolves https://discord.com/channels/310192285306454017/1203413537247076362.
**Before**
Games with categories on prod are currently sorted primarily by title, not category. Eg:
```
~AAA~ Game A
~BBB~ Game B
~AAA~ Game C
```
**After**
Now, category is given the priority.
```
~AAA~ Game A
~AAA~ Game C
~BBB~ Game B
```
=> fix(GameListService): sort category game titles primarily by category and then by title

app/Helpers/render/code-note.php, resources/views/pages-legacy/codenotes.blade.php
This PR adds a minor quality of life improvement to editing code notes while on the web.
If the user attempts to reload the browser, navigate away, or cancel editing while a row is in edit mode and dirty/changed, a confirm will appear informing them they could accidentally discard any changes.
Note: `confirmationMessage` will not appear in all browsers due to security reasons. Chrome, for example, forces a default message to appear.
=> feat(code-notes): pop a warning if attempting navigation while in edit mode

app/Platform/Actions/ResetPlayerProgress.php
Resolves https://discord.com/channels/310192285306454017/1204092628182900807.
It's currently possible to reset progress on a game and fall into a circumstance where `PlayerStat` records for the user ID are not updated.
After this is merged and deployed, a full resync on `PlayerStat` records should be run via:
```
sail artisan ra:platform:player:update-stats
```
=> fix: dispatch UpdatePlayerStatsJob on ResetPlayerProgress execution

docker/8.2/supervisord.conf, resources/views/layouts/components/body-end.blade.php
As a reminder: with our Laravel Sail setup, Octane runs at http://localhost:64008/ by default.
This adds a watcher to restart the Octane process after file changes.
An additional item is displayed in the bottom debug area:
=> feat(octane): enable Octane reloads in Docker

app/Community/Components/UserProfileMeta.php, app/Models/User.php, app/Platform/Controllers/BeatenGamesLeaderboardController.php, resources/views/components/beaten-games-leaderboard/leaderboard-card-row.blade.php, resources/views/components/beaten-games-leaderboard/leaderboard-table-row.blade.php, resources/views/components/beaten-games-leaderboard/leaderboard-table.blade.php, resources/views/components/user/profile/arranged-stat-items.blade.php, resources/views/components/user/profile/player-stats.blade.php, resources/views/components/user/profile/stat-element.blade.php, resources/views/pages/ranking/beaten-games.blade.php
This PR aims to more closely align the new beaten games stat on user profiles to the existing beaten games leaderboard feature on the site:
* The beaten games leaderboard now accepts a `filter[user]` query param, which redirects the user to the correct page for the target user.
* If the target user can't be found or has no ranking, there is a redirect to the first page of the leaderboard.
* The "Total games beaten" stat now has an `href`, which leverages this new `filter[user]` query param to deep link into the beaten games leaderboard from the statistic itself. The link takes the user to the number of retail beaten games.
=> feat(user): give beaten games stat an href

resources/views/components/game/game-list.blade.php
Resolves https://discord.com/channels/310192285306454017/1206007100308856942.
**Before**
**After**
=> fix: remediate z-index issue with progress indicators

app/Platform/Controllers/PlayerCompletionProgressController.php, app/Platform/Services/PlayerProgressionService.php, resources/views/components/completion-progress-page/meta-panel/console-filter.blade.php, resources/views/components/game-list-item/index.blade.php, resources/views/components/game-list-item/primary-meta.blade.php, resources/views/pages/user/[user]/progress.blade.php
Resolves https://discord.com/channels/310192285306454017/1206427760491237396.
It is now possible to view "Events" progress on the Completion Progress page:
This also means it's possible to go to another user's Completion Progress page and view their Events progress as well.
Unless explicitly filtering by system ID 101, these remain excluded from every other viewable context offered by the page. This should help alleviate some pain that a few achievement developers are currently experiencing.
=> feat(completion-progress): allow viewing Events progress

resources/views/components/game/game-list.blade.php
Resolves an issue that's observable here:
https://retroachievements.org/game/3105
Games do not exist in this hub. The meta surface and empty state are redundant and should not be visible.
**Before**
**After**
=> fix(game-list): don't show empty state where there are no filterable games

docs/CONTRIBUTING.md
Adds a note in _CONTRIBUTING.md_ about documenting API changes:
> - **Document any change in behaviour** - Make sure the `README.md` and any other relevant documentation are up-to-date. If you are changing the API in some way, please also open an accompanying PR in [the api-docs repository](https://github.com/RetroAchievements/api-docs).
=> docs(CONTRIBUTING.md): add note about api-docs

resources/views/pages-legacy/reportissue.blade.php
Fixes a broken link when the user types "manual unlock" into the Report Issue page.
https://discord.com/channels/476211979464343552/1002694942826704936/1209145643990523936
=> update link for manual unlock instructions

app/Helpers/database/user-activity.php, resources/views/pages-legacy/usergameactivity.blade.php
Fixes an issue where an achievement unlocked between two sessions doesn't appear in either session. Originally reported here https://discord.com/channels/476211979464343552/1207063525248344095/1210362941921038387 with a manually unlocked achievement.
Also updated the display to report when an achievement was manually unlocked.
=> fix session classification for manual unlocks

app/Platform/Controllers/SystemController.php, resources/views/components/game/game-list.blade.php, resources/views/pages/system/[system]/games.blade.php
Resolves an issue where viewing the system games list for an unsupported system no longer allows the user to filter into games without achievements.
**Before**
**After**
=> fix(system-games): show filters meta surface for unsupported console ids

resources/views/pages-legacy/controlpanel.blade.php
Resolves an issue where web API keys are no longer rendering on controlpanel.php. "$apiKey" is currently rendering on prod.
This is happening because the variable isn't wrapped in handlebars `{{ }}`.
=> fix(controlpanel): render web api keys properly

resources/views/pages-legacy/achievementInfo.blade.php
Resolves a regression from the Folio changes where achievement title tag content may not be rendered correctly.
**Before**
**After**
=> fix(achievementInfo): prevent escaping the page title

app/Support/Shortcode/Shortcode.php
Resolves https://discord.com/channels/310192285306454017/1213223210942734448.
To repro, try using this embed URL:
```
https://clips.twitch.tv/NastyConcernedBeanWholeWheat-J9z5FEl1gMo5EUYW
```
Twitch clips can now have a `-[hash]` suffix, which is not supported by `autoEmbedTwitch()`'s current URL pattern. This PR slightly adjusts the pattern so these URLs are now supported.
**Before**
**After**
=> fix(Shortcode): remediate issue with new twitch clip url pattern

resources/js/alpine/tooltipComponent/utils/renderTooltip.ts
This PR resolves an issue on game lists where tooltips can appear underneath table sticky headers. To repro, go to a hub and group it by console.
**Before**
**After**
=> fix(tooltip): raise z-index value

resources/views/components/user/progression-status/legend.blade.php, resources/views/components/user/progression-status/root.blade.php, resources/views/pages-legacy/userInfo.blade.php
This PR resolves some padding issues at the LG breakpoint in the Progression Status component container. It also slightly shifts the "Dynamic widths" checkbox up by 2px to be better aligned with the legend on SM+ breakpoints.
**Before**
**After**
=> fix(user): remediate padding issues on progression status container

resources/views/pages-legacy/achievementInfo.blade.php
Remediates a small issue where syntax highlighting in _achievementInfo.blade.php_ is broken past a certain point in the code.
Also adds some margins to the page around embeds and the comments section.
**Before**
**After**
=> chore(achievementInfo): fix issue with IDE syntax highlighting

app/Platform/Controllers/SystemController.php, app/Platform/Services/GameListService.php
Resolves an issue where visiting the `/system/101/games` route returns no results.
**Before**
**After**
=> fix(SystemController): allow viewing 'Events' games

resources/views/components/base/button/submit.blade.php, resources/views/components/base/form-actions.blade.php, resources/views/components/base/form-field.blade.php, resources/views/components/base/form/input.blade.php, resources/views/components/base/form/input/checkbox.blade.php, resources/views/components/base/form/search.blade.php, resources/views/components/base/form/select.blade.php, resources/views/components/base/form/textarea.blade.php, resources/views/components/base/form/user-select.blade.php, resources/views/pages-legacy/createtopic.blade.php, resources/views/pages-legacy/editpost.blade.php, resources/views/pages-legacy/viewtopic.blade.php, resources/views/pages/message-thread/[messageThread].blade.php, resources/views/pages/messages/create.blade.php
Modifies the reply UI for forums & messages to resolve some layout issues, especially on mobile.
**Before**
**After**
=> fix: remediate layout issues with forums/messages reply ui

app/Helpers/database/code-note.php, app/Models/MemoryNote.php, app/Platform/Concerns/ActsAsDeveloper.php, database/migrations/platform/2024_03_16_000000_update_codenotes_table.php, resources/views/components/game/claim-info.blade.php
Sorry, I'm going to have a few of these 😅
This PR renames `AuthorID` to `user_id` in the `CodeNotes` table. Additionally, `AuthorID` was missing a FK relationship to the `UserAccounts` table. The migration introduced in this branch adds this relationship.
=> refactor(MemoryNote): rename AuthorID to user_id, add foreign key

database/seeders/GamesTableSeeder.php
This PR resolves a failure in `GamesTableSeeder` which is occurring due to a foreign key constraint. The failure is caused by changes from https://github.com/RetroAchievements/RAWeb/pull/2283.
`game_hash_sets` and `game_hash_set_hashes` are both going to be removed. It is no longer necessary to attempt to seed `$gameHashSets()`.
The seeder now directly adds rows for `$game->hashes()` without going through `$gameHashSets()`.
=> chore(GamesTableSeeder): don't seed gameHashSets

app/Helpers/database/search.php, app/Helpers/database/subscription.php, app/Helpers/database/user-activity.php, app/Models/Comment.php, database/migrations/community/2024_03_16_000001_update_comment_table.php
**BEFORE EXECUTING THE MIGRATION, YOU MUST RUN:**
```sql
DELETE FROM Comment WHERE NOT EXISTS (
SELECT 1 FROM UserAccounts WHERE ID = Comment.UserID
);
```
---
This PR renames `UserID` to `user_id` in the `Comment` table. Additionally, `UserID` was missing a FK relationship to the `UserAccounts` table. The migration introduced in this branch adds this relationship.
=> refactor(Comment): rename UserID to user_id, add foreign key

app/Helpers/database/forum.php, app/Models/ForumTopic.php, database/factories/ForumTopicFactory.php, database/migrations/community/2024_03_22_000000_update_forum_topic_table.php
**Before the migration:**
```sql
UPDATE ForumTopic
SET AuthorID = NULL
WHERE AuthorID NOT IN (
SELECT ID FROM UserAccounts
);
```
In my local DB, this updates 0 records, but this should resolve any integrity issues.
---
This PR renames `AuthorID` to `author_id` on the `ForumTopic` table. Additionally, `AuthorID` was missing a FK relationship to the `UserAccounts` table. The migration introduced in this branch adds this relationship.
=> refactor(ForumTopic): rename AuthorID to author_id, add foreign key

app/Helpers/database/ticket.php, app/Helpers/database/user.php, app/Models/Ticket.php, app/Platform/Concerns/ActsAsDeveloper.php, app/Platform/Concerns/ActsAsPlayer.php, database/migrations/community/2024_03_16_000001_update_ticket_table.php, tests/Feature/Api/V1/TicketDataTest.php
**BEFORE RUNNING THIS MIGRATION, YOU MUST EXECUTE:**
```sql
-- Command One (this resolves around ~13 rows with integrity issues)
UPDATE Ticket
LEFT JOIN UserAccounts ON Ticket.ReportedByUserID = UserAccounts.ID
SET Ticket.ReportedByUserID = NULL
WHERE UserAccounts.ID IS NULL;
-- Command Two (this probably won't do anything)
UPDATE Ticket
LEFT JOIN UserAccounts ON Ticket.ResolvedByUserID = UserAccounts.ID
SET Ticket.ResolvedByUserID = NULL
WHERE UserAccounts.ID IS NULL;
```
This PR renames two columns on the `Ticket` table:
* `ReportedByUserID` -> `reporter_id`
* `ResolvedByUserID` -> `resolver_id`
Additionally, foreign key relationships are added between these columns to `UserAccounts.ID`.
`User` and `Ticket` models are updated so Eloquent ORM is aware of the relationships. I shuffled …
=> refactor(Ticket): rename reporter/resolver user columns and add foreign keys

README.md, app/Actions/ClearAccountDataAction.php, app/Community/Concerns/ActsAsCommunityMember.php, app/Helpers/database/subscription.php, app/Models/Subscription.php, database/migrations/2012_10_03_133633_create_base_tables.php, database/migrations/platform/2024_03_17_000000_update_subscription_table.php
This PR updates the `Subscription` table to get it more closely aligned with Laravel best practices.
A migration has been added which performs the following:
* Drop the combined `[SubjectType, SubjectID, UserID]` primary key.
* Add a `id` column as the new primary key.
* Rename all columns:
* `SubjectType` -> `subject_type`
* `SubjectID` -> `subject_id`
* `UserID` -> `user_id`
* `State` -> `state`
* `Created` -> `created_at`
* `Updated` -> `updated_at`
* Change `user_id` to an unsigned big integer.
* Add a unique constraint to `[subject_type, subject_id, user_id]`.
* Add a foreign key from `user_id` to `UserAccounts.ID`.
* Rename `Subscription` to `subscriptions`.
Additionally, the `Subscription` and `User` Eloquent models have been updated.
=> refactor(Subscription): rename columns and adjust primary/foreign keys

app/Helpers/database/leaderboard.php, app/Models/Leaderboard.php, database/factories/LeaderboardFactory.php, database/migrations/platform/2024_03_30_000000_update_leaderboarddef_table.php
**Before executing the migration, run:**
```sql
-- LeaderboardDef, clear orphaned Author values
UPDATE LeaderboardDef lb
SET Author = NULL
WHERE Author NOT IN (
SELECT User FROM UserAccounts
);
```
**After executing the migration, run:**
```sql
-- LeaderboardDef, populate author_id values
UPDATE LeaderboardDef lb
JOIN UserAccounts ua on lb.Author = ua.User
SET lb.author_id = ua.ID;
```
---
This PR adds an `author_id` column to the `LeaderboardDef` table. This column has a foreign key to `UserAccounts.ID`. Additionally, `SubmitNewLeaderboard()` now writes to this new column.
=> refactor(Leaderboard): add author_id column and double writes

app/Actions/ClearAccountDataAction.php, app/Community/Concerns/ActsAsCommunityMember.php, app/Helpers/database/user-relationship.php, app/Models/UserRelation.php, public/request/user/update-relationship.php, tests/Feature/Connect/AchievementWonDataTest.php
This PR rewrites the `changeFriendStatus()` helper function to use Eloquent ORM. As part of this rewrite, the `user_id` and `related_user_id` values are now populated into the database.
Additionally, the User model's `following()` and `followers()` relationships have been updated to utilize these values.
The following SQL needs to be run **after merge/deployment** to delete orphaned records and to populate values for existing records:
```sql
-- Friends, delete orphaned User records
DELETE FROM Friends
WHERE User NOT IN (SELECT User FROM UserAccounts);
-- Friends, delete orphaned Friend records
DELETE FROM Friends
WHERE Friend NOT IN (SELECT User FROM UserAccounts);
-- Friends, populate user_id values
UPDATE Friends f
JOIN UserAccounts ua on f.User = ua.User
SET f.user_id = ua.ID;
-- …
```
=> refactor(Friends): add double writes for user_id and related_user_id values

app/Helpers/database/user-permission.php
Fixes
```
addArticleComment(): Argument #3 ($articleID) must be of type array|int, null given, called in /home/forge/retroachievements.org/releases/2024-04-11T181031-6.3.0-a94e4522/app/Helpers/database/user-permission.php on line 124 {"userId":75956,"exception":"[object] (TypeError(code: 0): addArticleComment(): Argument #3 ($articleID) must be of type array|int, null given, called in /home/forge/retroachievements.org/releases/2024-04-11T181031-6.3.0-a94e4522/app/Helpers/database/user-permission.php on line 124 at /home/forge/retroachievements.org/releases/2024-04-11T181031-6.3.0-a94e4522/app/Helpers/database/user-activity.php:61)
[stacktrace]
#0 /home/forge/retroachievements.org/releases/2024-04-11T181031-6.3.0-a94e4522/app/Helpers/database/user-permission.php(124): addArticleComment() …
```
=> fix error logging dropped claim due to demoting user

app/Actions/ClearAccountDataAction.php, app/Community/Components/UserActivityFeed.php, app/Community/Concerns/ActsAsCommunityMember.php, app/Models/Achievement.php, app/Models/Game.php, resources/views/components/game/compare-progress.blade.php
Renames all `BelongsToMany<User>` model relations to more clearly designate actual `User` models are being selected:
* `relationships` -> `relatedUsers`
* `inverseRelationships` -> `inverseRelatedUsers`
* `following` -> `followedUsers`
* `followers` -> `followerUsers`
* `players` -> `playerUsers`
=> refactor: rename BelongsToMany<User> model relations

database/migrations/platform/2024_03_17_000000_update_subscription_table.php
https://discord.com/channels/476211979464343552/1159595979746582602/1225254512319533087
```
2024_03_17_000000_update_subscription_table ............................................................................................. 3ms FAIL
Illuminate\Database\QueryException 
SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table definition; there can be only one auto column and it must be defined as a key (Connection: mysql, SQL: alter table `Subscription` drop primary key)
```
Changes made to the base schema in #2298 cause prevent the migration added in that PR from completing. I've updated the migration to handle both paths (I think).
=> prevent error migrating fresh database

resources/views/components/game/link-buttons/game-link-button.blade.php, resources/views/pages/user/[user]/game/[game]/compare.blade.php
Resolves https://discord.com/channels/476211979464343552/1026595325038833725/1229087996075315351.
Additionally, modifies some of the link button styles so the icon and text are now better aligned along the center of the button.
**Before**
**After**
=> fix(game-compare): remediate link button size issue on LG and lower

app/Helpers/render/achievement.php
This PR resolves an issue observable on /achievementList.php. If you hover over one of the achievement titles, you'll see a tooltip with a broken badge.
This is being caused by a logic error in render/achievement.php.
**Before**
**After**
=> fix(achievement): show badge on tooltips even when `$icon` is false

database/migrations/community/2024_04_13_000000_update_gamedata_table.php
**Before running the migration, execute:**
```sql
UPDATE GameData g
LEFT JOIN ForumTopic f ON g.ForumTopicID = f.ID
SET g.ForumTopicID = NULL
WHERE f.ID IS NULL AND g.ForumTopicID IS NOT NULL;
```
---
This PR adds a migration which changes `GameData.ForumTopicID`'s field type and gives it a foreign key to `ForumTopic.ID`.
=> chore: add foreign key to GameData.ForumTopicID

app/Platform/Enums/ValueFormat.php, tests/Unit/ValueFormatTest.php
https://discord.com/channels/310192285306454017/310195377993416714/1228338799138967554
also changes the order to prioritize unshifted values over shifted ones and prefixes the fixed sizes with "Value"
=> allow SECS_AS_MINS formatting for leaderboards

app/Helpers/render/game.php
Resolves https://github.com/RetroAchievements/RAWeb/issues/2396.
Currently, an extra column is being added to the Achievement Distribution chart if bucketing is not enabled for the game.
Screenshots below are from game 3609.
**Before**
**After**
=> fix(game): don't add an extra bucket to achievement distribution

resources/views/components/forum/post-comment-meta.blade.php
In `submitTopicComment()`, we're now always setting `DateModified` due to the Eloquent ORM version. I believe logically this is correct, but the UI now needs to ensure that `DateModified` is different from `DateCreated`.
=> fix(forum): don't show post edit date unless it's different from create date

resources/views/components/game/leaderboards-listing/index.blade.php
Resolves a regression on game pages. Leaderboards are not currently sorted by `DisplayOrder`. Easily visible on game 1446.
**Before**
**After**
=> fix(game): sort leaderboards by displayorder

resources/views/pages-legacy/userInfo.blade.php
Resolves a regression on user profiles where user wall comments do not appear if the current user is unauthenticated.
Screenshots from http://localhost:64000/user/WCopeland while not signed in.
**Before**
**After**
=> fix(user): show user walls even while unauthenticated

app/Support/Shortcode/Shortcode.php
If `[link]` is malformed, return an empty string.
Unfortunately, we have no way to access the original `$input` to use that as a fallback. This is a stopgap fix to prevent the page from crashing outright.
=> fix(Shortcode): prevent potential crash from malformed link

app/Helpers/database/leaderboard.php
Resolves this display/ranking issue: https://discord.com/channels/476211979464343552/1026595325038833725/1238308585931538503
`created_at` shouldn't be null for these records, but `updated_at` should probably be the source of truth for submission/ranking placement.
=> fix(leaderboard): favor updated_at over created_at

resources/views/components/game/leaderboards-listing/leaderboards-list-item.blade.php
Currently, ties are not sorting by earliest submission date in the new component. This PR resolves that issue.
Reproducible on `/game/1462`.
Actual leaderboard standings:
**Before**
**After**
=> fix: add missing orderBy to leaderboards-list-item

app/Helpers/util/mail.php
https://discord.com/channels/476211979464343552/1026595325038833725/1238961731741552790
Fixes duplicate https://retroachievements.org in links in emails for ticket comments
=> fix double server in ticket comment url

app/Models/Ticket.php, app/Platform/Services/TicketListService.php, resources/views/components/ticket/ticket-list.blade.php, resources/views/pages/achievement/[achievement]/tickets.blade.php, resources/views/pages/game/[game]/tickets.blade.php, resources/views/pages/tickets/index.blade.php, resources/views/pages/user/[user]/tickets.blade.php
https://discord.com/channels/476211979464343552/1002693810037477377/1238989109029244988
The column was previously shown if the filter included resolved/closed tickets. I've restored that logic, but the column now appears after the reported by date instead of between it and the reporter.
Also fixes display of reporter/resolver for deleted users.
=> show resolver when filtering on resolved tickets

app/Actions/ClearAccountDataAction.php, app/Models/ForumTopicComment.php, app/Models/PlayerStat.php, app/Platform/Concerns/ActsAsPlayer.php, database/factories/PlayerStatFactory.php, tests/Feature/Platform/Action/ClearAccountDataTest.php
`player_stats` currently has orphaned records from deleted users. These appear as empty slots on the Beaten Games Leaderboard. One such instance is directly observable at this URL:
https://retroachievements.org/ranking/beaten-games?page%5Bnumber%5D=1&filter%5Bsystem%5D=39&filter%5Bkind%5D=retail
This PR adds a line to `ClearAccountDataAccount` to delete player stats records. We should also run the following query:
```sql
DELETE ps
FROM player_stats ps
INNER JOIN UserAccounts ua ON ps.user_id = ua.ID
WHERE ua.Deleted IS NOT NULL;
```
=> fix: delete player_stats records on account deletion

resources/views/components/comment/input-row.blade.php
This PR resolves two bugs in the comments textarea element:
* The textarea ID is not unique (`$commentId` is not currently being parsed)
* Alpine.js is throwing an error on initialization
Both bugs combined cause the character counter to never tick up beyond 0.
**Before**
**After**
=> fix(comments): count textarea chars correctly

app/Helpers/database/player-achievement.php, public/API/API_GetAchievementOfTheWeek.php, public/API/API_GetAchievementUnlocks.php, tests/Feature/Api/V1/AchievementOfTheWeekTest.php, tests/Feature/Api/V1Test.php, tests/Feature/Connect/AchievementWonDataTest.php
This PR is to add Softcore Points in the return value for API_GetAchievementUnlocks. 
Model Before:
```
{
"User": "DripZ07",
"RAPoints": 0,
"DateAwarded": "2024-03-15T19:49:20.000000Z",
"HardcoreMode": 0
}
```
Model After:
```
{
"User": "DripZ07",
"RAPoints": 0,
"RASoftcorePoints" 116,
"DateAwarded": "2024-03-15T19:49:20.000000Z",
"HardcoreMode": 0
}
```
=> feat(api): return RASoftcorePoints in API_GetAchievementUnlocks

resources/views/livewire/game/user-achievements-grid.blade.php
Resolves an issue where achievement card tooltips don't appear when hovering over dynamic achievement icons on the completion progress page.
=> fix(completion-progress): show tooltips on dynamic icons

app/Platform/Services/AchievementSetClaimListService.php, config/missing-page-redirector.php, resources/views/components/game/devbox-claim-management.blade.php, resources/views/pages/game/[game]/claims/index.blade.php
Missed in #2481.
Minor note: changed the default filters from "All Active Claims" (Active/InReview + Primary/Collaboration) to "All Primary Claims" (Active/InReview/Complete/Dropped + Primary).
=> fix claim history page for games

app/Platform/Actions/UpdateGameMetrics.php, app/Platform/Actions/UpdateGamePlayerGames.php, tests/Feature/Api/V1/GameInfoAndUserProgressTest.php
This PR resolves a longstanding issue with our denormalized data. Currently, once a user masters a set, unless the set's achievement set version hash changes, their RetroPoints earned on the game will be permanently frozen.
This is directly observable at: https://retroachievements.org/user/Kosmicd12
Kosmic's RetroPoints value is a staggering 1,376,121.
However, the true value sum of his two mastered sets is somewhere in the neighborhood of 700,000 RetroPoints.
**Root Cause**
Player A has mastered a set.
Player B starts playing the set and unlocks an achievement.
Currently, Player A's `player_games` metrics (and the denormalized metrics in their `UserAccounts` row) is not being updated.
This is being caused by a conditional in the `UpdateGameMetrics` action that isn't checking for if the …
=> fix(metrics): update player RetroPoints metrics on achievement unlocks

resources/views/pages-legacy/developerstats.blade.php
Resolves:
```
SQLSTATE: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-4, 25' at line 6 (Connection: mysql, SQL: SELECT ua.ID, SUM(!ISNULL(sc.ID)) AS ActiveClaims
FROM UserAccounts ua
LEFT JOIN SetClaim sc ON sc.user_id=ua.ID AND sc.Status IN (0,3)
WHERE ua.ContribCount > 0 AND ua.ContribYield > 0  AND ua.Permissions = 2
GROUP BY ua.ID
ORDER BY ActiveClaims DESC, ua.User LIMIT -4, 25) (View: /home/forge/retroachievements.org/releases/2024-06-24T203904-6.7.1-b1a49d25/resources/views/pages-legacy/developerstats.blade.php) {"exception":"[object] (Illuminate\\View\\ViewException(code: 0): SQLSTATE: Syntax error or access violation: 1064 You have an error in your …
```
=> fix(developerstats): remediate issue where the pagination offset can go negative

resources/views/pages-legacy/globalRanking.blade.php
Resolves the following error which is frequently appearing in the logs:
> localized_number(): Argument #1 ($number) must be of type int|float, null given, called in /home/forge/retroachievements.org/storage/framework/views/bb998d942beed7ef95ff6df7116dc309.php on line 271 (View: /home/forge/retroachievements.org/releases/2024-06-30T112700-6.7.1-76e5a495/resources/views/pages-legacy/globalRanking.blade.php) {"userId":117089,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): localized_number(): Argument #1 ($number) must be of type int|float, null given, called in /home/forge/retroachievements.org/storage/framework/views/bb998d942beed7ef95ff6df7116dc309.php on line 271 (View: /home/forge/retroachievements.org/releases/2024-06-30T112700-6.7.1-76e5a495/resources/views/pages-legacy …
=> fix(globalRanking): prevent server error from possible null value

app/Community/Listeners/NotifyMessageThreadParticipants.php, config/services.php
https://discord.com/channels/476211979464343552/1002688331827658774/1257349523081265307
Already added the webhook env var to prod's .env.
Additionally, this PR fixes a bug which is causing a few errors in our logs. Message thread titles cannot be over 100 characters long, otherwise the webhook POST errors out.
=> feat: add webhook for unwelcome concepts inbox

app/Platform/Services/GameListService.php
Fixes "Undefined array key \"NumTickets\"" exception when accessing a bookmark of games for a system sorted by tickets when not logged in.
=> fix exception viewing games list sorted by ticket count when not logged in

app/Helpers/database/code-note.php, app/Models/Game.php, app/Models/MemoryNote.php, app/Platform/Commands/SyncMemoryNotes.php, app/Platform/Services/TriggerDecoderService.php, app/Policies/MemoryNotePolicy.php, database/migrations/platform/2024_07_03_000000_update_codenotes_table.php
**Before running the migration, execute this SQL:**
```sql
DELETE FROM CodeNotes
WHERE GameID NOT IN (SELECT ID FROM GameData)
```
---
This PR is prep work for the ultimate migration of code notes management into Filament. Gets nearly all of the model's TODOs out of the way and adds a foreign key to `game_id`. Even though we ultimately plan on dropping the column, as long as it's there, it should be bound to GameData.ID to ensure data integrity.
=> chore(CodeNotes): implement schema TODOs and add foreign key to game_id

app/Filament/Resources/GameResource.php, app/Filament/Resources/GameResource/RelationManagers/AchievementsRelationManager.php
This PR fixes a critical bug I've discovered in the management app's game resource related to achievement reordering, as well as a few very minor issues. Due to the nature of this bug, I've added the `priority/high` label to this PR, as I don't believe we can release without this being fixed.
Currently, the achievements list table is not respecting the proper sort order. It is sorting by `DisplayOrder`, so if multiple achievements have the same `DisplayOrder` value of 0, they will all be in the wrong order. This is easily observable with game 2721 (http://localhost:64000/manage/games/2721):
**Player-facing achievements list:**
**Management-facing achievements list:**
Other than fixing this, I've made a few small quality-of-life improvements with the game resource:
* URLs are now …
=> fix(manage): remediate a few game resource issues

app/Filament/Resources/GameResource.php, app/Filament/Resources/GameResource/RelationManagers/MemoryNotesRelationManager.php, app/Helpers/database/code-note.php, app/Models/MemoryNote.php, app/Platform/Concerns/ActsAsDeveloper.php, app/Policies/MemoryNotePolicy.php
This PR adds another relation manager to the management app's game resource. Now, developers can manage code notes from the game resource's page, similar to achievements and hashes. The intention is to fully mirror the code note management behavior in the player-facing app, and in a subsequent release have the functionality live exclusively in the management app.
There are a few minor behavior differences:
* Only 200 code notes are loaded per page. This solves the Dragon Quest VIII problem where that game's code notes page will not load locally.
* Users can now search for code notes via the `body` attribute.
* Optionally, users can view a column for the `updated_at` value.
* Users can filter by note author.
=> feat(manage): add memory notes management to game resources

app/Helpers/database/leaderboard.php
Resolves https://github.com/RetroAchievements/RAWeb/issues/2590.
**Root Cause**
In https://github.com/RetroAchievements/RAWeb/pull/2537, we started recording game hashes on user activity. A new `ResumePlayerSession` event is executed on leaderboard submit. This event is inadvertently sent without a timestamp, and the timestamp is set to default to null in `ResumePlayerSession`. As a result, the `last_played_at` on the user's `player_games` row for the game is erased.
=> fix(SubmitLeaderboardEntry): attach timestamp to ResumePlayerSession

app/Exceptions/Handler.php
dump command line parameters when exception occurs running command from console.
i.e.
```
{
"exception": "[object] (ErrorException(code: 0): Attempt to read property \"id\" on bool at /var/www/html/app/Platform/Commands/UpdateDeveloperContributionYield.php:40)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/app/Platform/Commands/UpdateDeveloperContributionYield.php(40): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Platform\\Commands\\UpdateDeveloperContributionYield->handle()
#3 …
```
=> include command line arguments in exception

app/Platform/Services/GameTopAchieversService.php, resources/views/components/game/top-achievers/latest-masters.blade.php
Fixes
```
Attempt to read property "id" on null (View: /home/forge/retroachievements.org/releases/2024-08-22T131209-6.12.0-7136bf9c/resources/views/components/game/top-achievers/mastery-row.blade.php) 
```
error that occurs when viewing a game where the recent masteries contained a deleted user.
The query to fetch the recent masteries ignored deleted users, but the results are cached to improve page load times. If the cached results reference a deleted user, the exception occurs.
The proper solution is to expire the cached lists for any games the deleted user has mastered, but a more immediate solution is necessary to deal with the bad data already in the cache. I've chosen to check for deleted users before returning the cached data. It's still faster than not having the cache.
=> prevent exception trying to render recent mastery for deleted user

resources/views/pages-legacy/userInfo.blade.php
This PR fixes a minor bug on the user profile.
The new Completion Progress links on the "Last 5 Games Played" rows do not link to the correct user. They always link to yourself.
For example, go to http://localhost:64000/user/Scott and click on one of the links - it will link to your own Completion Progress page.
Now, the links will go to the right place.
=> fix(user): link to the correct user completion progress page

app/Community/Controllers/MessageController.php, app/Community/Listeners/NotifyMessageThreadParticipants.php, app/Policies/MessagePolicy.php, lang/en/legacy.php
The "new message" button is currently hidden for muted users. This re-enables the "new message" button, but will generate an error if the user tries to send to a non-team account.
https://discord.com/channels/476211979464343552/1002689485005406249/1276533882983940219
=> allow muted users to message team accounts

app/Platform/Services/PlayerGameActivityService.php, resources/views/components/user/game-activity.blade.php, resources/views/pages/achievement/[achievement]/tickets/create.blade.php
On tickets page and moderation page. Description of hash appears in tooltip.
If the description includes any of the keywords associated with multi-disc games, an asterisk is added with a tooltip indicating that only the first disc loaded is captured for a multi-disc game session.
Also attempts to pre-select a hash when creating a ticket based on session data, similar to how emulator/version information is pre-filled.
=> Add hash information to game history

config/cache.php
[Laravel 11 renames all of our Redis cache keys](https://laravel.com/docs/11.x/upgrade#cache).
In other words, without this fix, every user will be logged out on the next prod deploy. This fix re-adds the ":" character so the cache keys wont change.
=> fix: don't change all cache keys due to laravel 11 upgrade

app/Filament/Resources/GameResource/RelationManagers/GameHashesRelationManager.php, app/Models/Comment.php, app/Models/System.php
Very simple change to add a "View Comments" button to the game hash management table:
If there is at least one non-system comment, the button color changes. Automated system comments are not included in the count.
The button leads the user to the dedicated comments page for the game's hashes.
I originally explored trying to get these comments inline in the table somehow, but Filament is very unhappy with trying to do this. This seems like the next best option.
Next steps:
* Phase out the `/game/[game]/hashes/manage` route so this stuff can live entirely in Filament.
=> feat(manage): add 'View Comments' button to game hash management table

public/request/leaderboard/remove-entry.php
This legacy endpoint is still used by the leaderboardInfo.php page.
=> fix(leaderboard): restore remove-entry.php

app/Community/Listeners/NotifyMessageThreadParticipants.php, app/Helpers/util/mail.php
Resolves https://discord.com/channels/476211979464343552/1286304271847129150.
=> fix(message): remove char limit on discord/email previews

app/Community/Listeners/NotifyMessageThreadParticipants.php, app/Helpers/util/mail.php, app/Support/Shortcode/Shortcode.php
Preview messages in email/Discord are currently stripping all whitespace from `Shortcode::stripAndClamp()`. This change allows the whitespace to be preserved. Issue can be observed here: https://discord.com/channels/476211979464343552/1286306295325917256/1286306295325917256
=> fix(message): preserve whitespace in previews

package-lock.json, package.json
No functional changes. Resolves a few CVEs that Dependabot is reporting.
=> chore(deps): bump vite to latest

app/Community/Controllers/ForumTopicController.php
This PR resolves an issue on the forum recent posts view.
If you paginate too far, topics vanish: https://retroachievements.org/forums/recent-posts?page=10
This is caused by a `LIMIT 100` in the query which has now been removed.
=> fix(forum): remediate missing topics on recent posts pagination

app/Filament/Resources/AchievementSetClaimResource.php
Resolves https://retroachievements.org/log-viewer?file=034cd6ea-laravel-2024-10-01.log&query=log-index%3A87
> Missing required parameter for [Route: user.show] [URI: user/{user}] [Missing parameter: user]. (View: /home/forge/retroachievements.org/releases/2024-10-01T102815-6.15.0-cb4a2326/vendor/filament/tables/resources/views/components/columns/column.blade.php) (View: /home/forge/retroachievements.org/releases/2024-10-01T102815-6.15.0-cb4a2326/vendor/filament/tables/resources/views/components/columns/column.blade.php) (View: /home/forge/retroachievements.org/releases/2024-10-01T102815-6.15.0-cb4a2326/vendor/filament/tables/resources/views/components/columns/column.blade.php)
=> fix(manage): don't link to deleted user pages

app/Helpers/database/user-password-reset.php, app/Helpers/database/user-permission.php, app/Models/User.php, public/request/auth/reset-password.php, public/request/auth/send-password-reset-email.php
https://discord.com/channels/476211979464343552/1002689485005406249/1291000365705199689
=> fix: password reset functionality

app/Helpers/database/user-permission.php
extension of #2722 - ensures the same logic is executed when a user is untracked during the ban process
=> raise PlayerRankStatusChanged event when banning user

resources/js/tall-stack/alpine/newsCarouselComponent/newsCarouselComponent.ts
After slide 2, the home page carousel is flickering and becoming unreadable. This PR fixes the issue.
=> fix(home): remediate carousel flickering issues

resources/views/pages-legacy/leaderboardinfo.blade.php
https://discord.com/channels/310192285306454017/1190827552491716608/1301955044672798832
Fixes the value in the embed metadata, and displays the value in the page itself:
This query is slightly more expensive than I'd like (~5ms for 1500 entries), but we don't have denormalized data to leverage yet.
=> add total entry count to leaderboard details page

resources/js/features/game-list/components/DataTableToolbar/DataTableToolbar.test.tsx
GitHub Actions runs tests slowly enough that one of them in particular that renders a lot of DOM is occasionally failing due to exceeding a timeout window: https://github.com/RetroAchievements/RAWeb/actions/runs/11646542081/job/32430738923?pr=2802
=> test(DataTableToolbar): remediate flaky test that keeps failing in ci

app/Helpers/database/player-achievement.php, app/Helpers/database/player-game.php, public/dorequest.php, tests/Feature/Connect/AwardAchievementTest.php, tests/Feature/Connect/StartSessionTest.php, tests/Feature/Connect/UnlocksTest.php
followup to #2778 
[X] Modify Connect unlocks and startsession APIs to not indicate the achievement is unlocked if there's an active event achievement that the user hasn't unlocked. This will allow users to earn the event achievement without having to reset the achievement or use an alt.
this completes the player-side of things - a user can now earn an active event achievement while having previously unlocked the source achievement.
=> reactivate achievements associated to active events

resources/js/features/game-list/components/DataTableSearchInput/useSearchInputHotkey.ts
Fixes a regression from https://github.com/RetroAchievements/RAWeb/pull/2813.
`document` can't be accessed in the code without first checking that `document` exists. It's undefined during SSR, which causes the server to panic.
I mistakenly believed only `window` was affected by this -- in another project, the runtime monkey patches `document` during SSR, but Inertia does not.
It seems in the next major release of Inertia, it will be possible to run dev mode in SSR, which should greatly mitigate this sort of thing. To the best of my knowledge, there is no linting rule that can catch this.
=> fix(useSearchInputHotkey): remediate hydration issue

resources/js/features/game-list/components/DataTableSearchInput/DataTableSearchInput.test.tsx, resources/js/features/game-list/components/DataTableSearchInput/DataTableSearchInput.tsx, resources/js/features/game-list/components/DataTableToolbar/DataTableToolbar.test.tsx
This PR fixes an annoying issue on the mobile games list that only happens on iOS.
When focusing on an input field, iOS auto-zooms the window if the input field has a font size smaller than 16px. Unfortunately, it isn't possible to repro this issue without a real device or the iPhone simulator built into macOS. I've recorded the videos below using the simulator.
**Before**
https://github.com/user-attachments/assets/f80d96dd-7492-4a49-a72b-5ab198769fa6
**After**
https://github.com/user-attachments/assets/757455cf-ddbc-4c3f-a5e1-ec2b9d77ca79
=> fix(DataTableSearchInput): prevent auto-zoom on iOS

resources/js/features/game-list/components/DataTableRowActions/DataTableRowActions.tsx, resources/js/features/game-list/components/GameListItems/GameListItemElement/GameListItemContent/GameListItemContent.tsx
Right now it's pretty tough to visually parse at a glance if a game is on the user's backlog or not. This PR colorizes the button in "Remove" mode so it's easier to see at a glance what the current state is.
**Before**
**After**
=> feat(game-list): colorize the backlog toggle button

resources/js/common/components/+vendor/BaseToggle.tsx, resources/js/features/achievements/components/CreateAchievementTicketMainRoot/CreateAchievementTicketForm/DescriptionField.tsx, resources/js/features/achievements/components/CreateAchievementTicketMainRoot/CreateAchievementTicketForm/useCreateAchievementTicketForm.ts, resources/js/features/achievements/components/CreateAchievementTicketMainRoot/CreateAchievementTicketMainRoot.test.tsx
This PR remediates two minor issues present in the new Create Ticket page.
1: Unhelpful description validation is a little too aggressive.
https://discord.com/channels/310192285306454017/453242743292952578/1309231489845559296
2: The toggle button text is hard to read on light mode when hovered.
=> fix: remediate some minor issues on the Create Ticket page

.hooks/pre-push
`composer analyse` in pre-push does not currently reflect the memory limit that we use in _composer.json_.
=> ci: raise composer analyse pre-push memory limit

app/Filament/Resources/AchievementResource/RelationManagers/AuthorshipCreditsRelationManager.php
Resolves https://discord.com/channels/310192285306454017/310195377993416714/1314263872303005750.
To reproduce the bug:
* Add any form of achievement credit for a user.
* Delete the credit.
* Try to re-add the same credit for the user.
This surfaces a SQL error because it's a soft-deleted record that actually needs to be restored.
=> fix(manage): dont error when restoring deleted achievement credit

app/Filament/Resources/AchievementResource/RelationManagers/AuthorshipCreditsRelationManager.php, app/Filament/Resources/GameResource/RelationManagers/CoreSetAuthorshipCreditsRelationManager.php, app/Policies/GamePolicy.php
Jr Devs currently have the ability to update credit by means of bulk actions. This should not be permitted.
=> fix: block jr devs from updating credit

resources/js/features/game-list/components/DataTableToolbar/DataTableDesktopToolbar.tsx, resources/js/features/game-list/components/DataTableToolbar/DataTableMobileToolbar/DataTableMobileToolbar.test.tsx, resources/js/features/game-list/components/DataTableToolbar/DataTableSuperFilter/DataTableSuperFilter.test.tsx, resources/js/features/game-list/components/DataTableToolbar/DataTableSuperFilter/DataTableSuperFilter.tsx, resources/js/features/game-list/components/DataTableToolbar/RandomGameButton/RandomGameButton.test.tsx, resources/js/features/game-list/components/DataTableToolbar/RandomGameButton/RandomGameButton.tsx
Should resolve a bunch of errors we're seeing in the server logs.
This PR disables the "Surprise me" button when there are no results in the list (there is nothing to randomize, the returned game ID will always be null).
=> fix(RandomGameButton): disable when there are no games in the list

resources/js/features/game-list/components/DataTablePagination/DataTablePagination.tsx
This PR resolves an issue in the `DataTablePagination` component.
Right now, on Google Chrome (and possibly others), auto-scroll on pagination does not occur if the user is going to the first or last page. This is due to a race condition between React state and the browser event queue.
The issue can be reproduced by paginating at this URL:
http://localhost:64000/games?filter%5Btitle%5D=zelda&page%5Bsize%5D=50&page%5Bnumber%5D=1
=> fix(DataTablePagination): auto-scroll on first and last pages

resources/js/features/game-list/components/AllGamesMainRoot/AllGamesMainRoot.test.tsx, resources/js/features/game-list/components/DataTableToolbar/DataTableDesktopToolbar.tsx, resources/js/features/game-list/components/DataTableToolbar/DataTableSuperFilter/DataTableSuperFilter.test.tsx, resources/js/features/game-list/components/DataTableToolbar/DataTableSuperFilter/DataTableSuperFilter.tsx, resources/js/features/game-list/components/DataTableToolbar/DataTableToolbar.test.tsx, resources/js/features/game-list/components/WantToPlayGamesMainRoot/WantToPlayGamesMainRoot.test.tsx
Small QoL improvement to the React datatable.
If all the games on the table are of the same system, hide the now-redundant system filter on both desktop and mobile.
=> feat(DataTableToolbar): if only one filterable system, hide the System filter

resources/views/layouts/app.blade.php
Currently, `isHomeRoute` is being incorrectly set. This is resulting in the app layout's branding not being updated correctly on navigation from the home page to another React page.
`newRoute` represents the name of the _.tsx_ file, not the name of the route. For safety, we should use the pathname itself.
=> fix(home): use correct `isHomeRoute` condition

composer.json, composer.lock, package.json, pnpm-lock.yaml, resources/js/test/setup.tsx
As of today, Inertia 2.0 is no longer in beta. This PR migrates us to Inertia 2.0. There are no breaking changes in the upgrade.
In the future, we'll be able to leverage some of Inertia 2.0's features to make the front-end performance even faster.
**How to test this PR**
```
composer install
sail pnpm install
sail pnpm build
sail artisan inertia:start-ssr
```
You should be able to navigate around the React pages and not observe any hydration errors.
=> chore(deps): upgrade to inertia 2.0

package.json, pnpm-lock.yaml
Upgrades Vite to the latest major release. No functional or breaking changes. Results in slightly smaller production bundle sizes, so a minor win for perf.
**How to test this PR:**
```
sail pnpm build
```
As long as this succeeds, all is fine.
=> chore(deps): bump vite to 6.0.3

resources/js/common/utils/cn.ts, resources/js/features/home/components/+root/GuestWelcomeCta/GuestWelcomeCta.test.tsx, resources/js/features/home/components/+root/GuestWelcomeCta/GuestWelcomeCta.tsx
Makes a tiny modification to this component that appears on the home page if the user is a guest:
Now, the link to the All Games page ("the games") is sorted by player count.
=> feat(GuestWelcomeCta): auto-sort all games link by player count

app/Policies/AchievementAuthorPolicy.php
Resolves https://retroachievements.org/log-viewer?file=c05820c7-laravel-2024-12-19.log&query=log-index%3A175.
Errors are being thrown on the achievement update page in the management app due to the policy check exploding when `task` is null.
=> fix(AchievementAuthorPolicy): prevent errors on update policy checks

tests/Feature/Platform/Controllers/HubControllerTest.php
Resolves this issue:
```
There was 1 failure:
1) Tests\Feature\Platform\Controllers\HubControllerTest::testShowReturnsCorrectInertiaResponse
Inertia page component file [hub/[gameSet]] does not exist.
```
Now the test just validates props without worrying about whether the page component mounts. For whatever reason, while under test, PHPUnit seems to be having difficulty finding this component.
=> test(HubController): bypass explicit component check

app/Community/Actions/FormatLegacyCommentPayloadAction.php, app/Platform/Services/TicketViewService.php, resources/views/components/comment/item.blade.php, tests/Feature/Community/Actions/FormatLegacyCommentPayloadActionTest.php
This PR restores hash linking capabilities for ticket comments:
Blade UI ticket payloads are now sent through a sanitization/formatting action which properly safeguards against malicious injection. Comprehensive tests are included.
=> fix(ticket): properly link hash urls

app/Community/Commands/GenerateAnnualRecap.php
Addresses error:
```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 414
```
Encountered when trying to do a dry run of the `ra:community:generate-annual-recap` command.
=> reduce memory required to start recap command

app/Providers/AuthServiceProvider.php
Resolves a regression where JrDevs are no longer able to access the management app. The conditional on these roles was previously checking for a legacy permissions value.
=> fix: restore JrDev access to the management app

app/Helpers/database/user-activity.php, app/Helpers/database/user.php, public/API/API_GetUserRecentlyPlayedGames.php
https://discord.com/channels/310192285306454017/1305921595843285054/1326045928880210061
Event achievements were being filtered out _after_ doing the offset/limit, causing less than the requested number of items to be returned, which cascaded into the `more...` link not being shown.
=> exclude events from recently played games at the query level

resources/views/components/game/current-progress/root.blade.php, resources/views/pages-legacy/gameInfo.blade.php
Resolves https://discord.com/channels/310192285306454017/490333108621672448/1327646752068735098.
Also makes a slight change to the progress component itself. It already has an `isEvent` prop being passed in, so no harm in adding a conditional:
=> fix(game): show mobile event progress component

resources/js/features/game-list/hooks/useGameListState.test.ts, resources/js/features/game-list/hooks/useGameListState.ts, resources/js/features/game-list/hooks/useTableSync.ts
Resolves https://discord.com/channels/310192285306454017/1326579342230159360/1327411224249368748.
**Root Cause**
We're actually always persisting a page index of 0 in the "Remember My View" cookie.
I think it's actually desirable to do this so the types between pagination state in the cookie and datatable are perfectly aligned. Our logic error is that we weren't throwing away this persisted 0.
In other words, when a user currently has "Remember My View" checked:
* They navigate to page N of the table.
* They click a game.
* They click the back button.
* The table now thinks they're on page 1 even though they aren't, and this messes up table state.
=> fix(useGameListState): ignore persisted page index of 0

app/Actions/ProcessPlausibleUrlAction.php, tests/Feature/Actions/ProcessPlausibleUrlActionTest.php
Resolves:
> App\Actions\ProcessPlausibleUrlAction::extractId(): Argument #1 ($param) must be of type string, null given, called in /home/forge/retroachievements.org/releases/2025-01-11T035058-6.25.1-0bc6fb3e/app/Actions/ProcessPlausibleUrlAction.php on line 92 (View: /home/forge/retroachievements.org/releases/2025-01-11T035058-6.25.1-0bc6fb3e/resources/views/components/head-analytics.blade.php) (View: /home/forge/retroachievements.org/releases/2025-01-11T035058-6.25.1-0bc6fb3e/resources/views/components/head-analytics.blade.php) (View: /home/forge/retroachievements.org/releases/2025-01-11T035058-6.25.1-0bc6fb3e/resources/views/components/head-analytics.blade.php) (View: /home/forge/retroachievements.org/releases/2025-01-11T035058-6.25.1-0bc6fb3e/resources/views/components/head-analytics.bl …
=> fix(ProcessPlausibleUrlAction): remediate exception thrown on base URLs

lang/en_US.json, resources/js/common/components/+vendor/BaseAutosizeTextarea.tsx, resources/js/common/components/+vendor/BaseInput.tsx, resources/js/features/forums/components/EditPostMainRoot/EditPostForm/EditPostForm.tsx
The `placeholder` prop currently uses hardcoded text.
=> fix(EditPostForm): resolve untranslated string

app/Policies/NewsPolicy.php
Now that role-driven policies are the norm and the events team roles are all situated, I think it's appropriate to lock this down a bit more.
Note also with this change that only admins will be able to pin/unpin posts.
=> chore(NewsPolicy): adjust access

resources/js/features/forums/components/ShortcodeRenderer/ShortcodeCode/ShortcodeCode.tsx, resources/js/features/forums/utils/preProcessShortcodesInBody.test.ts, resources/js/features/forums/utils/preProcessShortcodesInBody.ts
Resolves https://github.com/RetroAchievements/RAWeb/pull/3074#discussion_r1921615916.
Also, adds margin bottom to code tags (we should probably also apply the same margin bottom to quote tags).
**Root Cause**
React uses its own synthetic event system to maximize browser compatibility. For example, when a component has `onClick={(event) => {...}}`, this is not a native `onclick="..."` event. It's running through React's synthetic event system that _emulates_ native events.
I've worked with React for a number of years and haven't hit a bug caused by synthetic events until now.
In our case, newlines were being sent to the preview component as escaped sequences (↵\n) after making any edit (ie: when initiating a synthetic event), but are served as actual newlines (\n) on load. I was able to …
=> fix(forums): normalize newlines from synthetic events

app/Support/Shortcode/Shortcode.php, resources/views/components/game/achievements-list/achievements-list-item.blade.php, resources/views/pages-legacy/achievementInfo.blade.php
Allows event managers to assign an achievement prior to it becoming active without exposing it to players until it does become active.
https://discord.com/channels/310192285306454017/1328443350889795635/1330687821429608500
If an event achievement is associated to a source achievement, it's title and description and image will be obscured on the event page and achievement page.
There are still ways to get to the unobscured data, but this should be sufficient for the largest portion of the playerbase.
=> hide future event achievement selection

resources/views/pages-legacy/individualdevstats.blade.php
Remediates an issue on the individual dev stats page where if the `display_name` differs from `User`, Own Awards show up as N/A.
**Before**
**After**
=> fix(individualdevstats): remediate Own Awards stats when using custom display_name

app/Platform/Components/GameCard.php
Resolves an issue where game cards show the wrong avatar if the user has a display_name which differs from their username.
**Before**
**After**
=> fix: remediate broken avatar image on game cards

app/Community/Controllers/UserSettingsController.php, app/Community/RouteServiceProvider.php, resources/js/features/settings/components/ChangeUsernameSectionCard/ChangeUsernameSectionCard.test.tsx, resources/js/features/settings/components/ChangeUsernameSectionCard/useChangeUsernameForm.ts, resources/js/types/generated.d.ts, resources/js/ziggy.d.ts, tests/Feature/Community/Controllers/UserSettingsControllerTest.php
When requesting a username change, if the request only has a difference in casing (ie: "Scott" -> "scott"), the request is auto-approved, with no `user_usernames` entry written to the database.
Addresses https://github.com/RetroAchievements/RAWeb/pull/3071#issuecomment-2608580032.
=> feat(user): auto-approve username changes for casing

app/Platform/Services/UserAgentService.php, tests/Feature/Platform/Services/UserAgentServiceTest.php
Apparently, IOS labels the cores "core.libretro" instead of "core_libretro"
https://discord.com/channels/476211979464343552/1002689485005406249/1332717032055115897
=> detect alternate core label

app/Models/User.php
Resolves https://discord.com/channels/310192285306454017/1333204742427377684.
Currently, if the given display name param is null, the first user on the table (Scott) will get grabbed instead, ie:
```php
$this->userContext = User::whereName($targetUsername)->first() ?? Auth::user() ?? null;
```
In the case of the bug reported, `$targetUsername` is null, so Scott's user record is being pulled by the query.
=> fix(user): properly handle null param in whereName()

.github/workflows/ci.yml, app/Filament/Resources/GameResource.php, phpstan.neon
Another PR to improve CI performance. This specifically targets `analyse` (PHPStan) while running in GitHub Actions.
As the project grows and grows, the `analyse` step is going to take exponentially longer because, currently, there is no cache to leverage in the actions containers.
This branch incorporates the official instructions for setting up the PHPStan cache in GitHub Actions from https://phpstan.org/user-guide/result-cache#setup-in-github-actions.
=> ci: use phpstan result cache

app/Filament/Resources/EventResource.php, app/Filament/Resources/EventResource/Pages/Create.php, app/Policies/EventPolicy.php, resources/views/pages-legacy/gameInfo.blade.php
If an event has a start date in the future, anyone without access to the event management console will get an Unauthorized message trying to view it.
https://discord.com/channels/310192285306454017/1334630307915104316/1335134440359329872
=> only allow event managers to view future events

app/Filament/Resources/GameResource/RelationManagers/AchievementSetsRelationManager.php
When working with the achievement sets relation manager for a game (ie: http://localhost:64000/manage/games/1?activeRelationManager=1), if you try to update the Display Order column value, a SQL error is thrown.
To repro, just change the value of the Display Order here:
**Root Cause**
For some reason, Filament is trying to use the owner record's "updated" field name (`GameData.Updated`) instead of the relation record's (`game_achievement_sets.updated_at`). This causes a SQL error because `game_achievement_sets.Updated` obviously does not exist.
=> fix(AchievementSetsRelationManager): remediate SQL error on order_column update

resources/js/common/components/+vendor/BaseTooltip.tsx, resources/js/common/utils/getIsInteractiveElement.test.tsx, resources/js/common/utils/getIsInteractiveElement.ts
This PR fixes an issue where these buttons are still showing `cursor-help` on hover:
This is due to the elements being wrapped in `<BasePopover>`. The tooltip component currently is not intelligent enough to handle this sort of nesting.
This PR extracts the util that drives the intelligence, adds more intelligence, and adds tests to cover the intelligence.
=> fix(BaseTooltip): add even more intelligence to the cursor classname

app/Community/Requests/MessageRequest.php
Resolves https://discord.com/channels/476211979464343552/1026595325038833725/1335990807097770036.
This PR only resolves the validation issue. Avatars still don't render correctly after selecting a user whose display_name value is different from their `User` value. That bug will be fixed in the imminent React migration of the page.
=> fix(MessageRequest): use display_name for recipient validation

resources/js/common/components/+vendor/BaseSelectNative.tsx, resources/js/common/components/FullPaginator/FullPaginator.test.tsx, resources/js/common/components/FullPaginator/FullPaginator.tsx, resources/js/features/comments/AchievementCommentsMainRoot/AchievementCommentsMainRoot.test.tsx, resources/js/features/comments/GameClaimsCommentsMainRoot/GameClaimsCommentsMainRoot.test.tsx, resources/js/features/comments/GameCommentsMainRoot/GameCommentsMainRoot.test.tsx, resources/js/features/comments/GameHashesCommentsMainRoot/GameHashesCommentsMainRoot.test.tsx, resources/js/features/comments/GameModificationCommentsMainRoot/GameModificationCommentsMainRoot.test.tsx, resources/js/features/comments/LeaderboardCommentsMainRoot/LeaderboardCommentsMainRoot.test.tsx, resources/js/features/comments/UserCommentsMainRoot/UserCommentsMainRoot.test.tsx, resources/js/features/comments/UserModerationCommentsMainRoot/UserModerationCommentsMainRoot.test.tsx, resources/js/features/games/components/TopAchieversMainRoot/TopAchieversMainRoot.test.tsx, resources/js/features/messages/components/+root/MessagesRoot.test.tsx
This PR adds a new vendor component: `BaseSelectNative`. For the time being, this component is only used in `FullPaginator`.
Mature component libraries tend to have multiple flavors of select components to choose from. For example, a subsequent PR will add a `BaseSelectAsync` component which allows you to search for the option (ie: a user to send a message to).
`BaseSelect` has highly-customizable UX, but has slow rendering performance on lists that have potentially hundreds of options. `BaseSelectNative` renders options very quickly, with the trade-off of having virtually no customizable UX for the select options.
**Before**
**After**
=> feat: add BaseSelectNative component

app/Helpers/database/code-note.php
Resolves https://discord.com/channels/310192285306454017/533411674162593812/1337123500321673309.
**Root Cause**
$currentNotes[$i]['User'] comes from `getCodeNotesData()`, which actually returns `display_name` as `User`.
=> fix(code-note): allow jr devs with custom display names to edit their own notes

app/Platform/Services/GameSuggestions/GameSuggestionEngine.php
Resolves https://discord.com/channels/310192285306454017/453242743292952578/1337165248653955232.
**Root Cause**
The strategies themselves are correctly filtering Event games from appearing as selections. However, `$masteredGames` and `$beatenGames` don't exclude non-game systems.
=> fix(GameSuggestionEngine): exclude non-game systems from mastered/beaten initial query

resources/views/pages-legacy/leaderboardinfo.blade.php
Resolves https://discord.com/channels/310192285306454017/859938399468388362/1337200540043710506.
Currently, the leaderboardinfo page does not detect if the authenticated user is using a custom display name. As a result, it doesn't highlight their score and still shows the CTA telling them to consider participating.
**Before**
**After**
=> fix(leaderboardinfo): don't ignore display names for local user

app/Filament/Resources/GameResource/Pages/SimilarGames.php
Resolves https://discord.com/channels/476211979464343552/1002696640001478769/1337524345790140478.
Currently, on pages like http://localhost:64000/manage/games/1/similar-games, it is possible to add a hub game to the similar games list:
=> fix(manage): block adding similar games from `System::Hubs`

resources/views/pages-legacy/setRequestList.blade.php
Resolves https://discord.com/channels/310192285306454017/453242743292952578/1337765957765959771.
There's a bug on the page where if the user changes their username, they no longer see the "Next request in..." label when viewing their own requests list.
=> fix(setRequestList): show 'Next request in...' after username change

app/Helpers/render/code-note.php, resources/views/pages-legacy/codenotes.blade.php
Will cherry-pick to `release` and deploy. Currently, if a Jr Dev has a custom display_name, they can no longer edit their own code notes on-site. This is due to a mismatch between `User` and `display_name` in a conditional specific to JrDevs on the page.
**Before**
**After**
=> fix(code-notes): allow jr devs with custom display names to edit on site

app/Helpers/database/user-relationship.php
Resolves https://github.com/RetroAchievements/RAWeb/issues/3216.
=> fix(changeFriendStatus): don't leak stable username on follow

app/Community/Actions/UpdateGameClaimAction.php, app/Helpers/database/set-request.php
Resolves https://github.com/RetroAchievements/RAWeb/issues/3220.
=> fix(email): don't leak stable usernames on set request/revision notifications

app/Filament/Resources/HubResource/RelationManagers/GamesRelationManager.php
Resolves these errors in the logs: https://retroachievements.org/log-viewer?file=5003fe9a-laravel-2025-02-15.log&query=log-index%3A19
`GameData.ID` needs to be fully-qualified, otherwise the column name is ambiguous in the query.
=> fix(GamesRelationManager): resolve server error on search

app/Filament/Resources/GameResource/Pages/SimilarGames.php
Resolves:
> SQLSTATE: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous (Connection: mysql, SQL: select count(*) as aggregate from `GameData` inner join `game_set_games` on `GameData`.`ID` = `game_set_games`.`game_id` where `game_set_games`.`game_set_id` = 23163 and (`id` like %123% or `Title` like %123%) and `GameData`.`deleted_at` is null) (View: /home/forge/retroachievements.org/releases/2025-02-16T191921-2025.02.06-B-3fa49552/vendor/filament/tables/resources/views/index.blade.php) (View: /home/forge/retroachievements.org/releases/2025-02-16T191921-2025.02.06-B-3fa49552/vendor/filament/tables/resources/views/index.blade.php) {"userId":117089,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): SQLSTATE: Integrity constraint violation: 1052 Column …
=> fix(manage): remediate server error on searching similar games

resources/js/common/components/+vendor/BaseSelect.tsx
Resolves https://github.com/RetroAchievements/RAWeb/issues/3081.
This issue **only** occurs on Android Chrome - no other browser or environment.
I discovered a solution here: https://stackoverflow.com/a/76771880. From the Radix docs:
> When using position="popper" on Select.Content, you may want to constrain the width of the content so that it matches the trigger width. You may also want to constrain its height to not exceed the viewport.
> 
> We expose several CSS custom properties such as --radix-select-trigger-width and --radix-select-content-available-height to support this. Use them to constrain the content dimensions.
=> fix(BaseSelect): remediate Android overflow issue

resources/js/features/game-list/components/HubMainRoot/HubBreadcrumbs/HubBreadcrumbs.tsx, resources/js/features/game-list/components/HubMainRoot/RelatedHubs/RelatedHubs.tsx
Resolves https://retroachievements.org/viewtopic.php?t=29663&c=265459#265459.
There appears to be a bug in the Inertia link component. When performing a client-side navigation to the same route, but with a different parameter, some client-side state is retained, which can lead to unexpected behavior.
How to reproduce this issue:
* Navigate to https://retroachievements.org/hub/26879.
* Sort by Achievements (More).
* Scroll to the bottom of the page, click on "Subgenre - Dating Simulation".
* Before doing anything on this page, observe the count of games.
* Sort by Achievements (More).
* Observe the count of games has changed.
=> fix(hubs): discard client-side state on navigation

resources/js/features/home/components/+sidebar/AchievementOfTheWeek/AotwUnlockedIndicator/AotwUnlockedIndicator.tsx
This PR resolves a style issue for the home page's AOTW "Unlocked" indicator on light mode.
**Before**
**After**
=> fix(home): remediate aotw 'Unlocked' style issues on light mode

resources/css/dropdown.css
Resolves https://github.com/RetroAchievements/RAWeb/issues/3240.
Resolves https://github.com/RetroAchievements/RAWeb/issues/2711.
The `box-shadow` on this classname is kinda overkill at the moment. Switched to a Tailwind sane default in this branch.
=> fix: remediate excessive box-shadow on nav dropdown menu

resources/js/features/game-list/components/DataTableToolbar/DataTableSuperFilter/DataTableSuperFilter.tsx, resources/js/features/game-list/components/GameListItems/GameListItemElement/GameListItemElement.tsx
Resolves https://github.com/RetroAchievements/RAWeb/issues/3245.
**How to repro the issue:**
The issue is actually caused by a bad interaction between the BaseSelect and BaseDrawer components on the page. To repro the issue, double-tap the same spot on a BaseSelect, like so:
https://github.com/user-attachments/assets/0ea438ac-d7d2-4e11-a608-4ac156f706e2
This is occurring because the drawer's `modal` prop is currently set to `false`. Flipping it to true resolves the issue, with the side effect that Safari's address bar is going to slightly pop when the drawer opens. This is the lesser of the two evils though. More info here: https://github.com/emilkowalski/vaul/issues/494
=> fix: remediate 'tap behind' effect for mobile drawers

app/Platform/Controllers/EventController.php, app/Platform/Data/EventShowPagePropsData.php, lang/en_US.json, resources/css/utilities.css, resources/js/common/components/GameAvatar/GameAvatar.test.tsx, resources/js/common/components/GameAvatar/GameAvatar.tsx, resources/js/common/components/ShortcodeRenderer/ShortcodeHub/ShortcodeHub.test.tsx, resources/js/common/components/ShortcodeRenderer/ShortcodeHub/ShortcodeHub.tsx, resources/js/common/models/base-avatar-props.model.ts, resources/js/features/events/components/+show-sidebar/EventShowSidebarRoot.tsx, resources/js/features/events/components/EventAwardTiers/EventAwardTiers.tsx, resources/js/features/events/components/HubsList/HubsList.test.tsx, resources/js/features/events/components/HubsList/HubsList.tsx, resources/js/features/events/components/HubsList/index.ts, resources/js/types/generated.d.ts, tests/Feature/Platform/Controllers/EventControllerTest.php
This PR adds a Hubs component to the React event page sidebar. IDs 1 and 4 are good to test on.
Additionally, a `GameAvatar`'s `href` can now be overridden. This also fixes a bug where `ShortcodeHub` was linking to the legacy game ID route.
=> feat(event): add Hubs component to the sidebar

docs/TRANSLATIONS.md
Some users seem to believe the doc shows a mistranslation in its example.
=> docs(TRANSLATIONS.md): use French instead of Portuguese in the example

app/Platform/Actions/BuildEventShowPagePropsAction.php, resources/js/features/events/components/EventAwardTiers/EventAwardTiers.test.tsx, resources/js/features/events/components/EventAwardTiers/EventAwardTiers.tsx, resources/js/features/events/utils/createVirtualAward.test.ts, resources/js/features/events/utils/createVirtualAward.ts
Resolves an issue mentioned in #3346.
Adds some conditional logic for events that have no event achievements but should still have an award tier. The fallback logic is now driven by `numMasters`, which has an extra query in the back-end controller.
=> fix(events): always show a virtual tier if there are masteries

lang/en_US.json, resources/js/common/components/EmptyState/EmptyState.test.tsx, resources/js/common/components/EmptyState/EmptyState.tsx, resources/js/features/events/components/EventAchievementSets/EventAchievementSets.test.tsx, resources/js/features/events/components/EventAchievementSets/EventAchievementSets.tsx
Implements a TODO on event achievement sets.
**Before**
**After**
=> feat(events): add a proper empty state for achievements

resources/js/features/game-list/components/SuggestionReasonCell/SharedHubReason/SharedHubReason.tsx
Resolves this persistent error in the logs:
> Error: Ziggy error: 'game' parameter is required for route 'game.show'.
The root cause is newer hubs without backing games do not have a game ID for `game.show` to use. However, the route should actually be pointed at `hub.show` now.
=> fix(SharedHubReason): remediate ssr crash

app/Models/Event.php
If an event has 0 event achievements, it must be concluded.
**Before**
**After**
=> fix(Event): add more logic to the status property

app/Community/Actions/UpdateGameClaimAction.php
Resolves an issue where banned users are receiving email after claims are completed.
=> fix(UpdateGameClaimAction): don't email banned users

app/Platform/Requests/GameListRequest.php, resources/js/features/game-list/components/DataTableToolbar/DataTableSuperFilter/MobileGameTypeFilterSelect/MobileGameTypeFilterSelect.test.tsx, resources/js/features/game-list/components/DataTableToolbar/DataTableSuperFilter/MobileGameTypeFilterSelect/MobileGameTypeFilterSelect.tsx, resources/js/features/game-list/components/DataTableToolbar/DataTableSuperFilter/MobileSetTypeFilterSelect/MobileSetTypeFilterSelect.test.tsx, resources/js/features/game-list/components/DataTableToolbar/DataTableSuperFilter/MobileSetTypeFilterSelect/MobileSetTypeFilterSelect.tsx, resources/js/features/game-list/components/DataTableToolbar/GameTypeFilter/GameTypeFilter.test.tsx, resources/js/features/game-list/components/DataTableToolbar/GameTypeFilter/GameTypeFilter.tsx, resources/js/features/game-list/components/DataTableToolbar/SetTypeFilter/SetTypeFilter.test.tsx, resources/js/features/game-list/components/DataTableToolbar/SetTypeFilter/SetTypeFilter.tsx
Resolves https://github.com/RetroAchievements/RAWeb/issues/3359.
**How to reproduce:**
* Go to any game list page.
* Ensure "Remember my view" is enabled.
* Open the game type filter.
* Select a game type, such as "Hacks".
* Open the game type filter again, and select "All Games".
* Refresh the page.
=> fix(games): don't malform persisted game type filter

app/Filament/Resources/GameResource/Pages/SimilarGames.php
Resolves https://retroachievements.org/log-viewer?file=2d3d1687-laravel-2025-03-28.log&query=log-index%3A16.
To reproduce the error, just try to use the similar games CSV input on a page like http://localhost:64000/manage/games/1/similar-games. Any input whatsoever into the CSV field and then pressing submit will trigger the error.
=> fix(manage): remediate similar games csv input crash

resources/views/pages-legacy/achievementInfo.blade.php
Resolves https://retroachievementsorg.sentry.io/issues/35231528/?environment=production&query=is%3Aunresolved%20is%3Afor_review%20assigned_or_suggested%3A%5Bme%2C%20my_teams%2C%20none%5D&referrer=issue-stream&sort=inbox&stream_index=0.
Easily observable at a URL like http://localhost:64000/achievement/237679.
This drops my local query count on the page from 82 to 33.
=> perf(achievementInfo): resolve N+1 query problem

resources/views/mail/community/activity.blade.php, resources/views/mail/community/private-message.blade.php, resources/views/vendor/mail/html/themes/default.css
This PR remediates two issues in Blade email templates:
* `<br />` tags are no longer printed into the email content.
* Sane line wrapping styles are now applied.
=> fix(email): remediate wrap and line break issues

resources/js/app.tsx
I can see hydration error replays, but their causes are imperceptible. This change is fine - we're not storing any PII.
=> chore: disable Sentry masking

app/Helpers/render/site-award.php
Updates the awards on the user profile page to link directly to the event page instead of going through the game page.
=> use event route for event awards

app/Models/Event.php
This PR changes how events determine if they're concluded vs evergreen:
* If an event has no end date, it will always be considered evergreen.
* If an event has an end date in the past, it will always be considered concluded.
=> fix(Event): change how current state is calculated

resources/js/common/components/DiffTimestamp/DiffTimestamp.tsx
DiffTimestamp is reporting hundreds of hydration errors to Sentry. However, the React team has specified these specific kinds of hydration errors are safe to suppress, as they are unavoidable: https://react.dev/reference/react-dom/client/hydrateRoot#suppressing-unavoidable-hydration-mismatch-errors
I've confirmed the hydration errors coming from this component do not cause the component tree to panic and remount.
=> fix(DiffTimestamp): suppress hydration errors

resources/js/features/game-list/components/DataTableToolbar/DataTableSuperFilter/DataTableSuperFilter.tsx, resources/js/features/game-list/components/GameListItems/GameListItemElement/GameListItemDrawerContent/GameListItemDrawerContent.test.tsx, resources/js/features/game-list/components/GameListItems/GameListItemElement/GameListItemDrawerContent/GameListItemDrawerContent.tsx
No functional changes.
Mobile drawer components are the source of dozens of errors in Sentry. The underlying vendor component is upset that a description isn't being used. This PR adds a description, but sets it to invisible.
=> fix: ensure drawers have a valid aria description

app/Filament/Resources/EventResource.php
This PR resolves a server error which occurs on http://localhost:64000/manage/events when any search is made on the page.
Easily reproducible with a URL like https://retroachievements.org/manage/events?tableSearch=asdf.
=> fix(EventResource): remediate crash that happens on search

resources/css/theme.css, resources/css/utilities.css, resources/js/common/components/+vendor/BaseChart.tsx, resources/js/common/components/+vendor/BaseSeparator.tsx, resources/js/features/events/components/AchievementDistribution/AchievementDistribution.tsx, resources/js/features/events/components/AchievementSet/AchievementDateMeta/AchievementDateMeta.tsx, resources/js/features/events/components/AchievementSet/AchievementsListItem/AchievementsListItem.tsx, resources/js/features/events/components/CompareProgress/CompareProgress.tsx, resources/js/features/events/components/EventAwardTiers/AwardTierItem.tsx, resources/js/features/events/components/EventAwardTiers/EventAwardTiers.tsx, resources/js/features/events/components/EventMainMedia/EventMainMedia.tsx, resources/js/features/events/components/EventProgress/EventProgress.tsx, resources/js/features/events/components/EventProgress/Glow/Glow.tsx, resources/js/features/events/components/HubsList/HubsList.tsx, resources/js/features/events/components/TopEventPlayers/TopEventPlayers.tsx
This PR makes some light mode a11y improvements. The bulk of changes are on the events page, however the default palette is affected (in light mode) on the entire site.
The default palette changes for light mode are:
* The embed color is ever so slightly brighter.
* The heading and text colors are now neutral-700 instead of blue.
* The link color has been darkened.
This isn't a silver bullet; light mode still suffers from major issues all over the place. However, this remediates some text on the site being completely unreadable while in the mode.
It is worth noting that currently the light mode usage rate on the site is <1%. Though the typography changes might be drastic, they aren't going to impact very many people.
**Before**
**After**
=> feat: make some light mode accessibility impovements

composer.json, composer.lock
Looks like `composer types` explodes if we don't have this dependency.
=> chore(deps): re-add spatie/enum

app/Helpers/database/search.php
Resolves https://discord.com/channels/310192285306454017/1364959420232241232.
Currently, "Forum Topic" search results send the user to a 404 when they click on them.
This is because the URLs are malformed due to a typo. The first query param starts with a `&` instead of a `?`.
=> fix(search): remediate forum link 404

app/Data/ForumTopicCommentData.php
Resolves https://discord.com/channels/310192285306454017/1364953100397449268.
We have thousands of comments with various encoded characters in the DB. The React UI does no decoding.
This approach of decoding characters in the DTO seems safest of all for visually displaying things correctly in the UI. It covers all possible encoded characters and mitigates any data corruption risks (ie: `updated_at`).
=> fix(ForumTopicCommentData): decode the body field

resources/js/common/hooks/useHydrateShortcodeDynamicEntities.test.ts, resources/js/common/hooks/useHydrateShortcodeDynamicEntities.ts, resources/js/features/messages/components/CreateMessageReplyForm/CreateMessageReplyForm.test.tsx, resources/js/features/messages/components/CreateMessageReplyForm/useCreateMessageReplyForm.ts
Resolves https://discord.com/channels/310192285306454017/1017568867574362283/1364950721526497361 and https://discord.com/channels/310192285306454017/1364989244963295283.
On pagination while viewing a forum topic, if a dynamic shortcode entity is on the destination page and it's also not on the current page, it will not render until a browser hard refresh.
**Root Cause**
Atoms are being used to manage global state on the page. On a client-side navigation, the atoms need to be resynced with props from the Laravel controller, otherwise the global state becomes stale.
=> fix(useHydrateShortcodeDynamicEntities): sync atoms with page props

app/Community/Actions/BuildMessageThreadShowPagePropsAction.php
Applies the fix from https://github.com/RetroAchievements/RAWeb/pull/3453 to message threads as well. `[event]` shortcodes are currently rendering in previews, but not submitted messages.
=> fix(messages): show event shortcodes in message threads correctly

resources/js/common/components/+vendor/BaseSelectAsync.tsx
Resolves https://discord.com/channels/476211979464343552/1152683553348407409/1366396241541595146.
Password managers are unhappy with the BaseSelectAsync component.
There should be no functional changes other than disabling certain password managers from trying to inject stuff into the field.
=> fix(BaseSelectAsync): disable native autocomplete

resources/js/features/forums/components/ForumPostCard/ForumPostCardMeta/ForumPostCardTimestamps.test.tsx, resources/js/features/forums/components/ForumPostCard/ForumPostCardMeta/ForumPostCardTimestamps.tsx
This PR makes an adjustment to how this label is presented in the forums:
"last edited" will now no longer appear on a post if the edit is within 2 minutes of the post's creation date. This gives the poster a chance to fix any typos they may have made in their post without it being visibly marked as edited.
=> feat(forums): only show 'last edited' label if updatedAt is >= 2 minutes after createdAt

app/Connect/Actions/SubmitCodeNoteAction.php, tests/Feature/Connect/GetCodeNotesTest.php, tests/Feature/Connect/SubmitCodeNoteTest.php
Fixes first part of https://discord.com/channels/310192285306454017/310195377993416714/1367961651156095067 (ability to delete code notes from DLL). I believe the second part (them magically reappearing when deleted from the site) is handled by #3486.
=> fix note deletion from client

app/Helpers/database/code-note.php
Soft deleted code notes are appearing in the legacy PHP UI (http://localhost:64000/codenotes.php?g=1) due to the legacy SQL query not considering the `deleted_at` field.
=> fix(code-notes): don't show soft-deleted notes in the php ui

app/Community/Actions/BuildShowForumTopicPagePropsAction.php
Resolves "Undefined array key 0" in the logs: https://retroachievements.org/log-viewer?file=1c5b31b8-laravel-2025-05-02.log&query=log-index%3A98
This is caused by forum topics being viewed where the single post is by someone who has unauthorized posting privileges, thus there are no posts to view.
=> fix(forums): 404 if the topic has no visible posts

app/Policies/MessageThreadPolicy.php
This PR allows users with `Role::MODERATOR` to change their inbox to the RAdmin inbox.
Additionally, `ROLE_INBOX_MAP` has been flipped so the key is now the inbox `display_name`, and the value is a list of allowed roles.
=> feat(MessageThreadPolicy): allow moderators to access RAdmin

resources/js/common/components/+vendor/BasePagination.tsx, resources/js/common/components/InertiaLink/InertiaLink.tsx
Improves the performance of the `FullPaginator` component wherever it's used, namely the forum, comment walls, and DMs. Now on hover for desktop devices only, the paginator prefetches the destination page, resulting in a moderately faster page transition.
=> perf(BasePagination): prefetch on hover for desktop

app/Console/Commands/CacheMostPopularEmulators.php, app/Console/Commands/CacheMostPopularSystems.php, app/Http/Controllers/DownloadsController.php, app/Models/DownloadsPopularityMetric.php, database/migrations/2025_05_02_000000_create_downloads_popularity_metrics_table.php
Currently, the downloads page uses persisted data in Redis for the system & emulator popularity metrics. However, this is being blown away on every prod deploy by our deployment script.
This PR moves the data to being stored in a lightweight table called `downloads_popularity_metrics`.
=> fix(downloads): store popularity metrics in the db instead of redis

app/Filament/Resources/GameResource/RelationManagers/AchievementsRelationManager.php
https://discord.com/channels/310192285306454017/310195377993416714/1368665461146910861
Hides the "Assign Maintainer" individual row action for users who do not have the permission to assign maintainers.
=> fix(manage): perm-gate assign maintainer table action

lang/en_US.json, resources/js/common/components/AchievementsListItem/AchievementTypeIndicator/AchievementTypeIndicator.test.tsx, resources/js/common/components/AchievementsListItem/AchievementTypeIndicator/AchievementTypeIndicator.tsx, resources/js/common/components/AchievementsListItem/AchievementTypeIndicator/index.ts, resources/js/common/components/AchievementsListItem/AchievementsListItem.test.tsx, resources/js/common/components/AchievementsListItem/AchievementsListItem.tsx
This PR adds type indicators to achievement rows on the React game pages.
There are two subtle behavior changes to keep in mind:
* The text animation has been replaced with `BaseTooltip`. This is so we can put other things in the rows (such as comment counts) without being design-constrained.
* The "[m]" invisible text on missable icons has been retired.
The beaten game credit dialog is not implemented yet.
=> feat(game): add type indicators to React game pages

app/Platform/Actions/BuildGameShowPagePropsAction.php, app/Platform/Actions/BuildHubBreadcrumbsAction.php, app/Platform/Controllers/GameController.php, app/Platform/Data/GameSetData.php, app/Platform/Data/GameShowPagePropsData.php, lang/en_US.json, resources/js/features/games/components/+show-sidebar/GameShowSidebarRoot.tsx, resources/js/features/games/components/+show/GameShowMainRoot.tsx, resources/js/features/games/components/SimilarGamesList/SimilarGamesList.test.tsx, resources/js/features/games/components/SimilarGamesList/SimilarGamesList.tsx, resources/js/features/games/components/SimilarGamesList/SimilarGamesListItem/SimilarGamesListItem.test.tsx, resources/js/features/games/components/SimilarGamesList/SimilarGamesListItem/SimilarGamesListItem.tsx, resources/js/features/games/components/SimilarGamesList/SimilarGamesListItem/index.ts, resources/js/features/games/components/SimilarGamesList/index.ts, resources/js/types/generated.d.ts
This PR adds a Similar Games component to React game pages:
Some subtle nuances to note:
* Games are sorted server-side by `sort_title`.
* Rather than show RetroPoints, which tends to confuse new users, the achievement count is shown instead. The achievement icon is the same one from the navbar.
=> feat(game): add Similar Games to React game pages

app/Community/Listeners/WriteUserActivity.php
There's one more source that's dispatching massive amounts of Meilisearch jobs. `WriteUserActivity` needs to use `->saveQuietly()` instead of `->save()`.
=> perf(WriteUserActivity): use saveQuietly

app/Helpers/database/player-game.php, app/Platform/Services/PlayerCompletionProgressPageService.php
Resolves https://discord.com/channels/310192285306454017/1373056387227324447.
The game datatables are using `sort_title`, but the Completion Progress page still sorts games via `Title`. This PR fixes the inconsistency.
=> fix: use `sort_title` on the Completion Progress page

config/horizon.php
At least for the time being, the Scout queue is the lowest priority thing we have being provisioned by Horizon.
I don't see any reason for it to need more than a single process, but right now it can consume 2-4 depending on load. These search index synchronizations are not time-critical.
=> perf(search): limit the scout queue to 1 process

app/Platform/Services/TicketListService.php
Fixes https://discord.com/channels/310192285306454017/1370868969531117600.
Currently, if a ticket has an inactive developer but an active maintainer, it's still appearing when filtering tickets by inactive devs.
With this branch's changes, those tickets will be excluded when using the filter.
=> fix(tickets): exclude 'inactive' dev tickets that have active maintainers

public/API/API_GetClaims.php, tests/Feature/Api/V1/AchievementSetClaimTest.php
API_GetClaims was implemented without pagination, and is now returning over a 4MB response (and growing) by default in prod.
There is an existing comment that reads:
> returns information about 1000 max set claims
This PR enforces this cap, which reduces the payload size to roughly 390KB.
=> feat(api): cap API_GetClaims to 1000 results

app/Helpers/database/player-game.php, app/Platform/Actions/ResumePlayerSessionAction.php, app/Support/Cache/CacheKey.php, resources/views/pages-legacy/gameInfo.blade.php
Reverts the game page recent players cache changes (never deployed to prod).
I've confirmed this has negative performance impacts when dealing with games with millions of sessions, such as Final Fantasy XI. Notably, it causes `ResumePlayerSessionAction` to take multiple seconds to finish.
=> chore: revert #3509

app/Helpers/database/user-permission.php, app/Models/Comment.php, app/Models/ForumTopicComment.php, app/Models/GameSet.php, app/Platform/Actions/UpdateGameAchievementsMetricsAction.php, config/horizon.php, config/scout.php, resources/views/pages/demo/scout.blade.php
This PR adds the `Searchable` trait to `Comment`, `ForumTopicComment`, and `GameSet`.
Additionally, the demo page has been enhanced so you can search for these things:
**How to test this PR:**
```bash
sail artisan horizon # be sure to restart your horizon instance if one is already running
sail artisan scout:sync-index-settings
sail artisan scout:import "App\Models\GameSet"
sail artisan scout:import "App\Models\ForumTopicComment"
sail artisan scout:import "App\Models\Comment"
```
**Things to note:**
* Comments left by banned users are not searchable. Forum posts are still searchable from banned users.
* When a user is banned, their comments are marked as unsearchable. There is no treatment for unbanning a user (should there be?).
* A few `->saveQuietly()` invocations have been added to …
=> feat(search): index comments, forum posts, and hubs

app/Community/Enums/AwardType.php, app/Filament/Resources/EventResource.php, app/Filament/Resources/HubResource.php, app/Helpers/database/site-award.php, app/Helpers/render/site-award.php, app/Models/Event.php, database/migrations/2025_05_18_000000_update_events_table.php, public/API/API_GetUserAwards.php, tests/Feature/Api/V1/UserAwardsTest.php, tests/Feature/Connect/SubmitCodeNoteTest.php
Instead of trying to derive it from the hubs it belongs to.
Also addresses https://github.com/RetroAchievements/RAWeb/discussions/3148#discussioncomment-11996185.
Site Awards will have `'AwardType'='Site Event'` and other events will have `'AwardType'='Event'`.
Does not address #3135, which deals with specific Site Awards not backed with an actual event record.
----
Query to initialize field:
```
UPDATE events SET gives_site_award=1 WHERE legacy_game_id
IN (SELECT game_id FROM game_set_games WHERE game_set_id IN (5, 3483, 5491, 25648));
```
=> Add "gives site award" flag to events

app/Filament/Resources/GameResource/RelationManagers/ReleasesRelationManager.php
Adds a URL which links to the changes introduced in https://github.com/RetroAchievements/docs/pull/249.
=> feat(manage): add guidelines doc url to game release form

app/Models/AchievementSetAchievement.php, app/Platform/Actions/UpsertGameCoreAchievementSetFromLegacyFlagsAction.php
This PR tackles another cause of N+1 writes in `UpdateGameMetricsAction`. Eloquent ORM's `sync()` kicks off an individual query for every entity to be synced.
Now, they're all rolled up into an `->upsert()`.
=> perf(UpsertGameCoreAchievementSetFromLegacyFlagsAction): batch sync

app/Platform/Actions/ResetPlayerProgressAction.php, app/Platform/Actions/UnlockPlayerAchievementAction.php, app/Platform/Actions/UpdateAchievementMetricsAction.php, app/Platform/Actions/UpdateGameAchievementsMetricsAction.php, app/Platform/Actions/UpdateGameBeatenMetricsAction.php, app/Platform/Actions/UpdateGameMetricsAction.php, app/Platform/Actions/UpdateGameMetricsForGamesPlayedByUserAction.php, app/Platform/Actions/UpdateGamePlayerCountAction.php, app/Platform/Actions/UpdatePlayerGameMetricsAction.php, app/Platform/AppServiceProvider.php, app/Platform/Commands/UpdateGameBeatenMetrics.php, app/Platform/Commands/UpdateGamePlayerCount.php, app/Platform/EventServiceProvider.php, app/Platform/Jobs/UpdateAchievementMetricsJob.php, app/Platform/Jobs/UpdateGameBeatenMetricsJob.php, app/Platform/Jobs/UpdateGamePlayerCountJob.php, app/Platform/Listeners/DispatchUpdateAchievementMetricsJob.php, app/Platform/Listeners/DispatchUpdateGameBeatenMetricsJob.php, app/Platform/Listeners/DispatchUpdateGameMetricsJob.php, app/Platform/Listeners/DispatchUpdateGamePlayerCountJob.php, app/Platform/Services/PlayerGameActivityService.php, tests/Feature/Api/V1/UserSummaryTest.php, tests/Feature/Platform/Actions/ResetPlayerProgressActionTest.php
* `UpdateGameMetricsAction` now only updates metadata about the game (number of achievements, number of points, hash of all published achievements).
- It's called whenever an achievement is modified (promoted/demoted/points changed)
- Calculating the hash is probably a lot less expensive than scanning millions of rows in the database, but it's still something that we don't need to be doing as frequently as we were.
- Whenever the hash changes, the set is synced to the core achievement set for the game. Doing a sync (even if the only change was the unlock percentage) was the third most expensive part of calling `UpdateGameMetricsAction`. That was largely improved by #3573.
* `UpdateGamePlayerCountAction` updates the number of players for the game.
- It's called when a player unlocks their …
=> Split UpdateGameMetricsAction into multiple actions

app/Platform/Actions/ResetPlayerProgressAction.php, app/Platform/Actions/UpdateGameMetricsForGamesPlayedByUserAction.php, app/Platform/Actions/UpdatePlayerGameMetricsAction.php, app/Platform/Commands/UpdateGameBeatenMetrics.php, app/Platform/Listeners/DispatchUpdateAchievementMetricsJob.php, app/Platform/Listeners/DispatchUpdateGameBeatenMetricsJob.php, app/Platform/Listeners/DispatchUpdateGamePlayerCountJob.php, config/horizon.php
Implements https://github.com/RetroAchievements/RAWeb/pull/3578#discussion_r2117794872.
Puts the long-running stuff in supervisor-2. Other things go into supervisor-1.
=> perf: split new actions across several queues

resources/views/pages-legacy/gameInfo.blade.php
Resolves a bug where if the user is persisting the "Hide unlocked achievements" filter and they complete/master the game, they no longer see the achievements list.
=> fix(game): always show all achievements if user has completion/mastery

app/Models/Achievement.php, app/Platform/Actions/UpdateAchievementMetricsAction.php
Reimplements https://github.com/RetroAchievements/RAWeb/pull/3572.
* We're no longer using `DB::statement()` with bindings.
* We're no longer doing dirty checking with `syncOriginal()`.
The only intent here is to lift `$achievement->saveQuietly();` to a single bulk write to mitigate network overhead between Horizon and the DB.
=> perf(UpdateAchievementMetricsAction): bulk write

app/Platform/Actions/ResetPlayerProgressAction.php, app/Platform/Actions/UpdatePlayerGameMetricsAction.php
Also eliminates the UpdatePlayerCount call when a single achievement is reset and relies on the UpdatePlayerGames action detecting the number of unlocks going to zero. This also handles the case where the number of unlocks go to zero through demoting all achievements a player has earned.
=> fix achievement metrics not updating when resetting single achievement

app/Connect/Actions/SubmitGameTitleAction.php, app/Helpers/database/game.php
also initializes other nullable counts that were previously being set to 0 (I assume this has to be the result of #3558, but I can't find anything explicitly setting the values to 0 [there](https://github.com/RetroAchievements/RAWeb/pull/3558/files#diff-6689b0b689dabb410c1e2cd5db0c475fa05e5d538d56b13e66251f5064a214dcL693-L709)).
these should probably be made not nullable with a default of 0.
=> ensure players_total gets intialized

tests/Feature/Platform/Services/GameSuggestions/GameSuggestionEngineTest.php
One test case in this file is still missing a call to `dangerouslySetFixedStrategyForTesting()`, which is causing it to frequently fail in CI.
=> test(GameSuggestionEngine): remediate ci flake

app/Filament/Resources/LeaderboardResource.php, app/Policies/LeaderboardPolicy.php, resources/views/pages-legacy/leaderboardinfo.blade.php
fixes https://discord.com/channels/310192285306454017/1376448588871106560/1379668587815633068
similar issue as #3561, but for leaderboards.
also added a manage button directly on the leaderboard page (#3559 for achievements) and hooked up the field-level permissions in the leaderboard management page.
=> allow junior developers with writer role to update leaderboard titles for non-claimed games

resources/views/pages-legacy/achievementinspector.blade.php
Fixes an issue where "Demote Selected" and "View Unofficial Achievements" weren't being shown when going to the "Manage Core Achievements" page for a game.
=> fix toolbox on achievement inspector page

app/Platform/Actions/UpdateDeveloperContributionYieldAction.php
Resolves https://github.com/RetroAchievements/RAWeb/issues/3605.
The `:flags` param is used twice, which is causing the query exception. Similar to `user_id`, it needs to be duplicated across uniquely-named params.
=> fix(UpdateDeveloperContributionYieldAction): duplicate the flags param

resources/js/common/components/GlobalSearch/GlobalSearch.test.tsx, resources/js/common/hooks/useUserSearchQuery.ts, resources/js/features/events/components/EventAwardEarnersMainRoot/EventAwardEarnersMainRoot.tsx, resources/js/features/events/components/EventAwardTiers/AwardTierItem.test.tsx, resources/js/features/events/components/EventAwardTiers/AwardTierItem.tsx, resources/js/features/game-list/components/SuggestionReasonCell/SharedAuthorReason/SharedAuthorReason.tsx
This PR resolves numerous warnings that are being logged:
```
stderr | resources/js/features/events/components/EventAwardTiers/AwardTierItem.test.tsx > Component: AwardTierItem > given no earn count, does not show a link to earners
An empty string ("") was passed to the href attribute. To fix this, either do not render the element at all or pass null to href instead of an empty string.
```
More empty string woes in `<AwardTierItem />`. Resolved by setting this to be `undefined` when there's no link and a type cast to `<InertiaLink />`'s `href` prop.
---
```
stderr | resources/js/features/game-list/components/SuggestionReasonCell/SuggestionReasonCell.test.tsx > Component: SuggestionReasonCell > given the suggestion reason is shared-author, renders the SharedAuthorReason component
Accessing …
```
=> chore: React warnings cleanup

resources/js/common/components/GlobalSearch/GlobalSearch.tsx, resources/js/common/hooks/queries/useSearchQuery.ts, resources/js/features/events/components/+show/EventShowMainRoot.test.tsx
This PR remediates the issue exhibited in this video:
https://github.com/user-attachments/assets/73e4fcb6-01e1-4975-83a4-977daa03d617
If the user makes a search, closes the dialog, then opens the dialog on the same page and makes another search, there's a brief flash of cached data that appears.
This is caused by the eager internal caching mechanism of `@tanstack/react-query`, which powers the `useSearchQuery` hook.
=> fix(search): remediate flash of cached results

app/Platform/Actions/IncrementDeveloperContributionYieldAction.php, app/Platform/Actions/ResetPlayerProgressAction.php, app/Platform/Jobs/IncrementDeveloperContributionYieldJob.php, tests/Feature/Platform/Actions/IncrementDeveloperContributionYieldActionTest.php
This PR:
* Skips invocation of `IncrementDeveloperContributionYieldAction` if the developer is deleted.
* Forces the action itself to never attempt an underflow write via a small modification to the query.
Resolves https://retroachievements.org/log-viewer?file=06e47184-laravel-2025-06-12.log&query=log-index%3A101
=> fix: prevent attempted underflows of dev stats

app/Filament/Resources/GameResource/RelationManagers/AchievementSetsRelationManager.php, app/Filament/Resources/GameResource/RelationManagers/AchievementsRelationManager.php, app/Filament/Resources/GameResource/RelationManagers/CoreSetAuthorshipCreditsRelationManager.php, app/Filament/Resources/GameResource/RelationManagers/LeaderboardsRelationManager.php, app/Filament/Resources/GameResource/RelationManagers/MemoryNotesRelationManager.php, app/Filament/Resources/GameResource/RelationManagers/ReleasesRelationManager.php
This PR:
* Adds icons and counts to the game resource's relation manager tabs.
* Removes the "Sets" tab for subset games.
**Before**
**After**
=> feat(manage): improve game relation tab ux

app/Platform/AppServiceProvider.php, app/Platform/Commands/BackfillPlaytimeTotal.php, app/Providers/AppServiceProvider.php
This PR ever-so-slightly reduces these batch sizes from 1,000 to 750.
Prod was unresponsive for 60s+ [earlier today](https://discord.com/channels/476211979464343552/1026273695133605888/1385286039744282708), with CPU briefly pinned at 100%.
There was a significant plateau overnight where CPU was also pinned:
I'm hoping lowering from 1,000 to 750 takes a little bit of the edge off.
=> perf: don't run scheduled commands in non-prod envs

.github/workflows/ci.yml, resources/js/common/components/ShortcodeRenderer/ShortcodeSpoiler/ShortcodeSpoiler.tsx
Resolves https://github.com/RetroAchievements/RAWeb/issues/3642.
`ShortcodeSpoiler` currently doesn't respect the dynamic height of its content. I've tweaked the CSS so it now does.
Easy to repro at http://localhost:64000/forums/topic/19615?comment=144996#144996.
**Before**
**After**
=> fix(ShortcodeSpoiler): respect dynamic content height

lang/en_US.json, resources/js/features/games/components/GameMetadata/GameMetadata.test.tsx, resources/js/features/games/components/GameMetadata/GameMetadata.tsx, resources/js/features/games/components/GameMetadata/GameOtherNamesRow/GameOtherNamesRow.test.tsx, resources/js/features/games/components/GameMetadata/GameOtherNamesRow/GameOtherNamesRow.tsx, resources/js/features/games/components/GameMetadata/GameOtherNamesRow/index.ts, resources/js/features/games/components/GameMetadata/GameReleaseDatesRow/GameReleaseDatesRow.test.tsx, resources/js/features/games/utils/getNonCanonicalTitles.test.ts, resources/js/features/games/utils/getNonCanonicalTitles.ts
Adds a metadata row for unique non-canonical titles:
If there are 5 or more alt titles, only 3 are shown and the excess is buried in a tooltip. If there are exactly 4 alt titles, all are shown with no tooltip.
=> feat(game): add 'Other Names' metadata row

app/Connect/Actions/GetAchievementUnlocksAction.php, app/Connect/Support/BaseApiAction.php, app/Helpers/database/player-achievement.php, public/dorequest.php, tests/Feature/Connect/AchievementWonDataTest.php
* Converted `getRecentUnlocksPlayersData` to eloquent.
* Added `Content-Length` header to response (as suggested in #3634).
* Changed the response for an unknown achievement ID to return 404 instead of success with no unlocks.
=> add action for achievementwondata connect api

resources/js/common/components/ActivePlayerFeed/ActivePlayerFeedList.tsx, resources/js/common/hooks/useAddOrRemoveFromUserGameList.test.ts
Resolves a very minor CSS regression introduced from changes in #3643. Active players don't have enough margin between the game avatar and game title/RP text.
=> fix(ActivePlayerFeedList): resolve margin regression

lang/en_US.json, resources/js/features/home/components/+sidebar/RecentGameAwards/RecentGameAwards.test.tsx, resources/js/features/home/components/+sidebar/RecentGameAwards/RecentGameAwards.tsx
Cleans up some copy I missed when changing the statbox label.
=> fix(home): use 'Most recent set mastered' label for consistency

resources/js/common/components/PlayerGameProgressBar/PlayerGameProgressBar.tsx
Resolves https://discord.com/channels/310192285306454017/1017568867574362283/1391119801631637544.
**Root Cause**
These progress bars are assuming the user has beaten or mastered the game, which is not the case for events, ultimately causing an empty tooltip display to appear on hover.
=> fix(event): don't show empty tooltips for compare progress

app/Platform/Actions/AttachPlayerGameAction.php, app/Platform/Actions/ResumePlayerSessionAction.php
This PR implements small optimizations to `ResumePlayerSessionAction`. Individually, these optimizations only save 3-5ms per execution, but at 49M executions/month they should yield significant CPU time savings.
**Changes:**
- `User` model updates have been consolidated from 3 separate saves to a single save.
- `AttachPlayerGameAction` now uses `firstOrCreate()` instead of a check-then-create pattern.
All in all, this should reduce queries from 7-8 to 5-6 per action invocation.
On my local, I benchmarked the before/after with 100 iterations.
- New session creation: 14.5ms -> 8.3ms (-6.2ms)
- Resume session: 17.01ms -> 13.85ms (-3.16ms)
- Resume with playtime: 17.12ms -> 12.53ms (-4.59ms)
These micro-optimizations should collectively save ~25 CPU hours per month.
=> perf: make some tiny optimizations to ResumePlayerSessionAction

app/Platform/Actions/LoadGameRecentPlayersAction.php, resources/js/common/components/PlayableCompareProgress/PopulatedPlayerCompletions/PopulatedPlayerCompletions.tsx, resources/js/common/components/PlayerGameProgressBar/PlayerGameProgressBar.test.tsx, resources/js/common/components/PlayerGameProgressBar/PlayerGameProgressBar.tsx, resources/js/features/games/components/GameRecentPlayers/GameRecentPlayersList/GameRecentPlayersList.tsx, resources/js/features/games/components/GameRecentPlayers/GameRecentPlayersTable/GameRecentPlayersTable.tsx
Fixes a bug on React game pages in the Recent Players section. If a player shown has a mastery award for the game, the tooltip content is empty.
**Before**
**After**
=> fix(game): don't show empty tooltips for some Recent Players

resources/js/features/games/components/AchievementSetCredits/AchievementAuthorsDisplay/AchievementAuthorsDisplay.test.tsx, resources/js/features/games/components/AchievementSetCredits/AchievementAuthorsDisplay/AchievementAuthorsDisplay.tsx
Extracts a minor tweak from the now-closed https://github.com/RetroAchievements/RAWeb/pull/3674:
> ... a minor tweak to the 33% authorship threshold, lowering it to 30%. This fixes an issue where only one author label was appearing for Super Mario 64, even though another user had contributed something like 31% of the set's achievements.
**Before**
**After**
=> fix(AchievementAuthorsDisplay): lower prominence threshold from 33% to 30%

resources/js/features/games/components/GameSidebarFullWidthButtons/GameSidebarFullWidthButtons.tsx
This PR fixes a bug on React game pages where the `href` attribute of guide URLs is "#". Now, they properly link to where they're supposed to go.
An example of a game to test with is http://localhost:64000/game2/15020.
=> fix(game): link guide URLs correctly on React game pages

resources/js/features/game-list/components/GameListItems/GameListItemElement/GameListItemContent/GameListItemContent.test.tsx, resources/js/features/game-list/components/GameListItems/GameListItemElement/GameListItemContent/GameListItemContent.tsx, resources/js/features/game-list/components/GameListItems/GameListItemElement/GameListItemElement.test.tsx, resources/js/features/game-list/components/GameListItems/GameListItemElement/GameListItemElement.tsx, resources/js/features/game-list/components/GameListItems/GameListItems.tsx
Resolves https://retroachievementsorg.sentry.io/issues/26749701/?environment=production&query=is%3Aunresolved&referrer=issue-stream.
Mobile views for `/system/{system}/games` are throwing a hydration error right now related to the system chip conditionally displaying. This is occurring because `route().current()` is undefined during SSR.
=> fix(GameListItemContent): remediate mobile system games hydration error

app/Platform/Actions/BuildGamePageClaimDataAction.php, app/Policies/AchievementSetClaimPolicy.php
Resolves https://discord.com/channels/310192285306454017/1409093801997242383.
Developers with several collabs are no longer able to make new achievement set claims.
**Root Cause**
`getActiveClaimCount()` needed its 2nd arg (`$countCollaboration`) flipped from true to false.
=> fix(AchievementSetClaimPolicy): don't include collab claims in activeClaimCount

app/Community/Actions/LoadThinActivePlayersListAction.php
Resolves https://discord.com/channels/476211979464343552/1026595325038833725/1408814140843102470.
**Root Cause**
`game_recent_players` stores entries for all games a user has played recently. When a user switches between games, they have multiple entries in the table. The current query returns all these entries, showing the same user multiple times.
**Fix**
This PR adds an additional filter to the query that leverages `UserAccounts.LastGameID`.
=> fix(home): remediate bug where active players has multiple rows for the same user

app/Community/Components/DeveloperGameStatsTable.php, resources/views/components/developer/game-stats-table.blade.php, resources/views/pages-legacy/individualdevstats.blade.php
The developer profile page is leaking stable usernames. That bug is resolved by this PR.
**Before**
**After**
=> fix(individualdevstats): remediate stable username leak

database/schema/mysql-schema.sql
Leftover from a scrapped branch. Forgot to run the `down()` migration before scrapping.
=> chore: remove unused column from mysql-schema

pnpm-lock.yaml
=> chore(deps): force linkifyjs to 4.3.2

resources/js/features/games/components/GameSidebarFullWidthButtons/SidebarDevelopmentSection/SidebarDevelopmentSection.tsx
For some reason, my brain is not too happy with the current placement of this button.
**Before**
**After**
=> chore(game): relocate the 'View Unpublished Achievements' button

resources/js/features/games/components/AchievementSetEmptyState/AchievementSetEmptyState.test.tsx, resources/js/features/games/components/AchievementSetEmptyState/AchievementSetEmptyState.tsx
https://github.com/RetroAchievements/RAWeb/pull/3788#pullrequestreview-3126343745
If the user is unauthorized, the link to player requests will now be a span.
**Before**
**After**
=> fix(AchievementSetEmptyState): don't link player requests if unauthorized

resources/js/app.tsx
Backswipes on iOS Safari are creating duplicate browser history entries.
Related: https://github.com/RetroAchievements/RAWeb/pull/3946
=> fix(game): remediate Inertia.js mobile backswipe issue

app/Platform/Actions/BuildGameShowPagePropsAction.php
Currently, all recent players are shown from the root game rather than a selected subset. With this PR, the right players (and RP strings) appear.
=> fix(BuildGameShowPagePropsAction): use backingGame for recent players

resources/js/features/games/components/GameMetadata/GameReleaseDatesRow/GameReleaseDatesRow.tsx, resources/js/features/games/hooks/useDeduplicatedReleases.test.ts, resources/js/features/games/hooks/useDeduplicatedReleases.ts
http://localhost:64000/game2/7212
The UI needs a thin layer of deduplication for game releases, in addition to the deduplication already happening in the back-end. The front-end deduplication layer ensures unique titles aren't discarded on identical regions and dates.
**Before**
**After**
=> fix(game): add another layer of release deduplication

resources/js/features/games/components/BeatenCreditDialog/BeatenCreditAchievementList/BeatenCreditAchievementList.test.tsx, resources/js/features/games/components/BeatenCreditDialog/BeatenCreditAchievementList/BeatenCreditAchievementList.tsx, resources/js/features/games/components/BeatenCreditDialog/BeatenCreditDialog.tsx, resources/js/features/games/components/BeatenCreditDialog/JumboTypeMetric/JumboTypeMetric.tsx
This PR:
* Applies the "normal" sort order to achievements so the unlocked ones appear before locked ones.
* Updates the layout (no more 2 column grid) and applies a consistent border radius to all elements.
**Before**
**After**
=> feat(game): add sorting to Beaten Game Credit dialog, make some css updates

app/Platform/Controllers/HubController.php, resources/js/features/games/components/SeriesHubDisplay/SeriesHubDisplay.tsx, resources/js/features/games/hooks/useSeriesHubHref.test.ts, resources/js/features/games/hooks/useSeriesHubHref.ts
https://discord.com/channels/310192285306454017/1420648984472457226
The Series Hub URL should not tack on query params if the user has cookie settings for the datatable persisted.
=> fix(game): have the Series Hub link respect user cookie prefs

resources/js/common/components/PlayableSidebarButton/PlayableSidebarButton.tsx, resources/js/features/games/components/+show-mobile/GameShowMobileRoot.test.tsx, resources/js/features/games/components/+show-mobile/GameShowMobileRoot.tsx, resources/js/features/games/components/GameSidebarFullWidthButtons/SidebarDevelopmentSection/SidebarDevelopmentSection.test.tsx, resources/js/features/games/components/GameSidebarFullWidthButtons/SidebarDevelopmentSection/SidebarDevelopmentSection.tsx, resources/js/features/games/hooks/useGameShowTabs.ts
This PR fixes a bug that affects mobile only.
When selecting the "View Unpublished Achievements" link in the Info tab, the tab isn't being reset to "Achievements". This PR fixes the issue.
=> fix(game): on mobile, navigate to 'Achievements' tab when selecting View Unpublished Achievements

resources/js/common/components/+vendor/BaseDropdownMenu.tsx, resources/js/common/components/PlayableListSortButton/PlayableListSortButton.test.tsx, resources/js/common/components/PlayableListSortButton/PlayableListSortButton.tsx, resources/js/features/games/components/GameAchievementSetsContainer/GameAchievementSet/GameAchievementSetToolbar/GameListViewSelectButton/GameListViewSelectButton.tsx
This PR fixes numerous issues with mobile sorting on the beta game page.
The most egregious issue fixed is if the user starts scrolling the page from the scroll button position (not tapping the button), the dropdown opens and scrolling is locked. This is caused by a known issue in the underlying Radix component: https://github.com/radix-ui/primitives/issues/1912. I've made some adjustments in `BaseDropdown` to work around the problem:
https://github.com/user-attachments/assets/4ca07e28-c894-43f0-944e-e54907729ef6
Additionally, two more changes have been made:
1. If the user selects the same sort option that's already selected, the list won't re-sort anymore.
2. When opening the sort order and achievements/leaderboards view dropdowns, the body is no longer scroll locked.
=> fix(game): don't lock mobile scrolling when starting scroll from the sort button
